### ISSUE TITLE
Druid's Flight Form

### ISSUE THREAD

**Issue by Noiminotnaomi** [SallyWhitemane/Mograine#1]
**Description:**
Flight form is not keeping it's momentum after canceling the form.

**How to reproduce:**
Get on druid with flying, and cancel form.

**How it should work:**
It should push you forward, distance is based on your flight speed 150/280.
And you should be falling forward-wise, rather than just STRAIGHT DOWN.

**Resource example:**
https://youtu.be/Q_zJLDE1-sk?t=97

Sunwell had same issue for a while, but they fixed it eventually...
https://github.com/SunwellTracker/issues/issues/352

Hope you fix that too, **thanks**.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contributing!
