### ISSUE TITLE
[Mage] Molten Armor, Mage's 2pT9, Glyph of Molten Armor and Dual Spec

### ISSUE THREAD

**Issue by Synful-Syn** [SallyWhitemane/Mograine#10]
Molten Armor is a mage buff that increases crit by 35% of the spirit.
It can be increased by an additionnal 15% from the 2pT9.
It can also be increased by an additionnal 20% from the Glyph of Molten Armor.

By using the dual spec into a spec that doesn't have the glyph and switching out of the 2pT9 (for something better in example), both bonuses remains.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
