### ISSUE TITLE
[Quest] [Scourge Tactics]

### ISSUE THREAD

**Issue by Matija5** [SallyWhitemane/Mograine#100]
**Description:**
I get dismounted from drake as soon as I get to quest area

**How to reproduce:**
Just get on the drake and start flying towards quest zone

**How it should work:**
You shouldn't get dismounted

**Comment by SallyWhitemane** [comment]
Can't reproduce.

**Comment by Matija5** [comment]
I've just reproduced it myself again on a diffrent character
