### ISSUE TITLE
Bug in EOE (phase 3)

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#1005]
Description: Bug in P3 Malygos
How to reproduce: Guardian Spirit causes you to get stuck in the air
How it should work: well I should die, but instead I get stuck with 2 hp and can't release or ress or be summoned
screenshot: https://gyazo.com/c8ac70d0b3fd91f7890a988113eae19a

**Comment by Raulfin** [comment]
dup of #975
