### ISSUE TITLE
[Shaman] Talent : Static Shock

### ISSUE THREAD

**Issue by way456** [SallyWhitemane/Mograine#101]
**Description:**

When the effect of Static Shock talent (enhancement) triggers , instead of refreshing the shield's stacks , it just consumes it.
This leads to lightning shield wearing off after 9 times that this effect happens.

**How to reproduce:**

Apply Lightning shield while having the talent , attack a dummy and wait for it to proc.

**How it should work:**

When the talent procs, it should apply another 6 stacks of Lightning Shield (not more than 9 total though).

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
