### ISSUE TITLE
[Mage] Ignite is munching

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#102]
**Description:**
If you cast Fireball into (Hot Streak) Pyroblast and both land and crits at the same time the server only register one crit for the ignite damage.

**How to reproduce:**
Use Hot Streak proc instantly after Fireball so they land at the same time as Fireball on the target. See screenshots: ![munch ignite](https://user-images.githubusercontent.com/38737831/102288242-6630e480-3f3c-11eb-864d-36a3965a3a2c.png) ![pyro ignite](https://user-images.githubusercontent.com/38737831/102288262-70eb7980-3f3c-11eb-9598-266e01c1307c.png)

**How it should work:**
Similar to the deep wounds bugreport they should add up into one big ignite

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
