### ISSUE TITLE
Cannot leave arena

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#1020]
Description:
[Arena] Can't leave arena
How to reproduce:
Get into an arena and try to leave arena using the minimap button, nothing happens. You can't leave in waiting room, can't leave after gates open, can't leave after you engage in combat, can't leave after dying, can't leave any bracket including soloq
How it should work:
should be able to leave
Screenshot/video:
March 8, 2021

**Comment by SallyWhitemane** [comment]
intended
