### ISSUE TITLE
Chain heal not jumping to targets at full hp [maybe thats how it should work tho]

### ISSUE THREAD

**Issue by Nyapaweon** [SallyWhitemane/Mograine#1023]
Description:
Chain Heal spell does not jump to targets that are at full health.

How to reproduce:
1. Cast Chain Heal on player, that has other players or pets nearby at full health. Chain Heal won't jump to them.

How it should work:
Chain Heal should always do full 3 (4 with glyph) jumps as long as there are enough targets in each other's proximity.

Targets of Chain Heal should be selected with this priority:

1. Player with highest health deficit should be chosen.
2. Pet/companion with highest health deficit should be chosen.
3. Player in range at full health.
4. Pet/companion at full health.

Also the Chain heal should prioritize group members (party or raid) to others - that does mean to prevent the jump ouside the group, it simply should give higher priority to them over players outside the group. The Chain Heal should generally try to avoid accidentally PvP flagging players.

It does affect mutliple aspects of shaman healing:

1. Talent Ancestral Healing not being applied on targets that would potentially be critted with overheal.
2. talent Improved Water Shield is not being triggered by potential overhealing crits which affect Restoration shaman mana retention.
3. Buff Earthliving from Earthliving Weapon weapon enchant is not being applied on potential targets of overheal jumps. 

Screenshot/video:

![image](https://user-images.githubusercontent.com/79753117/110380888-03417c00-8059-11eb-84fa-1d3bbcf1826d.png)

I have two players in my group - Karafrey and Screvvs. Chain heal was cast on Karafrey, but did not jump to Screvvs.

**Comment by mrnuggets** [comment]
I don't know why this was posted, but let me post the evidence that chain heal should in fact NOT jump to full HP targets.

Retail source: https://youtu.be/CX-K0oV9zmA?t=179 
Retail Source from video - CH not jumping to the full HP paladin next to the tank: https://gyazo.com/dd08bef727981306c42647f4aafaa6cd

If you keep watching the video, you'll also see that Chain Heal is not jumping to full HP targets.

**Comment by alexspew** [comment]
Hi, this works as it should. No further adjustment needed
