### ISSUE TITLE
[Quest] - Stranglethorn Fever second quest 

### ISSUE THREAD

**Issue by Knapec** [SallyWhitemane/Mograine#104]
**Description:** Stranglethor Fever quest is not available from Witch Doctor Unbagwa after completing the first quest from Booty bay (Fin Fizracket).

**How to reproduce:**

**How it should work:** The quest should be available from the NPC (Witch Doctor Unbagwa) after completing frist Stranglethorn Fever.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
