### ISSUE TITLE
TLPD

### ISSUE THREAD

**Issue by sadpanda5** [SallyWhitemane/Mograine#1049]
**Description:**Killed TLPD (Time-Lost Proto-Drake)
![WoWScrnShot_031121_093215](https://user-images.githubusercontent.com/80470803/110805474-1cac1900-824f-11eb-99f8-815634f4c358.jpg) No loot was given...

**How to reproduce:**

**How it should work:**

**Comment by Raulfin** [comment]
The 3 items TLPD can drop are only 98%. it is possible, however extreamly unlikely, for it to drop none.
