### ISSUE TITLE
[Quest] - Bad Medicine - quest item low drop chance

### ISSUE THREAD

**Issue by Knapec** [SallyWhitemane/Mograine#105]
**Description:** Jungle Remedy quest item for Bad Medicine quest should drop from Kurzen Medicine Man, Kurzen Witch Doctor and Kurzen Headshrinker with 50% drop chance on Blizzlike. Drop chance here according to page is 3x, but the real drop chance is less than 20 %.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
