### ISSUE TITLE
Feral tab: All abilities missing previous ranks

### ISSUE THREAD

**Issue by Degatien** [SallyWhitemane/Mograine#1053]
**Description:**
There's no previous ranks when you "show all spell ranks" on the feral tab. https://gyazo.com/f8e848f29063c5e17bd2223fe7497e0e

**How to reproduce:**
I'm tauren feral druid with no racial changes and i'm looking at my spellbook  in feral tab with "Show all spell ranks" ticked.

**How it should work:**
I have no evidence but all spells for all classes can show all spell ranks in their spellbook so I think this is a bug

**Comment by Platinumcoated** [comment]
"I have no evidence"
well, then your report is invalid

As far as i know, this has been a thing since vanilla, because there is literally no reason to use lower ranks of these abilities.

**Comment by Raulfin** [comment]
there should not be lower ranks of rage/energy based skills, only mp based skills.
