### ISSUE TITLE
Skinning in duskwood

### ISSUE THREAD

**Issue by Degatien** [SallyWhitemane/Mograine#1054]
**Description:**
When i loot the mobs i still have the empty loot window and i can't skin them. The game still see the mob as not looted

**How to reproduce:**
I was in duskwood with my rogue but i don't know if it's a zone related issue

**How it should work:**
It should work that after i loot the mob i'm able to skin it. Here's a proof of what i'm saying: 
https://www.youtube.com/watch?v=P3gLlFMvk9s

**Comment by Royalwax** [comment]
duplicate #261
