### ISSUE TITLE
Blood gorged talent Bug

### ISSUE THREAD

**Issue by Zeorgbugfinder** [SallyWhitemane/Mograine#1061]
Blood gorged talent should give 10% armorpenetration instead of 10% sunder armor

...yes its 2 different things

with 10% arpen talent u need 90% arpen from gems and it makes it 100% arpen total
with 10% sunder armor talent u still need 100% arpen from gems coz it first reduce armor from sunder armor and then reduce armor from gems

this makes 10% arpen way way better than 10% sunder armor

**How to reproduce:**
on PTR i tried BDK with 100% arpen(full arpen gems) and 90% arpen(str gems coz no need more arpen if talent works properly) and it was doing less dmg with 90% arpen than 100% arpen it means that talent doesnt give 10% arpen but 10% sunder armor
 - so when u have 90% arpen and talent gives 10% sunder armor it basicly gives 91% arpen total -> means u still need arpen gems thats why i did less dmg with 90%arp+str gems than 100%arpen

**How it should work:**
it should give 10% arpen like warrior's battle stance

on warmane it works properly thats why some ppl are playing BDK on PVE as DPS there with 90%arpen

https://www.mmo-champion.com/threads/720712-Blood-DK-how-much-ArP    -discussion from 2008 wotlk retail
http://forum.warmane.com/showthread.php?t=290640&page=4      - some discussion about it on warmane

**Comment by danniellos94** [comment]
Voting up this is true, you only need 90% arpen (1260) as blood dk to reach the cap.
