### ISSUE TITLE
Quest "Dragonmaw Race: Captain Skyshatter" bugged else the Archievment "Skyshattered" bugged

### ISSUE THREAD

**Issue by oli13371** [SallyWhitemane/Mograine#1071]
**Description:**
Quest "Dragonmaw Race: Captain Skyshatter" bugged else the Archievment "Skyshattered" bugged. To reach to the last guy u have to complete the flying vs other 5 guys, that actually took me a while...after that i reach the last one to get the Archievment and he bugs as you can see in the video.

**How to reproduce:**
Start last q "Dragonmaw Race: Captain Skyshatter". I Have a video of it but its way to big, so yeah.

**How it should work:**
You should be able to fly against him and if u win the fly get the Quest done and get the Archievment.

**Comment by Royalwax** [comment]
#850 duplicate
