### ISSUE TITLE
4h 10 man bugged loot

### ISSUE THREAD

**Issue by butcheeseon12** [SallyWhitemane/Mograine#1075]
**Description:**
We killed 4h on 10 man and all rolled group loot need/greed but no loot was distrubuted to us. The loot is still there I’m standing. At the box with it but on group loot it says it’s still being rolled on. On master looter it says this will bind it to you but doesn’t loot it. 

**How to reproduce:**
Hell if I know 

**How it should work:**
We should have gotten the loot and I shouldn’t be looking at it still there but can’t get. Timer for roll should have run out.

**Comment by herbhenk** [comment]
open ticket for support with the loot
