### ISSUE TITLE
Omen of Clarity does not proc on Faerie Fire

### ISSUE THREAD

**Issue by Grzegorz-Kolaty** [SallyWhitemane/Mograine#1076]
**Description:**
Please analyze this problem.
I have seen that my logs are different from the other servers - there is lack of Omen of Clarity on druid DPS Feral.

**How to reproduce:**
Faeire Fire (in Cat Form!) should have 10% to proc this. Now it has 0%

**How it should work:**
Omen of Clarity should be able to proc when I use Faerie Fire while in Cat from.

**Comment by gandalkk** [comment]
It worked fine last week unless something happened but its 6% not 10

**Comment by styxel** [comment]
all good every server has different way of scripting ooc i personally think its working correct here. Idk if u come from sunwell but its still bugged there

**Comment by Grzegorz-Kolaty** [comment]
I think it does not work properly so I asked to repair it. I met many feral druids and this makes casting faerie fire useless, when no energy.
