### ISSUE TITLE
Low quest item drop rate

### ISSUE THREAD

**Issue by Knapec** [SallyWhitemane/Mograine#108]
**Description:** After few hours of leveling I am confident to say that many quests items have lower drop chance than on blizzlike or they have drop chance like on blizzlike. From what I have read on the page items drop rate should be 3x, so I believe this concerns majority of quests. I dont know if I should report every quest or it is possible to repair it globally.

**How to reproduce:**

**How it should work:**

**Comment by SallyWhitemane** [comment]
Max loot rate was set at 30%, so if some quest had more than 30% it wasn't increased by x3, i excluded all quest items from this max loot rate check, let me know how it works, it'll be applied on next update. Thanks for contribution.

**Comment by Knapec** [comment]
I was trying that today, at first I thought it works but it turned out it
still works like before. For example "Irradiated Crystal Shards" quest
doesnt work according to the server rates (and most of the other quests i
just wanted to state an example that you can try).

so 19. 12. 2020 o 4:04 Whitemane <notifications@github.com> napísal(a):

**Comment by Knapec** [comment]
I think something even went worng because yesterday evening I was doing
"Demonic Contamination"(https://wotlkdb.com/?quest=9372) where you have to
get 6  Helboar Blood Sample
<https://www.wowhead.com/item=23336/helboar-blood-sample>, they have 33%
drop according to wowhead and 30% according to wotlkdb and I needed to kill
around 30 of them, maybe just bad luck but felt like worse than blizzlike
drop. And also  "Cursed Talismans" (https://wotlkdb.com/?quest=10484) quest
felt worse than blizzlike, I had to spend there around 20 minutes farming
them. I was doing these quests also before the fix that you applied and it
was quite better.
so 19. 12. 2020 o 19:49 Vidžaja Knap <knapec1@gmail.com> napísal(a):
