### ISSUE TITLE
Warrior - Arms - Sudden death has stopped working.

### ISSUE THREAD

**Issue by Sippiey** [SallyWhitemane/Mograine#1098]
**Description:** Sudden death consumes the rage but doesnt yield a execute hit at all, the only time execute works is when the mob is below 20% hp. I did 3 hours of raiding today and it was consistently not working through out the entire raid period. This along with sword spec not working properly makes warrior unplayable.

**How to reproduce:**
https://www.twitch.tv/videos/970462772 - Here you see a short video of me showing 2 sudden deaths procs that consumes the rage and does no dmg at all, it doesnt even show up in the combat text.

**How it should work:**
When you you cast execute with a sudden death procc active, a execute should occur.

**Comment by danniellos94** [comment]
It's working now it's fixed.
