### ISSUE TITLE
[Mage] 2pT7 and trinkets

### ISSUE THREAD

**Issue by Synful-Syn** [SallyWhitemane/Mograine#11]
Using some trinkets first then using a Mana Sapphire won't proc the spell power bonus from the 2pT7 set.

Trinkets that I tried and didn't gave the buff
Living Flame, 45148
Energy Siphon, 45292
Loatheb's Shadow, 39257
Mark of Norgannon, 40531

Trinkets that I tried and gave the buff
Spirit-World Glass, 39388
Rune of Repulsion, 40372

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
