### ISSUE TITLE
[Fishing] Crescent-tail Skullfish cannot be fished

### ISSUE THREAD

**Issue by jaca93** [SallyWhitemane/Mograine#1102]
As in the subject, this fish is supposed to have 20% fish rate in Deadwind Pass. It does not , I've been there for over 2 hours now fishing near Karazhan as the guides suggested and didn't catch a single one of these.

My fishing skill shouldn't be the problem either as with all buffs its over 500 .

This fish is required for Skullfish Soup - which is required for The Outland Gourmet achievement.

**Comment by Belpheris** [comment]
It is fish-able inside Zul Aman waters in less than 1 minute. Can close ticket.

**Comment by herbhenk** [comment]
duplicate: https://github.com/SallyWhitemane/Mograine/issues/1122
