### ISSUE TITLE
Glyph of Felguard is not working properly

### ISSUE THREAD

**Issue by Ghostgm** [SallyWhitemane/Mograine#1107]
**Description:**
Glyph of Felguard is Decreasing damage instead of increasing damage

**How to reproduce:**
Use Glyph of Felguard and run sim, then try without. 

**How it should work:**
Should increase Felguards damage by 20%
https://youtu.be/xplSlZCVMEc
https://youtu.be/InioKzRhF4w

**Comment by danniellos94** [comment]
All the bugs are in here https://github.com/SallyWhitemane/Mograine/issues/1088
From what I see felguard glyph increase damage - even on video you can see when he is stacked he hits more.

**Comment by Ghostgm** [comment]
try it yourself mate. its definitely not working properly @danniellos94

**Comment by danniellos94** [comment]
Increasing 20% attack power doesn't mean increasing damage by 20%. 

The target have armor you will see more difference on a 50-60 lvl target dummy because it has lower armor. 

The glyph obv works and increases felguard attack power by 20%.
