### ISSUE TITLE
[PALADIN] Seal of Righteousness doesn't deal damage on auto-attacks

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#111]
**Description:**
Seal of Righteousness fails to deal damage on auto-attacks. Damage on special attacks (such as Judgements) works fine.
Tested at low levels as well as level 80.

**How to reproduce:**
Cast Seal of Righteousness, auto-attack an enemy, observe Seal of Righteousness damage not being dealt.

**How it should work:**
Seal of Righteousness should cause auto-attacks as well as special abilities to deal extra damage.

**Comment by Kupcakez** [comment]
It also for some reason is acting as a pseudo reckoning granting extra auto attacks randomly

**Comment by Beefcaqe** [comment]
Working after server restart. Presumably fixed now.
