### ISSUE TITLE
[Warlock] Demon state after summoning

### ISSUE THREAD

**Issue by melezdev** [SallyWhitemane/Mograine#1110]
**Description:**
Pretty sure summoning a new demon should reset his state including: health, mana, buffs, debuffs, cooldowns. Currently, buffs are cooldowns are not reset. Example: after summoning a new felguard, he cannot intercept immediately if the old one has used it in the last 30 sec.

**How to reproduce:**
Buff the pet, use a cooldown, summon again.

**How it should work:**
As described above. Not entirely sure about the buffs part, but I know people on other servers had macros to summon a new felhunter and silence immediately to stop a crucial heal in arenas.

**Comment by herbhenk** [comment]
this is invalid on retail the cooldowns on pets where not reset you can find multiple threads on trinitycore discusing this with the general consensus being it shouldnt reset cooldows
here: https://github.com/TrinityCore/TrinityCore/issues/4005
