### ISSUE TITLE
[DESTRUCTION WARLOCK] Rain of fire bug.

### ISSUE THREAD

**Issue by MadeinNoxus** [SallyWhitemane/Mograine#1124]
**Description:**
"Bug 01: The Backdraft doesn't make warlock's Rain of Fire spell faster and it doesn't count as a tick of 3 Backdrafts.
Bug 02: Empowered imp proc only works on one tick on Rain of Fire."

**How to reproduce:**
"Bug 01: Immolate then Conflagrate then cast a Rain of Fire.
Bug 02: Wait for Empowered imp proc then cast a Rain of Fire."

**How it should work:**
"Bug 01: Reduce by 30% Rain of Fire's cast time when Backdraft is up.
Bug 02: Empowered imp should be up during all Rain of fire's cast."

**Comment by herbhenk** [comment]
this is invalid it shouldnt work for channeled spells
here: https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire?p=6039937&viewfull=1#post6039937
you can see people in 2009 saying it never affects the channel time
for bug 2 i cant find much documentation but those kinda buffs generaly dony apply to channeld spells
