### ISSUE TITLE
Engineering nitro boosts

### ISSUE THREAD

**Issue by MadeinNoxus** [SallyWhitemane/Mograine#1127]
**Description:**
after using it i fly in the air, i have video of that too.

**How to reproduce:**
Im mage, it happened in stormwind next to gate, i just use the boots and i fly up in the air and die from that.

**How it should work:**
just use the boosts. here is video : https://drive.google.com/file/d/1AJtyBlw6labriTXVVhXbKaBCv1bOsB9d/view?usp=sharing

**Comment by danniellos94** [comment]
This is how nitro boots work, they dont always work, That's why you usually use parachute in pvp.

It shouldn't make you fly only in closed area like raids (for example lich king fight).
