### ISSUE TITLE
Oculus bug - Mage-Lord Urom cannot be attacked

### ISSUE THREAD

**Issue by MadeinNoxus** [SallyWhitemane/Mograine#1129]
**Description:**
Some warlock's pet pulled Mage-Lord Urom and we wiped while our healer was in combat and not in the platform, so he wasn't able to be in the balcony. We runned back after all dying and both Eregos and Urom are untargettable.
**How to reproduce:**
"Warlock's Felguard pulled while our Druid healer was far away and unable to ride his drake back to the balcony (in combat).
We wiped, ran back and all the remaining bosses are untargettable."
**How it should work:**
Should not get bugged??

**Comment by danniellos94** [comment]
I will add that sometimes mage-lord Urom is bugged that he dont attack anyone at all he just stands while getting killed.
