### ISSUE TITLE
[Hodir Ulduar 10man] Hardmode - Not getting completion.

### ISSUE THREAD

**Issue by MadeinNoxus** [SallyWhitemane/Mograine#1159]
**Description:**
"We killed Hodir Hardmode in under 3 minutes, which used to be the ""normal"" Hardmode time but didnt receive the second lootchest nor the achiev. 

Raid ID: 2385"

**How to reproduce:**
Raid ID: 2385

**How it should work:**
Hardmode completed if the boss is killed in under 3 minutes?

**Comment by lachtanek** [comment]
it's the prenerf version so it's 2 minutes

**Comment by herbhenk** [comment]
working as intended
