### ISSUE TITLE
Blood tap

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#116]
**Description:**
When one blood rune is on cd and you use blood tap it instantly refresh the blood rune that is cd and turns it into death rune but also converts the remaining blood rune into death rune

**How to reproduce:**
Create a dk , spec into blood of the north , use blood strike and then blood tap.

**How it should work:**
only the one on cd should convert into death rune , the other blood rune should remain

**Comment by SallyWhitemane** [comment]
See https://www.mmo-champion.com/threads/842797-The-EXACT-mechanics-of-Blood-Tap-an-inquiry. This is a bug which existed on official servers and had an impact on the game experience. To remain truthful to the original design, it will not be fixed.
