### ISSUE TITLE
Enhancement Shaman

### ISSUE THREAD

**Issue by Fibraottica** [SallyWhitemane/Mograine#1169]
good evening,
i write u for asking some informations about my char/class.
Its since naxxramas that my char doesn't do the normal dps that i should to with my gear. I dont know if there are some issues with all the shaman enhancement or is my char in some strange case bugged. i think it is the second option. For exemple yesterday on the same boss with the same buff/procs the damaged are changed. 1st try i've done a lightning bolt with 12k crit. the 2nd try on the same boss with the same buffs/procs it was only 8k.
i play enha for 5 years and never saw that low dps on a enha shaman aswell. i played on different servers and no issues with that class but here i notice that the shaman enha is "nerfed".

i hope u will check my char and do something. so is impossible for me to play my favourite class because i'm always on the last place in dps and i can not join raid with this kind of dps.

ty in advice

Name of the char: Fibraottica (Draenai alliance)

**Comment by herbhenk** [comment]
please use proper bug report template
