### ISSUE TITLE
Stormchops

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#117]
**Description:**
Stormchops does not have any ICD

**How to reproduce:**
Make a character,buy stormchops from Misc vendor and hit the dummy

**How it should work:**
Stormchops should have 8sec ICD https://www.wowhead.com/item=33866/stormchops#comments

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
