### ISSUE TITLE
[Paladin] Sacred Shield healing attributed to recipient opposed to caster

### ISSUE THREAD

**Issue by Quillenator** [SallyWhitemane/Mograine#1170]
**Description:**
The wearer of the sacred shield is awarded the healing mitigation generated from its effect, opposed to the caster of the spell. 

**How to reproduce:**
1. Have a Paladin and a party member enter combat.  
2. Have the Paladin cast sacred shield on the party member.
3. Have the friendly unit take damage, triggering the sacred shield effect and mitigating X damage.
4. Have the Paladin heal himself or the friendly target for Y health, no over-healing.
5. End Combat.
6. Review the combat log to see the the friendly unit has contributed X healing, and the Paladin has contributed Y healing.

**How it should work:**
The Paladin should be the source of the healing when reviewing combat logs, i.e.,
1. Have a Paladin and a friendly unit enter combat.  
2. Have the Paladin cast sacred shield on the friendly unit.
3. The friendly unit takes damage, triggering the sacred shield effect and mitigating X damage.
4. The Paladin heals himself or the friendly target for Y health, no over-healing.
5. End Combat.
6. Review the combat log to see the the friendly unit has contributed 0 healing, and the Paladin has contributed X+Y healing.

**Comment by herbhenk** [comment]
duplicate https://github.com/SallyWhitemane/Mograine/issues/1148
