### ISSUE TITLE
[PALADIN][ITEM]Unholy Knight's bracers doesn't provide correct endurance

### ISSUE THREAD

**Issue by dunmil** [SallyWhitemane/Mograine#1171]
**Description:**
Unholy Knight's bracers (ilvl213) provides too much endurance.
74 + 12 (gem) + 40 (enchant) = 124 endurance
But they provide 156 in Ret spec, 172 in Prot spec
Other stats seems correct

**How to reproduce:**
Equip or unequip item show that the values are wrong (total endurance and health).
Comparing with another item that has sligthly more endurance but give less total endurance and health shows it again.

**How it should work:**
Should provide only 124 endurance (132 in Prot spec)

**Comment by Platinumcoated** [comment]
might be your meta gem

**Comment by dunmil** [comment]
/dumb
Of course it's the metagem.
Thx for your support.
