### ISSUE TITLE
NPC Kvaldir Mist Lord (25496)

### ISSUE THREAD

**Issue by vut12** [SallyWhitemane/Mograine#1186]
**Description:**
NPC Kvaldir Mist Lord (25496)
Doesn't use spell "Wave Crash"

**How to reproduce:**
**How it should work:**
Should use spell "Wave Crash"
proof: https://www.wowhead.com/npc=25496/kvaldir-mist-lord#comments:id=447645

**Comment by herbhenk** [comment]
can confirm the mob currently does not cast wave crash (https://www.wowhead.com/spell=49922/wave-crash)
