### ISSUE TITLE
[Druid] T8 Restoration 4P Bonus - wrong numbers according to actual content

### ISSUE THREAD

**Issue by pnetrio** [SallyWhitemane/Mograine#1192]
**Description:**
Druid T8 Restoration 4P Bonus — Your Rejuvenation spell also instantly heals your target for its periodic healing amount.

**How to reproduce:**
Cast Rejuvenation on yourself with 4P T8 on.

Your Rejuvenation spell also provides an instant heal for your target.
-Heals for about half of what a Rejuvenation tick does, flasked and buffed for 2431 spell power
1132 Initial Ticks
2054 Ticks for rest of duration

**How it should work:**
The difference between first tick of rejuvenation and the rest should not be this big.
The initial tick should not heal the same amount as a normal tick would, doesnt scale with the talents Genesis, Improved Rejuvenation, or Gift of Nature. It does scale with Empowered Rejuvenation, Master Shapeshifter, and Tree of Life.

In a later patch, after Trial of the Grand Crusader was release, the set bonus was nerfed because it was too strong compared to the new tier.
"Druid Tier-8 Healer 4-Piece Set Bonus: The amount of healing this set bonus grants on the initial cast of Rejuvenation has been reduced by 50%."

I am asking for set values for initial heal to pre 3.2.2 values which devalued this 4P bonus in next season.

Source (you should point out proofs of your report, please give us some source):
http://wowwiki.wikia.com/wiki/Patch_3.2.2
http://www.wowhead.com/spell=64760/item-druid-t8-restoration-4p-bonus#comments

**Comment by Platinumcoated** [comment]
I remember looking this up and initial ticks of 1000+ are in line with blizz values after the nerf. 

But so far it looks like Whitemane uses 3.3.5 balance and mechanics, so that would be the correct value

**Comment by pnetrio** [comment]
> I remember looking this up and initial ticks of 1000+ are in line with blizz values after the nerf.
> 
> But so far it looks like Whitemane uses 3.3.5 balance and mechanics, so that would be the correct value

I agree with you that at 3.3.5 it is correct value. This set bonus was nerfed after ToC release, because T8 was so OP and overhelms T9 bonus. On the other hand, we have no ToC released yet and in T8 season it isnt fair to lower resto druid's power. Is it possible to change it to pre 3.2.2 numbers than change it back to current after ToC will be up?
