### ISSUE TITLE
Unskinnable Dire Wolves in Duskwood 

### ISSUE THREAD

**Issue by Mimle** [SallyWhitemane/Mograine#1193]
**Description:**
- NPC's in zone Duskwood: Rabid Dire Wolf and Starving Dire Wolf are unskinnable. 
- After looting, the cursor remains as a looting-cursor instead of a skinning-cursor, and nothing happens when clicking the corpse after looting it. 

**How to reproduce:**
Kill a Rabid Dire Wolf or Starving Dire Wolf
- Loot it
- Try to skin it 

**How it should work:**
Kill a Rabid Dire Wolf or Starving Dire Wolf
- Loot it
- The skinning-cursor appears instead of the looting-cursor: 
- You can succesfully start skinning it

**Comment by Royalwax** [comment]
#261 duplicate
confirmed trying myself
