### ISSUE TITLE
[NPC] Stoic Mammoth 30260

### ISSUE THREAD

**Issue by vut12** [SallyWhitemane/Mograine#1195]
**Description:**
Two Stoic Mammoth spawn at all spawn points.

**How to reproduce:**
**How it should work:**
Only one npc should spawn at each point

**Comment by herbhenk** [comment]
can confirm
https://imgur.com/a/jkJBjkS
the mammoth (https://wotlk-twinhead.twinstar.cz/?npc=30260) is spawning 2 mamoths instead of just 1 per spot

**Comment by scrublama** [comment]
Duplicate of #864
