### ISSUE TITLE
[Druid][Skill] Track Humanoids not Auto-Learned

### ISSUE THREAD

**Issue by Vortexsphere** [SallyWhitemane/Mograine#1196]
**Description:**
The skill, Track Humanoids, for Feral, should be auto-learned at LV32. It currently isn't auto-learned, although it does appear in the trainer list.

**How to reproduce:**
Reach LV32 on a druid. Observe that Track Humanoids isn't auto-learned and instead appears in the trainer skill list.

**How it should work:**
As per the set up of the server, it should be on the auto-train list of skills for the druid class.

Apparently this bug is occurring with a number of skills and the GM that responded to my ticket said as much. This seems like a pretty simple bug to fix thankfully. In any case, a minor issue.

**Comment by cachocarne** [comment]
Yet only happens with druids. Not only Track Humanoids, but also Mangle (Cat) and Mangle (Bear).
