### ISSUE TITLE
Deterrence

### ISSUE THREAD

**Issue by tankpajzl** [SallyWhitemane/Mograine#1197]
**Description:**
 grant 100% parry and 100% chance to "deflect" spells

**How to reproduce:**
Abilities req attacks from behind like shred or backstep ignore whole mechanics and u get killed (rly nice in arena , when u on low hp going for dete and thinking about how "save"u are....got 2x shreds and u are dead) PLS HURRY, ARENAS VS FERALS/SUB ROG ARE IMPOSSIBLE TO WIN

**How it should work:**
only abilities req stealth can go through....and if u are cheapshoted/pounced then all attacks come through also...but this....

**Comment by AkinozWhitemane** [comment]
Sorry to say this but since you cant parry from behind its not a bug that abilities like backstab, ambush or shred go through and you can trust me on this one i play wotlk hunter since almost 10 years and wotlk in general over 10 years and this is normal

**Comment by Royalwax** [comment]
Works as intended.

**Comment by tankpajzl** [comment]
Akinoz, u are the dumbest hunter player in history of pvp wotlk hunters when u said this xD now, i asking you once more... fix this bug

**Comment by tankpajzl** [comment]
https://wowwiki-archive.fandom.com/wiki/Deterrence   u dumb fuck.... look at patch notes..im playing hunter from tbc to wotlk over 14 or 15 years im 3k exped gladiator hunter on plenty of servers and I KNOW how it should work or can u read english ?? "100% while under its effect.
World of Warcraft: Wrath of the Lich King Patch 3.2.0 (04-Aug-2009): This ability now allows the hunter to parry spells and attacks from behind as well as in front. Now has a new visual spell effect.""  HOW EVEN DARE TO ARGUE WITH ME... IM THE GOD U CUNT
