### ISSUE TITLE
Reins of the Traveler's Tundra Mammoth - when eject NPC's, they instantly disappears

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#12]
Description: when eject NPC's on Traveler's Tundra Mammoth or dismount , they instantly disappears. Tested both horde, alliance

How to reproduce: mount up, eject them. 

How it should work: They should stay for some 5 seconds on the ground, then disappears.
[video](https://youtu.be/sUpQEJUhSjA?t=272)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by matalukes** [comment]
Still doesn't work properly, please check it out. Thanks
