### ISSUE TITLE
Can't use Barbershop on Taurens !!! 

### ISSUE THREAD

**Issue by IkeVianna007** [SallyWhitemane/Mograine#1201]
**Description:**
I got a Tauren Druid named Bono, and after sit the chair and select the horn, skin tone and etc when i click to apply it just nothing happen ! and if i click a lot of times i got DC from server. The same thing happened to a friend Tauren Warrior.

**How to reproduce:**

**How it should work:** It suppose to change my visual and make me look beutiful. I'm brown, when i turn to bear i look like a big piece of shit. Pls fix that ://

**Comment by Royalwax** [comment]
Confirmed d/c once hitting the accept button. Tried on my female druid. 
2x attempts
