### ISSUE TITLE
Yogg Saron 25 Man Psychosis in Brain

### ISSUE THREAD

**Issue by Dysiu** [SallyWhitemane/Mograine#1202]
**Description:**
Sara Psychosis (Spell ID 65301) attack players who are in the brain.

**How to reproduce:**
Go inside the brain, in every try we were attacked by Sara's Psychosis in the brain.

**How it should work:**
Sara shouldn't target players in the Yogg's Brain

**Comment by dhave2014** [comment]
seems like we've had this same issue in our guild tries on HM

**Comment by pocghamp** [comment]
[Combatlog visual representation](https://gyazo.com/b6566a746f0462591c7171299804abf4) of illusion room buff(colored bars) and people getting hit by psychosis (the dots).

**Comment by Dysiu** [comment]
Here is also a small video, check my sanity ;) https://streamable.com/9tvxqi
