### ISSUE TITLE
Weapon Enchant Berserking

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#121]
**Description:**
Right now the enchant is proccing too often.

**How to reproduce:**
Enchant your weapon with it.

**How it should work:**
Should proc less often https://www.wowhead.com/spell=59621/berserking#comments

**Comment by Matija5** [comment]
hmm I think you got lucky or something, on my rogue it's not proccing that often, actually it's not even procing often. 
I'm using 2.6 fist wep 1.4 dagger with slice and dice up. In 2 min of attacking it proced once from both weapons, then I continued to attack for 5 min and it proced in total 3 times. So I definitely think that there's internal CD on it or I got unlucky
