### ISSUE TITLE
[NPC] Sunfury Researcher - Formula drop rate

### ISSUE THREAD

**Issue by player091** [SallyWhitemane/Mograine#1216]
**Description:**
I believe there is a problem with drop chance of Formula: Enchant Weapon - Major Intellect.
I've been farming Sunfury Researcher west of Kirin'Var Village in Netherstorm. According to dropcalc site, chances are:

Sunfury Signet - 28%
Arcane Tome - 1.8%
Formula: Enchant Weapon - Major Intellect - 1.5%

Every mob dropped Sunfury Signet, so i guess drop rate is increased. Now i have:

1000x Sunfury Signet
75x Arcane Tome
0x Formula: Enchant Weapon - Major Intellect

Numbers say i should have plenty of formulas, but i have none, so i believe there is a problem.

**How to reproduce:**
Kill 1000 Sunfury Researchers

**How it should work:**
It should be possible to drop formula.

**Comment by Royalwax** [comment]
drop rate is correct. TBC patterns are about 1% in open world. Pattern does drop.

**Comment by player091** [comment]
No drop after killing something over 2000 Sunfury Researchers. Guess i'm overly unlucky then?

**Comment by Royalwax** [comment]
2 of them have dropped for me in under 10mins less than 20 killed. What level is your enchanting at?

**Comment by player091** [comment]
Now i understand, sorry for bothering you. I farmed it with toon, not echanter. I didn't know that i need to be an enchanter to drop formula because i remember farming those Researchers on other server with feral, who for sure wasn't enchanter.
