### ISSUE TITLE
Celestial Steed Mount Speed Bug

### ISSUE THREAD

**Issue by Modmod-dot** [SallyWhitemane/Mograine#1223]
**Description:**
The Celestial Steed's mount speed is not updating to 310%. (Yes, I own a 310% mount- Yes, I cleared my cache files like a GM instructed me.)

**How to reproduce:**
When I encountered the bug, I tried /reload, relogging, and sending in tickets. I kept getting the answer, "You need to own a 310% mount", despite describing I owned one, and I have fast flying. I am a Paladin and I logged into Dalaran after buying the steed from the website. If you want to try and reproduce the bug, then get the Big Love Rocket, then a Celestial Steed and see if the mount speed updates or not. Though a guild mate bought the ashes after buying the Celestial Steed, and then the mount updated. It might be the order in which the mounts were obtained, but this shouldn't matter.

**How it should work:**
If you own a 310% mount, and get a mount capable of reaching that speed (in this case the Celestial Steed), it should update properly. Whether you have the 310% mount before, or get it after obtaining the Celestial Steed. There should be no need for evidence when all you need to see is people riding a 310% Celestial Steed, and you can ride on one as well.

**Comment by danniellos94** [comment]
With deleted cache and faster flying. Before It was 280% (mostly visual bug still) working now correctly.

https://prnt.sc/11z4gfr

**Comment by Modmod-dot** [comment]
Well that's the thing- I have the fastest flying, 5000 gold, and I've already deleted my cache. Still not working. Yes, I own the Big Love Rocket too, and it flies at 310% but the Celestial Steed still flies at 280%.

**Comment by Royalwax** [comment]
Might need to put in a ticket if this is still going on.
I have tested and my steed is at 310% now that I have a 310% mount

**Comment by Modmod-dot** [comment]
I've put in multiple tickets, and posted a thread on github as directed but
to no avail. I guess it won't hurt to email though.

**Comment by Royalwax** [comment]
I would like to know what 310% is currently learned for more information
