### ISSUE TITLE
Grom'Thar not dropping quest item 

### ISSUE THREAD

**Issue by vassal44** [SallyWhitemane/Mograine#1230]
Description:

When I killed Grom'Thar, it wouldn't let me loot his head. His corpse appeared to be empty, with no loot, when I hovered my mouse over it. When I right clicked on it, it didn't give any loot or open the loot window. I tried killing him again and the same result happened

How to reproduce:

I was on my orc hunter named radcab, using a bull as a pet. I killed the Grom'Thar twice, once in survival spec and once in beast mastery spec. 
Here are some links to screenshots that might help. Two of them show the corpse without loot and one shows the combat log to prove that i killed it. 
https://imgur.com/nakAzjc
https://imgur.com/QSTPtUp
https://imgur.com/69QG8uQ

How it should work:

It should drop his head, a quest item, to turn in for the quest.

**Comment by herbhenk** [comment]
in the pictures you appear to be in a raid you need to leave the raid in order to loot certain quest items
