### ISSUE TITLE
Dragonmaw Race: Captain Skyshatter!

### ISSUE THREAD

**Issue by Heidish00** [SallyWhitemane/Mograine#1233]
**Description:**
Dragonmaw Race: Captain Skyshatter at Netherwing Ledge. At the beginning of the race the captain just bugs out by spam moving back and forth, which leads up to the quest failing.

**How to reproduce:**
I happens on every attempt of the quest!

**How it should work:**
The quest has a route for the Captain, which you have to follow to succeed and get the achievement "Skyshattered".

**Comment by Royalwax** [comment]
duplicate #850
