### ISSUE TITLE
Get to Getry bugged respawn

### ISSUE THREAD

**Issue by whitemanetribe** [SallyWhitemane/Mograine#124]
**Description:**
The mob Getry for the quest "Foolish Endeavours" has an abnormally long respawn after the quest is completed - he also spawned once and disappeared - respawned again after another 5 minutes

**How to reproduce:**
Complete Foolish Endeavours

**How it should work:**
Should spawn much quicker at the top of the tower, or RP walk back up the tower and become interactable again once the RP is concluded.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
