### ISSUE TITLE
Demonic Knowledge issues

### ISSUE THREAD

**Issue by seaneffigy21** [SallyWhitemane/Mograine#1246]
**Description:**
1. Demonic Knowledge not giving correct AP to the warlock. An unbuffed imp, with 1156 stamina, and 762 intellect. 1156+762=1918x(0.12) =230.16 SP is how much my warlock should get. Instead, my warlock gains 210 SP.

My imps stats:
![imp stats](https://user-images.githubusercontent.com/67831462/116178404-88552300-a6e3-11eb-8be5-752fada116cd.png)

My SP without pet
![SP without pet](https://user-images.githubusercontent.com/67831462/116178419-8f7c3100-a6e3-11eb-9589-98532dcc7e3a.png)

My SP with pet
![SP with pet out](https://user-images.githubusercontent.com/67831462/116178423-90ad5e00-a6e3-11eb-9140-01ada18f3b18.png)

**How it should work:**
I should gain 230 SP from my pet instead of 210, giving me ~3015 SP.

**Comment by danniellos94** [comment]
https://github.com/SallyWhitemane/Mograine/issues/1088

**Comment by danniellos94** [comment]
The issue can be closed demonic knowledge works correctly after fix.
