### ISSUE TITLE
Shadow Priest Invisible Bug

### ISSUE THREAD

**Issue by ZombieZzZzZ** [SallyWhitemane/Mograine#1249]
**Description:** So interesting invisible bug

**How to reproduce I founded in Dun Morogh I'm a priest I dont now ho can you reproduce it but ı think its very big bug
but its only works in mount ı tested

**How it should work:** When you not in shadow form and open 'Dispersion' and go to the shadow form again you are invisible

https://user-images.githubusercontent.com/83389441/116507183-716f2600-a8c7-11eb-9180-0b4af4d3532d.png

**Comment by SallyWhitemane** [comment]
it's clientside
