### ISSUE TITLE
Mind Sear

### ISSUE THREAD

**Issue by Lurkingmist** [SallyWhitemane/Mograine#1256]
**Description:**
The priest aoe ability Mind Sear is not able to be used on a friendly target. This is a great ability for arena with a priest and was like that in retail wow. At the moment a priest trying to aoe a group will always hit 1 less target because of this bug. It is intended to pulse aroud the target no matter if the target is friendly or foe.

**How to reproduce:**
Target any friendly character in your party and try to cast "Mind Sear". It will say not "invalid target"

![WoWScrnShot_043021_150712](https://user-images.githubusercontent.com/83457534/116699419-d90b9b00-a9c5-11eb-8502-a6515351469b.jpg)
![WoWScrnShot_043021_150653](https://user-images.githubusercontent.com/83457534/116699458-e2950300-a9c5-11eb-9158-5f17c28bae0a.jpg)

**How it should work:**
It should pulse aoe damage to everyone who is neutral or unfriendly and damage them. The one casted on is not harmed at all.

**Comment by herbhenk** [comment]
invalid using mind sear on friendly targets was only introduced in patch 4.0.6

https://wowwiki-archive.fandom.com/wiki/Patch_4.0.6
