### ISSUE TITLE
Alliance area in Dalaran triggers teleports outside restricted area. 

### ISSUE THREAD

**Issue by Zirda** [SallyWhitemane/Mograine#126]
**Description:**
The Alliance area in Dalaran teleports horde players outside the bounds. 

**How to reproduce:**

https://youtu.be/GYfO_o5V2CI
https://youtu.be/XLqZAQEKk5A
https://youtu.be/Rrve9oa5OUE

**How it should work:**
It should only teleport horde players that walk past the guards in the main entrance or flies in from above. Not these areas outside.

**Comment by Zirda** [comment]
It is also possible to blink past the guards in the alliance inn and not get teleported out:
https://youtu.be/wUzWZCRvw_U
And access alliance badge vendors:
https://youtu.be/2nILFbsRGJ0

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
