### ISSUE TITLE
ilvl 200 Relics gone

### ISSUE THREAD

**Issue by Raulfin** [SallyWhitemane/Mograine#1265]
**Description:**
All ilvl 200 relics have been removed from the Heroism vendors and relic vendor.
Ninsianna 29529
Magistrix Lambriesse 31582
Arcanist Ivrenne 31580

[Idol of Lush Moss] | Idol | 40711
[Idol of Steadfast Renewal] | Idol | 40712
[Idol of the Ravenous Beast] | Idol | 40713

[Libram of Obstruction] | Libram | 40707
[Libram of Reciprocation] | Libram | 40706
[Libram of Renewal] | Libram | 40705

[Sigil of Haunted Dreams] | Sigil | 40715
[Sigil of the Unfaltering Knight] | Sigil | 40714

[Totem of the Elemental Plane] | Totem | 40708
[Totem of Splintering] | Totem | 40710
[Totem of Forest Growth] | Totem | 40709

**Comment by mrnuggets** [comment]
Not sure about you, but i just checked, and the paladin librams are there.

**Comment by Raulfin** [comment]
Just checked, the Librams are now visable but not the others. Checked on pld and dru so it's not class based hiding.

**Comment by Raulfin** [comment]
Not sure why this was closed, 8 of the 11 items are still not on vendors as they should be.
@Royalwax

**Comment by Royalwax** [comment]
I am looking at them at the moment..... It is on your end
