### ISSUE TITLE
Ebonweave

### ISSUE THREAD

**Issue by Ebonweave** [SallyWhitemane/Mograine#1267]
Can't create Ebonweave. Have disabled all Addons and deleted the cache folder, doesn't help. Always get the message " You have to be in the Obsidian Shrine". I tried it at the Maul as well as inside Obsidian Shrine.

Tailoring - Ebonweave

On the original Blizzard server you just had to get to the entrance of the shrine and could produce the ebonweave. 
Btw, Spelltread worked, with all Addons on.

Char Name is Rada, lvl 80 Warlock

**Comment by Royalwax** [comment]
Outside of the maul entrance.
