### ISSUE TITLE
Incorrect Tooltip - Life Tap (Rank 1)

### ISSUE THREAD

**Issue by Zirda** [SallyWhitemane/Mograine#127]
**Description:**
Tooltip for Life Tap on my level 7 warlock shows the wrong values. 

https://imgur.com/a/47KEA3C

It says convert 75 health into 27 mana 

**How to reproduce:**

**How it should work:**

It converts 28 health into 28 mana with 0 spellpower. The tooltip should represent those values.

**Comment by Zirda** [comment]
There is also an issue with the tooltip for Blood Fury;
https://imgur.com/a/6TA6ljh

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
