### ISSUE TITLE
Bloodworms are limited to 4 at max

### ISSUE THREAD

**Issue by danniellos94** [SallyWhitemane/Mograine#1271]
**Description:**

I'm hitting the boss Random Number Generator gives me 4 Bloodworms if Random Number Generator was so kind as to give me another set of Bloodworms they are supposed to spawn while the previous set is still active. As they are right now, Bloodworms only spawn as one set at a time which is incorrect.

Bloodworms are limited to 4 at max.

**How to reproduce:**
https://www.youtube.com/watch?v=_n18zWh7KtI several moments showing far more then 4 worms active on 1 DK.

https://www.youtube.com/watch?v=fx0kVZHiBJY another one (from beta though, unlike the above one)

http://wowwiki.wikia.com/wiki/Bloodworms Note the patch changes only having one change in 3.1.0 where they increased the healing worms do. Also note the lack of an internal CD."

from retail 2016 comment https://eu.battle.net/forums/en/wow/topic/17613703133
"they could change it to proc on all crits but limit blood worms to max of 2 or 3 at the same time."
So far they have not limit till 2016 year on retail.

How to reproduce:
smash the dummy with the talent 3/3 bloodworms and see that it's impossible to have more than 4 https://www.youtube.com/watch?v=_n18zWh7KtI several moments showing far more then 4 worms active on 1 DK.

https://www.youtube.com/watch?v=fx0kVZHiBJY another one (from beta though, unlike the above one)

http://wowwiki.wikia.com/wiki/Bloodworms Note the patch changes only having one change in 3.1.0 where they increased the healing worms do. Also note the lack of an internal CD."

from retail 2016 comment https://eu.battle.net/forums/en/wow/topic/17613703133
"they could change it to proc on all crits but limit blood worms to max of 2 or 3 at the same time."
So far they have not limit till 2016 year on retail.

How to reproduce:
smash the dummy with the talent 3/3 bloodworms and see that it's impossible to have more than 4 

**How it should work:**
They shouldn't be limited to 4 at one time.

**Comment by Raulfin** [comment]
the video you linked is 5 dks, not 1. It's super low quality, i couldn't see a single bloodworm the whole time.

https://www.youtube.com/watch?v=fx0kVZHiBJY&ab_channel=Aeditha
the video is posted 10/8/08, and says it's from beta.
in this video you can see 2 worms being spawned 2 times for 4 worms at the same time. The first set of 2 spawn at 0:25, the second at 0:32, the first set pops at 0:51 and the second set pops at 0:55.
5 worms then spawn at 1:07. 5 more worms spawn at 1:16 for 10 total active worms. 4 or 5 more spawn at 1:24 for 14-15 active worms. 2 spawn at 1:31, some have died and there are now 7 active. 3 more spawn at 1:44 and it goes on. the most worms i saw active in the vid was 17 for about 2-3sec.

The whole time the worms activly seek to get behind the target to avoid being parried/blocked.

https://www.youtube.com/watch?v=M-y_BulIY54&ab_channel=Kreator
the video is posted 18/9/14, says it's from retail 335. (the dk has 48k HP, the targets in the background are lvl 80 so seems to be right for era)
training dummy from 2:37-6:57. never has more than 4 worms active.

https://www.youtube.com/watch?v=-_8e-VJfAdk&ab_channel=mbXtreme
the video is posted 20/8/10 during 335 and is oddly high quality for the era
training dummy from 0:30-2:00. never has more than 4 worms active.

**Comment by danniellos94** [comment]
Yea I've checked few logs bloodworms always dies before new summon so it's truth. This must be undocumented change by blizzard.
