### ISSUE TITLE
[Doom Lord Kazzak] less gold

### ISSUE THREAD

**Issue by palkovi** [SallyWhitemane/Mograine#1273]
Doom Lord Kazzak only gives 6 gold when killed.

 From server I came it gave 500 gold
In wowhead it says 403 gold
Other databases says 501 gold

**Comment by Shragenator** [comment]
This should definitely be around 500g.  I kill Doomwalker regularly (a different BC lvl 70 world boss) and it drops just shy of 500g

**Comment by palkovi** [comment]
BUGFIX???
