### ISSUE TITLE
NPC Boar charge bonus damage not applied. 

### ISSUE THREAD

**Issue by Zirda** [SallyWhitemane/Mograine#128]
**Description:**
NPC: https://wotlkdb.com/?npc=3099
Print screens: https://imgur.com/a/96WjmDT

These mobs apply a self buff charge bonus that increases damage on next attack by 13 according to toolip. No damage is added. The attack is still within the normal 8-11 damage range against low armor character. 

**How to reproduce:**
Tag one of the boars at range south of Razor hill. Compare damage taken to charge attack and normal

**How it should work:**
Bonus damage should be applied on the attack

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
