### ISSUE TITLE
Berserking currently has no inner cooldown

### ISSUE THREAD

**Issue by Ikatsukun** [SallyWhitemane/Mograine#1282]
**Description:**
When testing out my raid dunny dps I came upon many instances on my arms warrior where I would have my berserking enchant buff would procc while currently already procced, prolonging the effect with a fresh 15 second buff. 
Also procced just a few seconds after the buff had dissipated. 

**How to reproduce:**
I used my arms warrior, with a 56/15/0 spec. 
Attacking raid target dummy in orgrimmar. 
Using my two-handed sword, stormruned edge, buffed with berserking. 
Did about with a normal single target rotation using rend, overpower, mortal strike, executes and sunder armor. 

**How it should work:**
There should be atleast a 45 second inner cooldown. 
I know this subject has been invalidated before when tried on a rogue, but the fact is its very much present on my warrior. For what reason I don't know, perhaps it's the class, perhaps it's weapon archetype, I have no clue. 
But it should not be proccing as often and regularly as it is on my warrior. 
As an arms warrior, I feel that if this applies to fury warriors or other classes they get a heck of an unfair advantage, and that could explain why fury warriors are a bit overtuned early patches on this server compared to how it was back on retail.

**Comment by MissZay** [comment]
berserking never had an internal cooldown, also what do you mean fury warriors are overturned? they're at the bottom of damage meter on any single target encounter

**Comment by Ikatsukun** [comment]
> berserking never had an internal cooldown, also what do you mean fury warriors are overturned? they're at the bottom of damage meter on any single target encounter

From reading the old comments on wowhead about berserking from both 3.0.3 and 3.3.5 there are alot of people who have tested and confirmed there is an internal cooldown on berserking. I was wrong in that it would be 45 seconds though, there they are stating it's actually 60 seconds.
Here is a link: https://www.wowhead.com/spell=59621/berserking#comments

And about fury warriors being overturned, I. Am not by any means saying they are topping the damage meters in our current patch. I am simply stating that they are stronger than what they have been way back when on retail as I remember it, and to back that up there's plenty of theorizing and testing aswell as immensely in depth spreadsheets on the subjects of arms and fury warrior dps on the archived elitistjerks forums.

Also, if you just think of it. If berserking should indeed have an internal cooldown but does not, seeing as how strong the 400 ap buff is, especially with berserker stance and ap increasing raid buffs, a fury warrior being able to have two additive buffs up with flurry to help keep them both up for longer periods of time, a fury warrior would benefit at great big deal more than arms, however with each content release it should level out a bit more, but not entirely.

**Comment by MissZay** [comment]
maybe it got changed when cataclysm came out or during the prepatch but there are plenty of comments that explain how the proc works and the ppm system, all the procs that use ppm don't have an internal cooldown, unlike for example the greatness card which is a flat 30% chance with 45sec icd
I'm currently playing enh sham with 700 haste and sometimes I start a fight with BL and speed pot and don't get a single zerk proc in the first 10secs or so, my zerk uptime is usually between 30-45% but sometimes it's as low as 20% and sometimes up to 60% or more it's just a low % and thus it can be pretty inconsistent, also on the buff uptime rogues attack around 2 to 3 times faster than a fury war and they have pretty much the same uptime
