### ISSUE TITLE
Feral things

### ISSUE THREAD

**Issue by styxel** [SallyWhitemane/Mograine#129]
**Description:**

1.**Rake initial hit doesnt ignore all armor** 
rake dot damage works correctly and ignores all armor can be tested with a arp trinket getting a proc with arp doesnt do anything for the bleed but it increase the damage on the initial hit. Also tiger's fury doesnt increase the damage the of the initial hit i actually dont remember if it should :).

2.**Berserk should remove tiger´s fury from druid when activated, now it doesnt**

3.**gift of the wild should roll omen of the clarity 6% x amount of people u buffed it with.**

4.**feral tier 8 2 set bonus should be 2% proc chance not sure if u changed it to 6%?**

5.**Leader of the pack heals work incorrectly**

6.**Stormchops consumable** had to test this xd, it doesnt proc ooc and thats correct imo, but it should have a 8sec gcd with the proc damage of it and it should only hit max 2 targets currently has no icd.

**How it should work:**
1.Rake has 2 parts the initial hit and the bleed of it, they both **should do damage as u had 100% arp** with them since they ignore all armor. Currently only the bleed damage works correctly the initial hit doesnt
https://github.com/SunwellTracker/issues/issues/2295 same issue was on sunwells server

2.**Berserk should remove tiger's fury from the druid when activated**
[18:42:35.148] Oranoss gains Tiger's Fury from Oranoss
[18:42:35.148] Oranoss casts Tiger's Fury
[18:42:35.465] Oranoss gains Rage of the Fallen (8) from Oranoss
[18:42:35.465] Reî Judgement of Light Oranoss +0 (O: 1199)
[18:42:35.481] Oranoss gains 60 energy from Oranoss's King of the Jungle
[18:42:35.498] Oranoss hits Rotface 1992
[18:42:35.591] Oranoss's Tiger's Fury fades from Oranoss
[18:42:35.591] Oranoss gains Berserk from Oranoss
[18:42:35.591] Oranoss casts Berserk
**retail logs**

3.**feral tier 8 2set bonus should be 2% proc chance not sure if u made that fix didnt test.**
https://www.wowhead.com/spell=64752/item-druid-t8-feral-2p-bonus

4.**Gift of the wild should roll omen of the clarity 6% x amount of people buffed it with it.**
" The 2T10 is the only bonus that will change how you play. Since Gift of the Wild can be used to force a Clearcasting proc, you should make a habit of doing this anytime you have to move, so that the next few spells you cast after you stop moving will have the buff. If you're moving for a few seconds and are going to cast both GotW and DoT's, cast GotW first, as the buff will affect the subsequent DoT's for their entire duration. Do not cast GotW while standing still."
" Gift of the Wild, if cast on 25 people, has a very high chance of proccing this."
https://web.archive.org/web/20100731043147/http://elitistjerks.com/f47/t66856-druid_balance_pve_updated_3_3_5_a/
https://www.wowhead.com/forums&topic=55989

**5. leader of the pack**
Leader of the pack works incorrectly just like it was working on sunwell. 
On retail the aura was a personal buff for every player but on whitemane its basically consired a cast made by the druid making it a "heal" this was causing it to proc alot of omen of clarity it should only proc it when u self heal with it. Actually not sure if lotp heals are proccing ooc here.

its goin to look like this when its broken https://imgur.com/a/rgLtiAz
this is how it should look like (this is from retail method logs) https://imgur.com/a/MouHfY5
if u look at the logs here u can see that every player has their own lotp healing done 
http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/sum/healingDone/?enc=kills

6.**Stormchops**
https://www.wowhead.com/item=33866/stormchops#comments

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by styxel** [comment]
@SallyWhitemane just wanted to say that the lotp self healing does proc ooc atm so its working correctly just the other part needs to be fixed where it should be a personal heal for everyone otherwise it will be proccing ooc like crazy since ull be healing the whole raid with "your heals".
