### ISSUE TITLE
DK Runetap glyph and talent bugged, not healing the percent it should/ it says

### ISSUE THREAD

**Issue by palkovi** [SallyWhitemane/Mograine#1290]
DK Runetap glyph and talent bugged, not healing the percent it should/ it says

**Comment by danniellos94** [comment]
I don't have the glyph atm but rune tap is healing 20% of my hp as it should without.
Its 10% base and 100% more with improved rune tap - 20%.
When glyphed it should be 22% and should heal everyone in a party for their 10 % max hp I bet it works just correct.
