### ISSUE TITLE
[Naxxramass] Encounter still in progress bug/combat bug

### ISSUE THREAD

**Issue by ghuser44** [SallyWhitemane/Mograine#130]
**Description:**
If you wipe on a boss and you release, you can't zone back in the instance. It says " Encounter still in progress " even though everyone is outside. The bosses stay at the **current HP** that they were at, when we wipe, they keep the **current debuffs** on them, as well, and they go back to their initial patrol path **without resetting their HP and debuffs**.

Also, When you kill a boss, you get stuck in combat, afterwards. Example: killing **Grobbulus**.

**How to reproduce:**
- Zone in Naxx, engage a boss and die. Release and try to zone back in again.
- Kill a boss (ex: Grobbulus) and check combat bug afterwards. The bug might be associated with pets keeping the bosses in combat indefinitely, even after they die or they're dismissed (according to a GM, in game). It might be something completely different too, though.

**How it should work:**
- After a wipe, the boss should **exit combat, clear himself from every player/pet debuffs and reset his HP to full**.
- Anyone who releases after a wipe should be able to zone back in with no problems, **if no one is in combat with a boss**.
- Anyone who **DI** themselves (**_Divine Intervention_**) should exit combat and not bug the boss, so he can resurrect players later.
- After a boss is dead, the combat state should reset to **Out of Combat** for everyone in the raid.
- If a hunter pulls a boss, and uses feign death, the boss should reset as mentioned above (_after a wipe reset_).

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
