### ISSUE TITLE
Mage T9 gear swap doesn't keep the bonus crit 

### ISSUE THREAD

**Issue by FakerAmine** [SallyWhitemane/Mograine#131]
**Description:**
Swapping gear after using molten armor(while equipping 2 T9 set) doesn't keep the 15% crit bonus from spirit.

**How to reproduce:**
Swapping gear after using molten armor (while equipping 2 T9) set should keep the 15% crit bonus from spirit.

**How it should work:**
The bonus was kept on retail and allowed mages to play both crit/haste and crit/spirit optimization and was NEVER declared or announced as a bug.
https://www.mmo-champion.com/threads/707670-Mage-T9-2p
https://wowguidepvpandpve.blogspot.com/2014/10/mage-guide-wotlk-guide-pve.html?view=classic

**Comment by Synful-Syn** [comment]
So... I got it "fixed" with that bug report here https://github.com/SallyWhitemane/Mograine/issues/10
After reading your proofs, I've just learnt that it was a retail bug, but do we really want to reproduce retail bugs?
It does sounds very annoying and very unfun to switch to the other spec, wear the T9, regain enough mana to cast Molten Armor, switch back to the main spec then regain mana once again for a fight.

**Comment by way456** [comment]
> After reading your proofs, I've just learnt that it was a retail bug, but do we really want to reproduce retail bugs?

How is that considered a bug? Even it wasn't intended to work this way , they still let it go through the whole expansion.
Still, why not play the classes as close as it was to blizzlike?

Also you dont switch spec for a glyph , considering you are already playing fire in t9, therefore using that glyph already

**Comment by FakerAmine** [comment]
You don't need to switch spec, just a maccro to equip 2 T9 set+cast molten armor, and a maccro to equip back your current gear, which takes less then 1sec to execute! let me explain more,it only keeps the bonus crit of 0.15*ACTUAL spirit not at the moment u cast,it means it's pointless to equip a full spirit gear use it and hope u get 4 or 5%, it only keep the % bonus of the actual spirit with items u're wearing that's what made spirit/crit mage an option to play and it was fun btw ! Tbh even if it was a bug on retail,blizzard kept it and didn't change it up until the rework of molten armor with cataclysm arrival !Besides, even when considering its a bug, it doesn't affect or hurt the game or gameplay in anyway, it was juste a way for mages to play with different optimizations, haste/crit or spirit/crit and for the crit gained, when u're bis or almost,u have not that much spirit, u will gain like 2 to 3% at most(if u're playing spirit/crit) so it's almost nothing, but still, endgame is a about those tiny numbers diff and i think it's important, alongside with several friends, want to play and relive those moments we had back then, we just want a server as blizzlike as possible, and i'm sure that's what the developers are trying to achieve to !

**Comment by SallyWhitemane** [comment]
Last corrections to mage T9 will be removed, it'll work like on retail. Thanks for contributing.
