### ISSUE TITLE
 Idol of Mutilation stacking buffs

### ISSUE THREAD

**Issue by dudeedu** [SallyWhitemane/Mograine#1318]
**Description:**  Idol of Mutilation (item=47668) gives 2 bufs Evation for a bear & Agile for cat. They stacks

**How to reproduce:** shift to cat make mangle or shred, then reshift to bear & make lacerate or swipe = can have both buffs at same time.

**How it should work:** should not have 2 buffs from one item in same time.

**Comment by gandalkk** [comment]
Working as intented imo unless theres some proof.
