### ISSUE TITLE
Paladin gains skill Beacon of Light at level 2

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#133]
**Description:**
Upon reaching level 2, the ability Beacon of Light is gained (several times!)
It can even be cast with "/cast Beacon of Light", healing the player for 1hp for some reason.

Beacon of Light is the 51-point talent in the Holy tree and should not be gained at level 2.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
