### ISSUE TITLE
Light's Vengeance

### ISSUE THREAD

**Issue by MadeinNoxus** [SallyWhitemane/Mograine#1333]
**Description:**
I try to take the Light's Vengeance but doesn't give me the item.
https://www.wowhead.com/item=49869/lights-vengeance
**How to reproduce:**
Try to take the Light's Vengeance.

**How it should work:**
You will take the Light's Vengeance and go to icc for one of the quest for shadowmourne.

**Comment by danniellos94** [comment]
Are you sure you are not in raid? I get the item without a problem.
