### ISSUE TITLE
[Quest] - Seasoned Wolf Kabobs drop chance

### ISSUE THREAD

**Issue by Knapec** [SallyWhitemane/Mograine#134]
**Description:** When you kill wolfs in duskwood they should drop lean "Lean Wolf Flank" With approx 40% chance on blizzlike, the drop rate is on blizzlike level. I am now checking the fix you made to all quest items and it seems to work well so far, but I think it didn't work for this quest because "Lean Wolf Flank" is not a quest item, it also drops regularly. 

**How to reproduce:** Kill the wolves in duskwood.

**How it should work:**

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
