### ISSUE TITLE
Lich King 25m Heroic has incorrect health for Blizzlike tuning

### ISSUE THREAD

**Issue by Akmandorr** [SallyWhitemane/Mograine#1349]
**Description:**
LK 25m HC has too much hp

**How to reproduce:**
Go to the fight on 25m HC and check his hp

**How it should work:**
He should have 103million HP at Blizzlike values
https://youtu.be/_QcuB8zCpu4?t=64 (Paragon World First of 25m HC in Retail Wrath the boss is targeted at the timestamp and you can see his full hp in the top left)

**Comment by mrnuggets** [comment]
lmao, you're not wiping due to health values. It's easy, just kill him as is.
