### ISSUE TITLE
[Paladin] Retribution talent "Fanaticism" reduces threat while Righteous Fury is active

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#135]
The talent "Fanaticism" currently reduces threat generated even while Righteous Fury is active. It should only reduce threat while Righteous Fury is not active.

With 3 points in Fanaticism and Righteous Fury active, melee attacks currently deal 1 threat per damage versus the expected 1.43 threat due to Righteous Fury's implicit tank-stance threat multiplier (1.43 * 0.7 ~= 1).

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
