### ISSUE TITLE
shadowstep broken

### ISSUE THREAD

**Issue by Peskyy1** [SallyWhitemane/Mograine#1350]
**Description:**
shadowstep doesnt work when im in range

**How to reproduce:**
fix it

**How it should work:**
shadow step works

https://youtu.be/PohorrY4LM8

here is link to video of it

**Comment by SallyWhitemane** [comment]
This is wotlk bugtracker, go here (https://github.com/SallyWhitemane/Herod/issues) for cataclysm.
