### ISSUE TITLE
feral druid berserk 

### ISSUE THREAD

**Issue by styxel** [SallyWhitemane/Mograine#136]
**Description:**
Seems to reduce energy cost of shred too much, tooltip says 21energy but in reality it uses only 12energy

**How to reproduce:**
Use berserk and use shred, tooltips read correct but uses less energy apparently
**NOTE**
it might be issue with talent called shredding attacks 
shred is normally 60energy, with the talent its 42 -> berserk = 21energy
what it propably does is 60 -> berserk = 30 - 18 = 12 

https://github.com/SunwellTracker/issues/issues/2297 same issue was on sunwell.

ps. really good job on fixing omen of clarity :) seems to work perfectly for now!

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
