### ISSUE TITLE
Quest - Howling Fjord - Let Them Eat Crow (11227)

### ISSUE THREAD

**Issue by kieran1188** [SallyWhitemane/Mograine#139]
**Description:**

While doing the quest, you summon the Plaguehound using the Plaguehound Cage (item=33221) and he just appears and stands still, he doesnt follow you. you are allowed to use the meat to feed him and complete the quest but its not correct.

![WoWScrnShot_121920_204314](https://user-images.githubusercontent.com/38033595/102699209-f459e300-423a-11eb-8db0-9e15be8e6e4b.jpg)
![WoWScrnShot_121920_204315](https://user-images.githubusercontent.com/38033595/102699213-fa4fc400-423a-11eb-96aa-38ee36c9611d.jpg)
![WoWScrnShot_121920_204317](https://user-images.githubusercontent.com/38033595/102699220-fe7be180-423a-11eb-9431-27a34b37ff23.jpg)

**How to reproduce:**

Accept the quest and use the cage.

**How it should work:**

https://youtu.be/LFQs5pwe6xY

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
