### ISSUE TITLE
[Ulduar Hodir] 10m Campfire not droppingg

### ISSUE THREAD

**Issue by guardian40** [SallyWhitemane/Mograine#140]
**Description:**
Amira Blazeweaver is not casting https://www.wowhead.com/spell=62823/conjure-toasty-fire
**How to reproduce:**
Pull Hodir, free Amira and watch

**How it should work:**
Should be dropped at least once before each flash freeze is cast. 

Linking 2 twitch highlights showing the issue, I looked around and I didn't see if this was reported yet, but I apologize if it already was and I missed it. 

https://www.twitch.tv/videos/843311569 Evidence 1
https://www.twitch.tv/videos/843311568 Evidence 2

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
Also i've reworked AI for helpers, they should be more responsive to whats happening around them.
