### ISSUE TITLE
Icecrown citadell buff

### ISSUE THREAD

**Issue by FakerAmine** [SallyWhitemane/Mograine#142]
**Description:**
There are 2 buffs in icc stacking multiplicatively, in other words , the first buff gives 15% bonus on damage/healing and health so u get 1.15 coef, and the second one gives you 10% on top of the 1.15 u already have, which results in 1.15*1.1=1.265 which is odd !
**How to reproduce:**
Try multiple spells (without trinkets or damage modifiers) on icc trash mobs, take off the buff & try same spells, and finally, do the math.
**How it should work:**
Originally the buff was 5%, then they increased it progressively to 30% so most people can enjoy the end game content.
(The choice to increase it progressively or start directly with the 30%(which i would like to have tbh) is up to the devs/board, if the server is gonna be open for wotlk content for long, then the first option seems better as players will have enough time to reach the 30% point, but if you intend to reset the server or move to another expansion then the 30% on start would be the best choice imo) 
https://wow.gamepedia.com/Strength_of_Wrynn
https://wow.gamepedia.com/Hellscream%27s_Warsong

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
