### ISSUE TITLE
warlock life tap

### ISSUE THREAD

**Issue by fenkov89** [SallyWhitemane/Mograine#143]
warlocks life tap is buged, when u life tap at low hp u are getting killed and getting insta rez after this

you should be able to kill ysefl with lifetap

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues?q=is%3Aissue+is%3Aclosed

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues/138
