### ISSUE TITLE
[Druid] Lifebloom bloom consumes clearcast

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#144]
**Description:**
When Lifebloom blooms it will consume Clearcasting from Omen of Clarity if you have it active

**How to reproduce:**
Refresh Lifebloom until you get clearcast, then let Lifebloom bloom and watch clearcast get removed

**How it should work:**
Lifebloom bloom effect returns mana to the caster, this should not consume Clearcast

**Comment by styxel** [comment]
works fine for me in feral spec or maybe they fixd it already

**Comment by SallyWhitemane** [comment]
Works fine.
