### ISSUE TITLE
Evading monsters don't reset health

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#145]
Monsters do not currently regain health when they finish evading, they just return to patrolling/wandering with whatever health they had when they started evading.
Noticed this on monsters in the open world, have not checked if bosses are similarly bugged.

**Comment by tdymel** [comment]
Monsters in polymorph also dont.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
