### ISSUE TITLE
Prospecting loot tables are bugged

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#146]
Almost all Prospecting loot tables are completely broken. For example, prospecting Fel Iron Ore yields no Uncommon gems other than Golden Draenite and Azure Moonstone (not a single Uncommon gem other than those two in over 200 Prospecting casts).

A look at all Prospecting tables and/or mechanics is clearly needed, but for reference these tables were clearly bugged in my testing:
Iron Ore
Mithril Ore
Thorium Ore
Fel Iron Ore
Cobalt Ore
Saronite Ore
Titanium Ore
and maybe Copper ore

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
