### ISSUE TITLE
Some Milling loot tables are inaccurate

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#147]
Some Herbs give, on average, three times as much of their Uncommon-quality Pigment when milled, compared to the expected yields as seen in various WOTLK databases:

Mageroyal       gives 1.5 verdant  per mill (3x)
Swiftthistle    gives 1.5 verdant  per mill (3x)
Briarthorn      gives 1.5 verdant  per mill (3x)
Grave Moss      gives 1.5 burnt    per mill (3x)
Wild Steelbloom gives 1.5 burnt    per mill (3x)
Fadeleaf        gives 1.5 indigo   per mill (3x)
Goldthorn       gives 1.5 indigo   per mill (3x)
Firebloom       gives 1.5 ruby     per mill (3x)
Purple Lotus    gives 1.5 ruby     per mill (3x)
Arthas' Tears   gives 1.5 ruby     per mill (3x)
Sungrass        gives 1.5 ruby     per mill (3x)
Golden Sansam   gives 1.5 sapphire per mill (3x)
Dreamfoil       gives 1.5 sapphire per mill (3x)
Terocone        gives 1.5 ebon     per mill (3x)
Dreaming Glory  gives 1.5 ebon     per mill (3x)
Felweed         gives 1.5 ebon     per mill (3x)
Ragveil         gives 1.5 ebon     per mill (3x)
Deadnettle      gives 1.5 icy      per mill (3x)
Talandra's Rose gives 1.5 icy      per mill (3x)
Tiger Lily      gives 1.5 icy      per mill (3x)
Goldclover      gives 1.5 icy      per mill (3x)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
