### ISSUE TITLE
Prospecting sometimes fails, consuming Ore and producing no loot

### ISSUE THREAD

**Issue by Beefcaqe** [SallyWhitemane/Mograine#148]
Rarely (1 in 50 to 1 in 100 ballpark estimate), Prospecting ore consumes 5 ore as expected but does not give any loot and does not open a loot window.
I have confirmed that the cast does not simply fail, and the ore IS consumed in the process.

Unfortunately I do not have a reliable way to reproduce this bug other than prospecting lots of ore.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
