### ISSUE TITLE
[Quest] Lazy peon

### ISSUE THREAD

**Issue by Matija5** [SallyWhitemane/Mograine#150]
**Description:**
Peons are waking up by themselfs

**How to reproduce:**
make and orc/troll take quest, and just roam to find them. Most of them are going to be awake even though noone else is leveling. You can also just watch at one of them and at certain point they are gonna wake up.

**How it should work:**
They should only be woken up when u use quest item on them

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
