### ISSUE TITLE
[Mage] Combustion Buff not removed when right clicked off from Buffs tab.

### ISSUE THREAD

**Issue by HasieEST** [SallyWhitemane/Mograine#151]
**Description:**
Currently unable to put the spell on CD after you have cast the spell via right-clicking it off from buffs row.

**How to reproduce:**
1) Cast Combustion
2) Right-click it off
3) Check if it started cooldown, if not proceed to cast a spell and then repeat step 2
4) Repeat step 3 until on cd.

**How it should work:**
1) Cast Combustion
2) Right-click it off
3) Combustion goes on CD

https://user-images.githubusercontent.com/25981761/102900387-df689400-4474-11eb-8532-27a4287c93d4.mp4

**Comment by HasieEST** [comment]
Adding a video without addons.
https://user-images.githubusercontent.com/25981761/102901113-e217b900-4475-11eb-9699-2f391b4c0286.mp4

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
