### ISSUE TITLE
[Hunter] Talent : Lock and Load

### ISSUE THREAD

**Issue by Notkym** [SallyWhitemane/Mograine#152]
Talent name: Lock and Load (survival) ID : 56344
You have a 100% chance when you trap a target with Freezing Trap, Freezing Arrow, or Frost Trap and a 6% chance when you deal periodic damage with your Immolation Trap, Explosive Trap or Black Arrow to cause your next 2 Arcane shot or Explosive shot spells to trigger no cooldown, cost no mana and consume no ammo.
This effect has a 22 sec cooldown.

Yesterday when my frost trap trigger on dungeon bosses the Lock and Load didn't proc, when the talent says frost trap have 100% chance to proc the Lock and load. However this talent work on dummies at orgrimmar.

This talent should proc when your frost trap trigger on the boss.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by Soufly** [comment]
Wrong,the bosses are immune to snare effects... the frost trap should proc,but LnL effect not.
3.2.0 (04-Aug-2009): Now has a 22 second cooldown. The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used. The tooltip for this talent has been updated to indicate that it also works with Explosive Trap. 
https://wowwiki.fandom.com/wiki/Lock_and_Load

**Comment by Soufly** [comment]
Wrong,bosses are immune to snare effects... the frost trap should trigger,but the LnL effect not.
3.2.0 (04-Aug-2009): Now has a 22 second cooldown. The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used. The tooltip for this talent has been updated to indicate that it also works with Explosive Trap. 
https://wowwiki.fandom.com/wiki/Lock_and_Load
