### ISSUE TITLE
Stranglethorn Fever bug

### ISSUE THREAD

**Issue by kindauncanny** [SallyWhitemane/Mograine#154]
**Description:**
Stranglethorn Fever quest requires 10 Gorilla Fangs for the stage where you have to summon Mokk the Savage.

**How to reproduce:**
It's in the quest itself currently.

**How it should work:**
In WotLK the quest should only require 1 Gorilla Fang.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
