### ISSUE TITLE
Warriors Rage generation scaling with caster mobs

### ISSUE THREAD

**Issue by kindauncanny** [SallyWhitemane/Mograine#155]
**Description:**
Warriors do not generate enough Rage when hit by caster mobs, so Rage starvation is a thing on lower levels.

**How to reproduce:**
Try pulling as an appropriate level warrior in any Scarlet Monastery instance. 

**How it should work:**
It should generate way more Rage than it does currently.
I'm not sure about the exact scaling factor, but it should be multiple of what it is now.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
