### ISSUE TITLE
Fire Elemental Totem summoned after Greater Fire Elemental

### ISSUE THREAD

**Issue by Gem-i** [SallyWhitemane/Mograine#156]
**Description:**
In combat log firstly an elemental is summoned, then secondly a totem is summoned. Similar thing happens to an Earthbind totem with talent Storm, Earth and Fire which enables Earthgrab spell, and starts casting it before a totem is summoned. This problem is very probably causing Fire Elemental to deal damage only on its own, not as shaman's pet.

**How to reproduce:**
Cast Fire elemental totem, then check the order of summoning totem and summoning elemental in combat log.

**How it should work:**
A totem should be summoned before a Fire Elemental.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
