### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by Miserymonk** [SallyWhitemane/Mograine#157]
**Description:**
Below mentioned quest is not shown.
https://classic.wowhead.com/quest=823/report-to-orgnil

**How to reproduce:**
Master Gardin does not give the required quest to start "Dark Storms"

**How it should work:**
Master Gardin should give the quest "Report to Orgnil" as preQuest to "Dark Storms"

**Comment by SallyWhitemane** [comment]
Works fine, you need to have Report to Sen'jin Village quest completed before Report to Orgnil can show up.
