### ISSUE TITLE
[Quest] Super Sticky - low drop rate

### ISSUE THREAD

**Issue by Knapec** [SallyWhitemane/Mograine#158]
**Description:** Quest in Ungoro crater, the drop rate is below blizzlike level, the drop rate should be 42%. Other quests drop rates are still not 3x. I was sending you a message about this but I don't know if you received it.

**How to reproduce:** Tak Super Sticky quest from Tanaris and kill Tar mobs in Ungoro Crater.

**How it should work:** I believe the drop rate should be 100% (3x 42%, Or at least 42%).

**Comment by SallyWhitemane** [comment]
There was a typo in code, it should work fine for all quest items now.
Issue will be fixed with next update, thanks for contribution!
