### ISSUE TITLE
Bugged mobs in belf starting zone

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#159]
**Description:**
1.Angryshade bugged in terrain
2.Melee mobs auto attacking from range

**How to reproduce:**
https://youtu.be/3RxxrEnqxGI

**How it should work:**
https://www.youtube.com/watch?v=dgupKoO6hRA&ab_channel=GitGudGuides

**Comment by mangodextra** [comment]
"quality"

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
