### ISSUE TITLE
Warlock lvl 40 fast mount

### ISSUE THREAD

**Issue by fenkov89** [SallyWhitemane/Mograine#160]
Warlock is not getting instant learn lvl 40 fast mount ability plus riding like he is getting it on lvl 20.
I think it should work the same like its working for paly. Paly on lvl 40 is getting insta learn fast mount plus riding ability same as he is getting it on lvl 20.

I think it should work the same for both classes. But maybe im wrong

**Comment by Fixetza** [comment]
Both pallys and warlocks need to learn riding on level 40 and only after that can they get the level 40 mounts. So it's working as intended.

**Comment by fenkov89** [comment]
if u fixed it ok but when i was testing pally was geting insta mount on 40.

**Comment by SallyWhitemane** [comment]
The auto-learn feature doesn't teach mounts anymore, and Apprentice Riding (level 20) will be learned automatically for free as one of the Autolearn features. You will still have to purchase the mount for 85 silver or learn it at your class trainer
