### ISSUE TITLE
Druid Innervate

### ISSUE THREAD

**Issue by WubWub24** [SallyWhitemane/Mograine#161]
**Description:**
Innervate is giving less then 225% mana pool

**How to reproduce:**
Cast Innervate on a lvl 80 druid no talents no  items no
 glyphs
**How it should work:**

**Comment by styxel** [comment]
works fine? regenerates exactly 7866 mana over 10sec like it should.

**Comment by WubWub24** [comment]
Ye it was only a bugged character as stats were wrong and spells not working as intended 
![WoWScrnShot_122420_204718](https://user-images.githubusercontent.com/73794095/103105688-f7d4dc00-4637-11eb-86f2-316129d2b76b.jpg)
![WoWScrnShot_122420_204146](https://user-images.githubusercontent.com/73794095/103105689-f9060900-4637-11eb-87a4-1725cb1869e6.jpg)
