### ISSUE TITLE
Warlock - Voidwalker Spell not autolearned

### ISSUE THREAD

**Issue by Gander21** [SallyWhitemane/Mograine#165]
**Description:**

(Undead) warlock has not autolearned Voidwalker spell at level 10, ability is locked behind a class quest.

**How to reproduce:**

Level an udead warlock to lvl 10.
**How it should work:**
All spells should be autolearned upon reaching the level required, including spells learned via quests

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
