### ISSUE TITLE
[Death Knight] Runes feel a bit odd.

### ISSUE THREAD

**Issue by AndreiGameDev** [SallyWhitemane/Mograine#166]
**Description:**
Sometimes Runes have an cooldown and can't be used immediately.

**How to reproduce:**
Use every blood rune and stay in Unholy Presence or Frost Presence ,then cast Blood Tap and try to use Blood Stance

**How it should work:**
Runes should be detected immediately as a rune that can be used.

https://user-images.githubusercontent.com/49598916/103466510-c1851400-4d3d-11eb-9654-3a55fc840ea6.mp4
https://www.youtube.com/watch?v=lVu7C6CgQ4A&feature=youtu.be
https://youtu.be/aGGnSEbx3_g

**Comment by CraftyGam** [comment]
https://youtu.be/aGGnSEbx3_g

**Comment by Rugsz** [comment]
Yeah I tried messing around with this today and it makes playing DK so clunky that it's almost unplayable. This **needs** to be fixed before launch. It heavily effects FDK regular rotation & hinders Unholy & Blood openers severely.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
