### ISSUE TITLE
[Quest] [A Little Slime Goes a Long Way]

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#167]
**Description:**
Using the Empty Sample Jar on the Oozes in Un'Goro / Felwood doesn't despawn the corpse after use, so players can just use up all 10 of the items to get the filled version.

**How to reproduce:**
Accept quest A Little Slime Goes a Long Way (pt. 1 or 2)
Kill the slime
Use the jar on the slimes corpse
The player can keep using the jar and the corpse does not despawn
**How it should work:**
Slime corpses should despawn after the Empty Sample Jar is used on their corpse.
https://youtu.be/MoxXqZKI2DY?t=602 (from classic but is accurate)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
