### ISSUE TITLE
[Quest] [Azuremyst Isle Totems]

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#168]
**Description:**
All of the totem quests (Learning the Language -> The Prophecy of Akida) are bugged and do not do their RP events and give the player the buff after turning in each quest. This is very important for speed leveling and immersion.

**How to reproduce:**
Turn in each quest, and watch as the RP and buffs are not given.

**How it should work:**
See this Wowhead comment from patch 3.2.2
https://www.wowhead.com/quest=9538/learning-the-language#comments:id=859994

**Comment by alexspew** [comment]
After testing, it seems you need to follow the npc and not rush to the place. They grant the buffs correctly, if there's still issues with this quest, please let me know in discord (alexs) thanks!
