### ISSUE TITLE
[Quest] [Jungle Secrets]

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#169]
**Description:**
Private Thorsen offers the quest Jungle Secrets without being rescued from his scripted RP event.

**How to reproduce:**
Go to Private Thorsen and accept the quest Jungle Secrets.

**How it should work:**
Private Thorsen should do an RP event every 30 minutes, and only after he is saved does he offer the quest Jungle Secrets.
Reference this Wowhead comment from patch 3.3.2
https://www.wowhead.com/npc=738/private-thorsen#comments:id=993888
And this video
https://www.youtube.com/watch?v=GF1SkliEVGo

**Comment by alexspew** [comment]
Hi! This issue has been resolved.
