### ISSUE TITLE
Quest [Load'er Up!] - escorted NPC's behaviour

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#17]
Description: 
1. When i use fly mount quest npc (which is mule horse) fly with me. 
![WoWScrnShot_110820_213849](https://user-images.githubusercontent.com/52035924/98484320-f037b000-220e-11eb-81a5-7de9c3702c80.jpg)
2. Npc should disappear after completing quest.

How to reproduce: Try do this quest

How it should work: Npc should stay on the ground, screenshot is from retail
![WoWScrnShot_110820_220510](https://user-images.githubusercontent.com/52035924/98484338-02b1e980-220f-11eb-99e7-66904420f271.jpg)

Additional info: I assume that many of these escort quests are bugged equally

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
