### ISSUE TITLE
[Quest] [Bring the Light]

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#170]
**Description:**
When you turn the quest in, Archbishop Benedictus should cast Power Word: Fortitude (Spell ID: 2791) on the player.

**How to reproduce:**
Turn the quest in and receive no buff.

**How it should work:**
When you turn the quest in Archbishop Benedictus should cast the spell Power Word: Fortitude (Spell ID: 2791) on the player. I have no video, but if you look at the wiki you can see the NPC has that spell listed under his abilities.
https://wotlk.evowow.com/?npc=1284#abilities

**Comment by WubWub24** [comment]
https://www.youtube.com/watch?v=mHJe2HpX3g4   . Guess not.
