### ISSUE TITLE
[Quest] [Kodo Roundup]

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#171]
**Description:**
Tamed Kodo is neutral.

**How to reproduce:**
Use the Kodo Kombobulator on one of the kodos.

**How it should work:**
Tamed Kodo should be friendly and not neutral so other players cannot attack it.
https://www.youtube.com/watch?v=TDotkQnD0gY

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
