### ISSUE TITLE
Warrior stance quests

### ISSUE THREAD

**Issue by whitemanetribe** [SallyWhitemane/Mograine#172]
**Description:**

It's stated that abilities such as warrior stances will be automatically learned while levelling - this however is not the case

**How to reproduce:**

Level a warrior to 10, you don't receive defensive stance - level to 30 and you don't receive zerk stance

**How it should work:**

If I'm not mistaken you should receive those stances at level 10 and 30 respectively automatically and not have to do the quests.

**Comment by Version420** [comment]
Fixed

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
