### ISSUE TITLE
Tooltip Bug Slice and Dice with T6 2piece-bonus

### ISSUE THREAD

**Issue by Crzyfist** [SallyWhitemane/Mograine#173]
**Description:**
T6 2piece-bonus gives you an extra 5% haste on Slice and Dice, it does give the extra haste but the buff still shows the standard and not the 5% extra.
https://wotlkdb.com/?itemset=668
**How to reproduce:**
put on 2 T6 pieces and pop Slice and Dice

**How it should work:**
overall it works, it's just a tooltip bug

**Comment by keelash123** [comment]
Im prty sure your class ability buff shouldnt show you the set bonus diference.
