### ISSUE TITLE
[Quest] [Prisoners of the Grimtotems]

### ISSUE THREAD

**Issue by AugustFloden** [SallyWhitemane/Mograine#175]
**Description:**
The quest "Prisoners of the Grimtotems" works correctly, but the cages that you free the humans from do not respawn.
This makes it so that other people cant complete the quest.
Print screen: https://cdn.discordapp.com/attachments/572936860356050970/795039724230148187/unknown.png
The quest: https://wotlk.evowow.com/?quest=11145

**How to reproduce:**
Let one player open the cages to make them despawn. 

**How it should work:**
Cages should respawn together with the NPC's that you free.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
