### ISSUE TITLE
[Quest] [Just around the corner]

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#176]
**Description:** You can currently just fly in to the goblin and grab the quest item. The goblin Janks is missing his  monologue which he should say once someone get close to him/the quest item.

**How to reproduce:** Grab the quest and fly there.

**How it should work:**  You should get shot down/dismounted when approching them on a flying mount by the "anti air turrets" (the black squares one the ground).
[Quest info](https://wowwiki.fandom.com/wiki/Quest:Just_Around_the_Corner)
[Janks monologue](https://wowwiki.fandom.com/wiki/Janks)
[Youtube video](https://www.youtube.com/watch?v=bkEZAqH-FoI)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
