### ISSUE TITLE
[Quest] [Ample inspiration]

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#177]
**Description:** When you throw an u.d.e.d. on a mammoth it explodes and leave just one big mammoth carcass.
The small ones which should spawn at the same time, seems to spawn later. I saw the small carcasses (which should drop 1 mammoth meat) when I got back to a place were I had previously blown up a mammoth before.

**How to reproduce:**Grab an U.D.E.D and throw it on a mammoth.

**How it should work:** The mammoths should explode and spawn 1 big carcass and more small carcasses at the same time, enough to complete the quest with one bombing of a mammoth.

[A wowhead comment.
"If you're on the quest you don't need to be the one to blow up the mammoths. Once a mammoth is blown up the meat is free for all loot.
Also one mammoth will give you enough meat to complete the quest, just make sure to grab the big slab of meat first."](https://www.wowhead.com/quest=12828/ample-inspiration)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
