### ISSUE TITLE
[Quest] [Delicate touch]

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#178]
**Description:**The mobs Garm invaders, and Snowblind followers are stationary at Garm's Bane. 
Some also seems to be evade bugging with the towers at the north part of the tower line.

**How to reproduce:** Just fly there and observe.

**How it should work:** They should run towards the west side and be killed by the towers if not interupted by the player either attacking them or killing them with the "Improved land mines" by the "Danger" signs.

**Comment by enheken** [comment]
The mines also does not explode if the mobs just run at max speed over them. 
They only explode if the mobs stand still or are slowed by something when they walk close to the mine.
[Quest video](https://www.youtube.com/watch?v=1aCPJU9KysM)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
