### ISSUE TITLE
[Quest] [Opening the backdoor]

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#179]
**Description:** When you use the "Transporter power cell" at the Teleportation pad at Garm's Rise you get teleported back the K3 but instantly teleported back to Garm's Rise.

**How to reproduce:** Get the quest and the quest item needed and use it at the teleportation pad at garm's rise.

**How it should work:** You should only get teleported back K3 and not sent back to Garm's Rise immediately.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
