### ISSUE TITLE
Druid - Omen of Clarity - not working correctly

### ISSUE THREAD

**Issue by Noiminotnaomi** [SallyWhitemane/Mograine#18]
**Decription:**
OOC is not proccing as it is supposed to like on retail.

**What it should do**
>Proc off:
-Autoattacks/Maul
-Mana costing spellcasts (example would be using MotW prepull for free clearcast in raids or hotting raid when on move with Rejuvenation or even Tranquility)
-NO mana costing spells: Fearie Fire all forms so **Faerie Fire** (cat, bear and human form), Nature's Grasp, Innervate and Barkskin, Dash
-Rake & Rip with T8 2p { altho % seems way off here, would be nice if you checked that one too, as it **BARELY** procs, Clearcasts proc rate should be 5.83333% (https://www.wowhead.com/spell=16864/omen-of-clarity#comments) }

**What it doesn't do**
> It's not proccing off: 
-Faerie Fire(Feral)
-Barkskin
-Nature's Grasp
-Dash
-Maul (Keep in mind this is **Enchanced Autoattack** it should still proc Clearcasts)

**How to reproduce:**
Get on druid, and go slap some target.
Make sure you limit yourself to specific source or check combat log properly to see what exactly it procced off.

**Resources:**
One of resources would be this guy getting **Clearcast** off a **Barkskin**, while he was **Stunned**, so **No other spell** was being used at that time:
https://youtu.be/WuWOFtk6JS4?t=122

Since there are not many video sources, I'm going to quote from this site:
https://vanilla-wow.fandom.com/wiki/Omen_of_Clarity
,,**Tips and Tactic**”
,,**Free abilities**” that have a chance to trigger Clearcasting, most notably **Nature's Grasp**, can if they are not needed be used each time they are ready, giving and extra chance to trigger a **free Clearcasting**.

Another quote from this website:
https://wowwiki.fandom.com/wiki/Feral_DPS_guide
,,DPS algorithm/rotation”
,,6. If you have less than 35 Energy, use [Tiger's Fury] (or [Nature's Grasp] - which can proc [Omen of Clarity]). ”

**Faerie Fire - Method Logs**
http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=spell+%3D+"Clearcasting"%0D%0AAND+sourceName+%3D+"Oranoss"%0D%0AOR+spell+%3D+"Faerie+Fire+(Feral)"%0D%0AAND+sourceName+%3D+"Oranoss"+&page=1

[18:05:42.211] Oranoss's Faerie Fire (Feral) fades from Volatile Ooze
[18:05:44.934] Professor Putricide's Faerie Fire (Feral) is refreshed by Oranoss
[18:05:45.067] Oranoss gains Clearcasting from Oranoss
[18:05:47.980] Oranoss casts Faerie Fire (Feral) on Volatile Ooze
[18:05:48.263] Volatile Ooze afflicted by Faerie Fire (Feral) from Oranoss

[18:36:01.079] Oranoss casts Faerie Fire (Feral) on Blazing Skeleton
[18:36:01.153] Blazing Skeleton afflicted by Faerie Fire (Feral) from Oranoss
[18:36:01.494] Oranoss gains Clearcasting from Oranoss
[18:36:02.103] Oranoss's Clearcasting fades from Oranoss

**Lastly**, I'd like to direct you to Sunwell post, they've been dealing with OOC issues for over two projects, unable to fix it completely, they made Maul, Barkskin, Nature's Grasp proc it, but other sources were messy, and **MANY TIMES** during their ,,**Fixing of OOC**” they managed to **Completely Break** it, either not proccing at all from anything, or literally proccing off everything, like shapeshifting, standing in campfire (making people put it under boss) or holy paladin's beacon (< this was really broken btw).
https://github.com/SunwellTracker/issues/issues/2500

**I wish you goodluck**, this is a tough one to not mess up, be sure to test everything twice, cause there can be same fate awaiting you, fixing it one way, breaking it other way :)
Thank you

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
