### ISSUE TITLE
[Druid][Balance]Moonkins are generating too much aggro... once again!

### ISSUE THREAD

**Issue by ghuser44** [SallyWhitemane/Mograine#181]
**Description:**
Moonkin spells are generating more aggro than they should be, **again**. It seems like the talent **Nature's Reach** is not reducing aggro correctly, too. I had **2/2** points in Nature's Reach and was generating as much, if not more, aggro than another boomy with only 1/2 in it, with basically the same dps rotation/damage done. I was pulling aggro off of tanks even after waiting for more than 5 sec after pulls. Threat shoots through the roof, after few casts, especially once **Starfall** is used, even on single target dps, few seconds after a pull. We could be at the bottom of the dps meters and still pull aggro, somehow...
The class is literally unplayable, atm...

**How to reproduce:**
Go in any raid, fully buffed, with a normal raid setup.
Deal damage to anything that tanks have aggro on (optimal dps rotation and whatnot).
Die because you pulled aggro after few casts... even though you started dpsing last in the raid!

**How it should work:**
Check the code on threat values generated from each moonkin spell, especially **Starfall**.
Check the code on threat reduction value on **Nature's Reach** too.
Something is off...

**Comment by Riverwinn** [comment]
Can confirm that. The most efficient way of dpsing with moonkin now is casting starfire, listening to omen aggro sound, casting starfire etc. Last time, after the Nature's Reach issue was fixed, it was better, now its back to the start.

**Comment by keelash123** [comment]
im 99% sure this is autolearning problem we had this same issue on our nonamed server, it learning druid aura from bearform that increases his threat, im prty sure this aura wasnt only spel that players shouldnt have , we even throw autolearning away and make personal trainers because autolearning causes us many problems. Ofc i could be wrong but im prty sure im not.

**Comment by Rugsz** [comment]
Yep I can also confirm this bug. It's either the auto learning like @keelash123 said or the 2/2 Nature's Reach providing a 30% threat increase instead of a 30% threat reduction to balance spells. I can provide logs & clips as well if needed by the staff.

**Comment by Riverwinn** [comment]
Tested the threat today with Nature's Reach talented 0/2 and 2/2 using the tiny threat plugin from Details. Used spells with maxed rank and spells with 1 rank lower than max rank. Here are the results:

_Nature's Reach with **max rank** spells:_
**0/2 NR** - 500k damage - 1.450.000 threat
**2/2 NR** - 500k damage - 1.200.000 threat
**1.2/1.45 = 0,8276** (even considering rng factor its not close to 30% threat reduction)

_Nature's Reach with spells **1 rank lower than** max:_
**0/2 NR** - 500k damage - 1.440.000 threat
**2/2 NR** - 500k damage - 1.180.000 threat
**1.18/1.44 = 0,8194**

Dont know how informative it is, but seems like the NR always reduces threat on a 1/2 talent level. Also skills with lower ranks differ a bit in base damage so i think they shouldnt generate the same amount of threat as max rank spells. Either way threat multipliers seems odd (like e.g. 1.450.000 threat with 500k damage gives out **multiplier = 2.9**).

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
