### ISSUE TITLE
[Druid] Tiger's fury not buffing bleeds

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#183]
**Description:**
Tiger's Fury currently does not buff bleed damage

**How to reproduce:**
Use Rake on enemy and check peroidic damage. Buff yourself with Tiger's Fury and apply Rake, the DoT does same dmg

**How it should work:**
Tiger's Fury should snapshot and buff bleeds like Rake and Rip when you use it before applying the bleeds

**Comment by styxel** [comment]
Tf doesnt buff bleeds is correct behaviour

**Comment by Jokieh** [comment]
TF just adds flat damage to your autoattacks. Shred, claw and mangle should scale with the TF buff, bleeds shouldn't as they scale only from attack power.

**Comment by styxel** [comment]
Yeah there was once a tooltip that said it doesnt affect finishing moves (rip,fb), rake or pounce bleed. tigers fury snapshotting came in cataclysm.

**Comment by Version420** [comment]
![image](https://user-images.githubusercontent.com/33231743/104014560-e8b76780-51bb-11eb-96b5-5a2a3a3b9e2e.png)

**Comment by Version420** [comment]
![image](https://user-images.githubusercontent.com/33231743/104014908-7c893380-51bc-11eb-9039-a2dadebad5cc.png)

**Comment by styxel** [comment]
Thats copypaste from how cata feral works, tf doest work on bleeds In wotlk.

**Comment by nippari** [comment]
thats from like cata or later expansion since theres talk about 25% fb which is not available in wotlk content but idk if tigers fury worked on bleeds in wotlk.

**Comment by styxel** [comment]
Bleeds only benefit from ap and %multipliers tigers fury gives smthing else. 
Same with ferocious bite it gains nothing from tf. 
So tf should work just fine atm. 

https://www.youtube.com/watch?v=5uIhEWc16sk 
0.35 tigers fury/agile buffed rake - 2219/2218 dmg/tick
0.45 rake with no tf/with agile - 2219 dmg/tick 
so no change in damage with tf.
