### ISSUE TITLE
Shaman totem quests

### ISSUE THREAD

**Issue by Version420** [SallyWhitemane/Mograine#188]
**Description:**
It's stated that abilities will be automatically learned while levelling - The issue is that shamans learn the ability but CAN'T USE it without a totem => they are still forced to do the quests. This being unfair, because for example warriors can skip stance quests, so can every other class.

**How to reproduce:**
Level a shaman to 4, you receive the spell but **not the totem so you can't use the spell** - level to 10 get the spell but no totem to give the ability to use it - so on.

**How it should work:**
You should get **Totem of the Earthen Ring** item by default to be able to use the spells u get by leveling. Otherwise shamans will be **UNDERPRIVILEGED**. Considering the fact that other classes can skip their quests for spells.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
