### ISSUE TITLE
Character has 10 all resistances for no reason

### ISSUE THREAD

**Issue by beeefcaqe** [SallyWhitemane/Mograine#191]
My character (named Choochoo) appears to have +10 to all resistances for no reason that I can tell.
I have tried to:
+ unequip all gear
+ reset my talents
+ die
+ logout
+ restart my game
+ delete cache
+ gain and lose resistance buffs

...and I still have +10 all resist.
Considering how persistent it is, it's pretty bad even if only visual.

**Comment by alexspew** [comment]
Invalid. Please follow proper report forms
