### ISSUE TITLE
Lifeblooms and Dispels

### ISSUE THREAD

**Issue by tii86** [SallyWhitemane/Mograine#192]
**Description:**
Lifebloom does not "bloom" when dispelled.

**How to reproduce:**
1. Duel someone
2. Apply lifebloom to yourself
2. have them dispel you
3. ....
4. plz fix

**How it should work:**
when lifebloom is dispelled, a heal should occur (and mana back for the caster) on the target whom the lifebloom was on. See the tooltip description in game.

**Comment by Zeorgbugfinder** [comment]
i tested it works normally, prob fixed already

**Comment by tii86** [comment]
nah its still broken. I guess it should be noted that I'm using spellsteal to test this.

**Comment by Zeorgbugfinder** [comment]
aha, I tried it with pri dispel and worked well

**Comment by Zeorgbugfinder** [comment]
I tested it, it works as it should work
mage who spellstealed lifebloom is healed by ending bloom and druid gets the mana for lifebloom

**Comment by tii86** [comment]
I don't think you understand how it's supposed to work. 

When lifebloom is dispelled by mage, 3 things should happen.
**1. The lifebloom heal "blooms" on target from which it was dispelled.
2. The druid that casted the lifebloom recieves the refunded mana back associated with the spell.**
3. The mage relieves the lifebloom hot.

When a priest dispels, only the first two items happen of course.
Note that when dispelled on test realm, neither first nor second item occur. (priest / mage dispel).

https://youtu.be/wRqXyydSMAQ

Please check out this video to see how it works, made on blackrock.

**Comment by Zeorgbugfinder** [comment]
oh, so this is how it works...
on sunwell its bugged too then I just tested it here works same way as on whitemane
no wonder i had such problems vs mages as rdruid on sunwell...

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
