### ISSUE TITLE
[Death Knight] Empower Rune Weapon Doesn't Refresh Death Runes

### ISSUE THREAD

**Issue by jcm9400** [SallyWhitemane/Mograine#193]
**Description:**
Empower Rune Weapon is refreshing normal runes (blood/frost/unholy) but **not** death runes.

**How to reproduce:**
Convert a blood rune to a death rune with blood tap, deplete the rune with an ability, then try to use empower rune weapon. All other runes will be refreshed except the death rune.

**How it should work:**
All runes **including** death runes should be refreshed when using Empower Rune Weapon. Video from retail has it shown at the 3:49 mark. Sorry, couldn't find a cleaner retail video to use.

https://www.youtube.com/watch?v=2ozDHQwi044

**Comment by AndreiGameDev** [comment]
I can confirm it doesn't, fix this please ;-;

https://user-images.githubusercontent.com/49598916/104085693-4c3ba680-5249-11eb-964d-6791ff485dba.mp4

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
