### ISSUE TITLE
[Death Knight] Death runes are laggy/non responsive (Rune Grace Period?)

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#194]
**Description:**
When playing with Death Rune Mastery (Blood talent) and u try use an ability that spends runes it wont go off until 1-2 sec of spamming that ability. The runes shows as ready on my client but while spamming they wont go off until 1-2seconds (server preventing it). Maybe it's because of the Rune Grace Period? https://github.com/TrinityCore/TrinityCore/issues/6122 Maybe Rune Grace period is not working for Death runes?

**How to reproduce:**
Do normal rotation and spam your rune spending abilities while looking at runes. Sometimes blood strike wont go off, sometimes death strike wont go off. Something is preventing it. 

**How it should work:**
When runes are ready you should be able to use them instantly

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
