### ISSUE TITLE
Quest "Hellscream's Vigil" bug

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#198]
**Description:**
I was just able to accept the Quest "Hellscream's Vigil" (Borean Tundra starting Quest) twice and also turn it in twice

**How to reproduce:**
Go to the NPC and talk to him 

**How it should work:**
Should only be acceptable once

![Hellscreamsvigil](https://user-images.githubusercontent.com/77163864/104106438-30221e80-52b6-11eb-8f8f-99e44eb39446.JPG)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
