### ISSUE TITLE
[Shadow Priest] Unable to cast Dispersion while Maim or Kidney shot

### ISSUE THREAD

**Issue by Starcallerx** [SallyWhitemane/Mograine#199]
**Description:**
It has been observed that Shadow priests are not able to use Dispersion while affected with Maim from a druid or Kidney shot from a rogue. Both Maim and Kidney shot are considered stuns and as per Dispersion tooltip, it should work while in stun. I also tested this out on other servers like Blackrock and Sunwell and found out that Shadow priests there are able to cast dispersion while in Main or Kidney shot.

**How to reproduce:**
1. Make 3 characters. A Shadow priest, Feral druid, and Rogue.
2. Duel the Shadow priest with the druid and druid uses maim on the Shadow priest.
3. Shadow priest uses dispersion while affected with Maim.
4. Notice that the Shadow priest is not able to use dispersion for the whole duration of Maim.
5. Now duel the shadow priest with Rogue and rogue uses Kidney shot on the Shadow priest.
6. Shadow priest uses dispersion while affected with Kidney shot.
7. Notice that the Shadow priest is not able to use dispersion for the whole duration of the Kidney shot.

**How it should work:**
Shadow priests should be able to use Dispersion while in Maim or Kidney shot.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
