### ISSUE TITLE
Mage: Glyph of Frost Nova, does not work

### ISSUE THREAD

**Issue by dlohvyn14** [SallyWhitemane/Mograine#20]
Hello.

The Glyph is supposed to give a chance for the targets to receive up to 20% more damage before the nova brakes. Tested a few times on lvl 80 dummy, there was no any increase in numbers when casting frostbolt with that glyph. The item is very useful while leveling as a shatter mage as well as for some high-end 2s setups like with rogue

Thanks for attention

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
