### ISSUE TITLE
Quest "Get to Getry" bug

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#200]
**Description:**
If you're going to the Quest "Get to Getry", the NPC "Varidus the Flenser" is already there, aggros on you and kills you.

![varidus](https://user-images.githubusercontent.com/77163864/104110869-1e537200-52dc-11eb-8b10-615a3fb4069b.JPG)

[edit:] the follow-up quest is missing the entire dialogue, both audio and chat. Seems like the whole thing is fucked up
**How to reproduce:**
Go there.

**How it should work:**
Varidus should only get active and attackable after you have accepted the next quest and the event started.

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/449
