### ISSUE TITLE
[Quest Bug] The Emissary

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#201]
**Description:**
When you dive down to kill Leviroth, you need to swim almost in melee range to be able to use the harpoon on him. He actually aggros on you and hits you before you can use it. Probably impossible for clothies.

**How to reproduce:**
Do the quest.

**How it should work:**
Harpoon has to be usable way before he aggros on you.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
