### ISSUE TITLE
draenei racial 2x

### ISSUE THREAD

**Issue by honzii1** [SallyWhitemane/Mograine#203]
**Description:**

draenei female paladin has 2x racial no shared cd
**How to reproduce:**
make female draenei paladin

**How it should work:**
only have 1x racial
[]https://i.gyazo.com/5589fb03196eec63dc0d32ccf4808e87.jpg(url)

**Comment by Version420** [comment]
tested on shaman male, he also get 2 racials of each 
![image](https://user-images.githubusercontent.com/33231743/104120922-390d0180-5343-11eb-8c67-3247dd3b521c.png)

**Comment by Version420** [comment]
Tested it o shaman male, he also gets 2 of each racials

**Comment by WubWub24** [comment]
Also Blood Elf Gets 2x Arcane Torrent

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
