### ISSUE TITLE
[DK] Deathgrip bug

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#206]
**Description:**
When you stand on the Water with Path of Frost and grip something from the water, it doesnt come to you but instead glitches like 60 yards deep in the water and then starts running to you. Happened to me every time with Glimmer Bay Orcas while doing the quest "Succulent Orca Stew"

**How to reproduce:**
Stand on Water with Path of Frost and grip something swimming in the water

**How it should work:**
obvious

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
