### ISSUE TITLE
[API][DK] Unplayable stutter with GetSpellCooldown()

### ISSUE THREAD

**Issue by InflictWounds** [SallyWhitemane/Mograine#207]
**Description:**
Attempting to use GetSpellCooldown() API call for spells using runes when the runes are on cooldown results in unplayable stutter.

Example video:
https://streamable.com/vww0av
First is Frosthold, second is Whitemane PTR same UI.

**How to reproduce:**
Make a WeakAura to track spellcooldown for a spell using runes then do basic combat against a dummy.

Example setup:
https://cdn.discordapp.com/attachments/787539382029647873/797822434690596884/unknown.png

or copy one of the following:
https://pastebin.com/EZsxGSJg
https://pastebin.com/v32kPQV8

**How it should work:**

No lag, no stutter, seamless experience.

**Comment by yorks-yorks** [comment]
Can confirm - 100% chance to reproduce

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
