### ISSUE TITLE
[Item] Illustration of the Dragon Soul bug

### ISSUE THREAD

**Issue by Arclowe** [SallyWhitemane/Mograine#208]
**Description:**
Illustration of the Dragon Soul trinket procs on any spell you do (tested - mage armor, conjure refreshment, food/eating - I'm sure there are many more).

**How to reproduce:**
1) Have illu trinket.
2) Cast Mage Armor (or some other non-dmging/healing spell) 10 times before pull.
3) ?????
4) Profit

**How it should work:**
Trinket should only proc on damaging/healing spells.

![2021-01-10_161704](https://user-images.githubusercontent.com/62103976/104126893-77181e80-535f-11eb-88fa-6358fe64c85e.png)

**Proof:**
https://youtu.be/QA15c1Yzul8

**Comment by Riverwinn** [comment]
it procs also on clicking fish feast, picking mage food. Seems like every action stacks that.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
