### ISSUE TITLE
Feral swipe

### ISSUE THREAD

**Issue by nippari** [SallyWhitemane/Mograine#209]
**Description:**
Feral swipe (cat) counts as a finishing move? when u use it on a target thats affected with something that makes u miss on it your swipe will only cost 80% of its energy.  [primal precision] talent causing this?

**How to reproduce:**
cyclone 1 target aoe, swipe on the cycloned target see that u can spam infinite swipes aslong as the target is immune to your swipes propably works with banish too etc.

**How it should work:**
swipe is not a finishing move so it shouldnt refund energy or atleast work like this.

**Comment by Rugsz** [comment]
It worked like this on a few other servers I've played on. I'd suggest researching and confirming if this is 3.3.5 retail-like since it's such a common "bug" it might not actually be a bug.

**Comment by styxel** [comment]
It would be very hard to find such scenario where someone is swiping on a cyclone in retail, but theres stuff like this https://youtu.be/WuWOFtk6JS4?t=44 where he uses **rake** which is also not a finishing move and it **fails to land** -> dodges and hes not losing almost any energy that kinda confirms that it was not working as the tooltip says even in retail. (think this video is from retail?)
