### ISSUE TITLE
[Mob Behaviour] Agro range feels very un-natural

### ISSUE THREAD

**Issue by Doppiu** [SallyWhitemane/Mograine#21]
Not sure if this is a custom change, close the issue if it is. 

Agro range is very very un-natrual, I've attatched a gif of me (level 4) agroing a mob (level 7) from a pretty fair distance away. I feel if the range was reduced by around 15%-20%-25% it would feel a lot more natural and blizzlike. Even at level 80 I'm agroing mobs (1-69) from around 4-7 yards away so I think there's an issue with agro range accross the board since it overcompensates the range if the mob is higher than you are, but if you're higher than the mob there is no grace system that reduces the range you're agroed at.

https://gfycat.com/vigilantperfumedharpseal

**Comment by Doppiu** [comment]
After a bit more playing I feel this can't be a custom change, it is literally impossible to do any sort of quests that have enemies in close proximity with other enemies at lower levels, the agro range is just wayyy too overshot

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
