### ISSUE TITLE
Shaman totem quest correction because totems are undeletable

### ISSUE THREAD

**Issue by keelash123** [SallyWhitemane/Mograine#211]
https://github.com/SallyWhitemane/Mograine/issues/188

dont give shamans 4 undeletable totems give them ,,Totem of the Earthen Ring" 66747 it is final class quest reward that have same efect as 4 totems and you can equip it, it give no stats and it can be deleted also some shamans doing class quest for good experience points and they can get duplicated undeletable totems THATS LITERALY MAKE NO SENSE :D they can have locked 4-8 inventory slots.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
