### ISSUE TITLE
Mage-talent - Fingers of Frost

### ISSUE THREAD

**Issue by keelash123** [SallyWhitemane/Mograine#214]
how is that talent bugged ? - fingers of frost stacks are removed after spellcast is finished.

how it should work ? - fingers of frost stacks should be removed after spell land on target.

if you dont play mage it seems as minor bug but this is prty gamebreaking bug it makes frost mage unplayable pve and rly hurts him in pvp this should be one of prio to fix .

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
