### ISSUE TITLE
Racial swapping as nelf priest

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#215]
**Description:**
When swapping night elf priest to draenei racial u learn Gift of the Naaru attack power version (doesnt scale with SP)

**How to reproduce:**
make nelf priest, race shift to draenei

**How it should work:**
priest should get gift of the naaru that scales with SP

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
