### ISSUE TITLE
Quest : Inoculation 

### ISSUE THREAD

**Issue by Balticat** [SallyWhitemane/Mograine#216]
**Description:**
The quest requires you to use a item on a Npc for a couple of seconds (channeling it on the npc ) and after the channel ends it should complete the objective but even if you cancel it early it still after a couple of seconds have past (as if you completed the channel) it still completes the objective.

**How to reproduce:**
It doesnt matter what class you use it works the same on all.Just try yo do the quest.

**How it should work:**
It should complete the channel and then complete the quest objective.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
