### ISSUE TITLE
Demons at Outland Portal

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#217]
**Description:**
When you enter Outland through the Portal, all friendly NPCs just stand there and do nothing and there's like 10 level 70 Elite Demons aggroing on you and killing you when you try to turn in the starter Quest.

**How to reproduce:**
Go there

**How it should work:**
The friendly NPCs should be fighting the Demons so they don't aggro on you

**Comment by keelash123** [comment]
![WoWScrnShot_011521_151116](https://user-images.githubusercontent.com/58020391/104737254-4e6b9c80-5744-11eb-89cb-64bc833c66c9.jpg)

we had same issue on our nonamed server - problem is that in some time demons will owerwhelm friendly npcs and make huge waves that oneshot everithing in their way its snowball effect - solution is lower damage of demons that they canot make huge waves or something like that

**Comment by alexspew** [comment]
Hi! Please contact me on discord (alexs) if this remains to be an issue. Thanks!
