### ISSUE TITLE
Paladin Mount

### ISSUE THREAD

**Issue by WubWub24** [SallyWhitemane/Mograine#220]
**Description:**Paladins learn different mount . Argent Charger and Argent Warhorse  ( both of them from argent tournament ) when they need to learn Charger and Warhose

**How to reproduce:**
Make a paladin. Learn all spels

**How it should work:**

**Comment by SallyWhitemane** [comment]
The auto-learn feature doesn't teach mounts anymore, and Apprentice Riding (level 20) will be learned automatically for free as one of the Autolearn features. You will still have to purchase the mount for 85 silver or learn it at your class trainer
