### ISSUE TITLE
Warrior Intercept stuning hunter through deterrance

### ISSUE THREAD

**Issue by karolbis** [SallyWhitemane/Mograine#223]
Decription:
Detterance works only against charge in battle stance, if warrior is in berserker stance, his Intercept just stuning hunter through detterance.

How it works:
Detterance works only against charge in battle stance, if warrior is in berserker stance, his Intercept just stuning hunter through detterance.

How it should work:
Warrior intercept should be parried or dodged. Hunter cant get stuned during detterance

Proofs:
Whitemane:
https://vimeo.com/500901535

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
