### ISSUE TITLE
[Quest] Blending in

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#224]
**Description:**
If you go in the Temple shrouded and then aggro and fight an abo, you cant use the cloak again and get into the stealth.

**How to reproduce:**
Do it

**How it should work:**
Obvious

**Comment by lineagedr** [comment]
Equip / Unequip?

**Comment by alexspew** [comment]
Quest confirmed working fine. Unequip cloak as lineagedr says and equip it again after combat.
