### ISSUE TITLE
T7-Bugs compendium

### ISSUE THREAD

**Issue by AugustFloden** [SallyWhitemane/Mograine#227]
**Description:**
First off - the general mechanics of all t7-content was functioning.
No game-breaking bugs found except for Noth ([3]) and its possible that other bosses have the same reset-mechanic and it should be investigated further.
Below are the only major bugs we found, other than that usual spells were working just fine.
 **How to reproduce:**
[1]: Grand Widow Faerlina.
 - Killing the adds does not remove enrage. It also doesnt prevent Poison volley being cast.
[2]: Maexxna
- The individual webs only attach people to the left side.
[3]: Noth
- Dragging the boss to the green wall will reset the boss completely.
[4]: OS
- Firewall doesnt knockback.
 **How it should work:**
[1]: Grand Widow Faerlina.
- Killing adds should place a debuff on Faerlina and prevent her from casting poison volley and dispell enrage.
[2]: Maexxna
- The individual webs should attach people to "closest walls", not only left side.
[3]: Noth
- Boss should 
[4]: OS
- Firewall should knock players back

**Comment by nippari** [comment]
this is 10man? afaik 

Grand Widow Faerlina.

Killing the adds does not remove enrage. It also doesnt prevent Poison volley being cast.

should only work in 10man right? but killing adds shouldn't prevent poison valley or enrage in 25man

**Comment by Arclowe** [comment]
the noth bug was also present on frosthold. if noth was close to wall and he blinked into the green wall, he would reset.

**Comment by Jamiexdx** [comment]
Yes this was all done on 10 man we are aware you need to MC the adds on Faerlina for 25 man

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
