### ISSUE TITLE
Wyvern sting autoloearned without talent

### ISSUE THREAD

**Issue by ammenvale** [SallyWhitemane/Mograine#228]
**Description:**
Wyvern sting https://www.wowhead.com/spell=19386/wyvern-sting
has been autolearned even if I don't have the talent
(I only noticed at lvl50, I assume rank 1 was autolearned at lvl40)

**How to reproduce:**
Level a hunter 40+
Don't spec survival
Check if Wyvern Sting is avail in talents

**How it should work:**
spell gained through talents shouldn't be autolearned if you do not have the talent

![wyvern](https://user-images.githubusercontent.com/45928535/104797770-a202d800-578e-11eb-9471-5a3399680ec2.PNG)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
