### ISSUE TITLE
[SHAMAN] Thunderstorm cannot be used in most of the boss stuns

### ISSUE THREAD

**Issue by Redstarboss** [SallyWhitemane/Mograine#229]
**Description:**
Yesterday we did a full naxx10 test and one of the bugs i found was that i can't use thunderstorm in Maexxna web spray (its a stun) and i can't use it in Sapphiron ice tomb, which is also a stun. You should probably look at every boss stun, because i think this is the case with all of them.
Thunderstorm should be able to used in stuns.

**How to reproduce:**
Get Web Sprayed by maexxna.

**How it should work:**

You should be able to use thunderstorm in stuns.

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues/23
