### ISSUE TITLE
Spell [Thunderstorm] is usable in cocoons

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#23]
Description: You can use thunderstorm while you are under effect of [Web Wrap](https://www.wowhead.com/spell=52086/web-wrap) spell (Azjul Nerub mobs) and Maexxna Web Wrap (can't find link). Webs are also vulnerable to knock-up's (tested on thunderstorm, but i think DK grip, bala typhoon will work like that too.)

How to reproduce: naxx maexxna, azjol nerub's mobs, both tested today.

How it should work: According to wowhead comment, people thought it's bug, but it's been correct behavior.
![image](https://user-images.githubusercontent.com/52035924/98582042-b0320500-22c2-11eb-9c7a-d3b305f64d9b.png)
I also tested on retail:
![WoWScrnShot_110920_183348](https://user-images.githubusercontent.com/52035924/98582514-58e06480-22c3-11eb-942b-1a29502df843.jpg)

So in cocoon you can't use thunderstorm, and cocoon shouldn't be vulnerable by moving action (thunderstorm, typhoon, grip)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
