### ISSUE TITLE
soloQ bugs

### ISSUE THREAD

**Issue by Zeorgbugfinder** [SallyWhitemane/Mograine#231]
![Z SOLOQ](https://user-images.githubusercontent.com/58181528/104815185-57776f00-5813-11eb-8eaf-ecc23e9ada7c.jpg)
pls fix gladius not showing 5v5 overlay in soloQ its anoying
![Z SOLOQ2](https://user-images.githubusercontent.com/58181528/104815183-547c7e80-5813-11eb-9c27-3f7fd63e40c2.jpg)
another bug showing 21 hours queue time after 1sec of being in queue but its w/e

**Comment by SallyWhitemane** [comment]
First one is addon issue, second one is fixed.

**Comment by Zeorgbugfinder** [comment]
Not addon issue... I cant fix it by dling new one, on warmane's soloQ it doesnt show 5v5 overlay
