### ISSUE TITLE
Quest "Into the Pit" & "The Warm Up"

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#232]
**Description:**
The Bear you sit on doesn't auto attack, the fight vs the Matriarch is only doable with kiting. Lots of damage missing
There's also too few hostile Bears to kill for "Into the Pit", there should be lots dueling each other.

**How to reproduce:**
Do the Quests

**How it should work:**
The Bear should auto attack

**Comment by alexspew** [comment]
Hi! This should be resolved on next server updates (wednesday) thank you!
