### ISSUE TITLE
Warlock: Drain Soul

### ISSUE THREAD

**Issue by stileerko** [SallyWhitemane/Mograine#235]
The first touch from the drain soul should reset the corruption and not the first touch from the drain soul dmg.
 Talent name: "Everlasting Affliction":
Your drain life, Drain Soul, Shadow Bolt, and Haunt spells have a 100% chance to reset the duration of your corruption spell on the target "and not dmg from spells

**Comment by Dunderj** [comment]
This is not a bug and it's correct in its current form

https://youtu.be/umHxIK5wi14?t=243

**Comment by stileerko** [comment]
it doesn't have to be a bug but it's set incorrectly. according to talent, it should reset it now and not when DMG gives it
