### ISSUE TITLE
[Priest] Vampiric touch Replenishment procs on all spells

### ISSUE THREAD

**Issue by scrublama** [SallyWhitemane/Mograine#236]
**Description:**
Vampiric Touch replenishment procs on all offensive spells
https://clips.twitch.tv/HeartlessElegantYamDendiFace

**How to reproduce:**
As a shadow priest apply Vampiric Touch and cast an offensive spell

**How it should work:**
Replenishment from Vampiric touch should only proc after the priest damage with a Mind blast

VT:
https://wotlk-twinhead.twinstar.cz/?spell=48160

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
