### ISSUE TITLE
Small drakes in The Obsidian Sanctum don't despawn after fast Sartharion kill

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#24]
Description: Small drakes in OS don't despawn after fast Sartharion kill. And you can still kill them on their original spots. Tested yesterday on PTR.

How to reproduce: If you kill Sartharion before some of the drakes joins the fight, these drakes stay alive at their original spots.

How it should work: I try it on retail, and you can't kill them after. And if you argue it could be a change after 3.3.5a, I think you aren't able to farm additional emblems from them.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
