### ISSUE TITLE
Hunter: Taming Quests: Game Breaking Issue

### ISSUE THREAD

**Issue by BushieHunter** [SallyWhitemane/Mograine#241]
**Description:**
Once you hit level 10 your Hunter class trainer will give you the learn to tame quest. There will be 3. You will be given a taming rod to tame a beast within the area. Once you "Tame" (It counts as a charmed creature I believe, it doesn't count as an actual hunter pet) You cannot get rid of this creature in anyway, there is not right click option to dismiss, the dismiss pet ability does not work. These are usually mandatory quests, they are not on your server due to unlocking all abilities however, they give an insane amount of experience for a quest that takes around a minute so it is safe to assume players will do them.  Once you attempt it you have ruined your toon.

**How to reproduce:**
Pick up any of the Way of the hunter quests at level 10 (I did mine in the dwarf starting zone)

**How it should work:**
Once you use the provided taming rod, you should be able to get rid of the creature immediately.

**Comment by FabiRotter2017** [comment]
Hunter Taming quest worked fine for me. After taming the first pet i could just right click the pet bar and dismiss it and tame a new one.

**Comment by SallyWhitemane** [comment]
Can't reproduce.
