### ISSUE TITLE
[Warrior] Sword Specialization is bugged

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#242]
**Description:**
Sword Specialization is bugged and currently only procs from white auto attacks

**How to reproduce:**
Take the talent Sword specialization and use a sword and attack, only time sword specialization procs is from white auto attacks

**How it should work:**
It should have a chance to proc from every attack aslong as you are in range of the target (with an ICD of 6 seconds)

https://wowwiki.fandom.com/wiki/Sword_Specialization_(warrior_talent)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
