### ISSUE TITLE
Missing animation

### ISSUE THREAD

**Issue by mdlsvensson** [SallyWhitemane/Mograine#243]
**Description:**
No walking animation on this turtle. It just floats around.

**How to reproduce:**
Go look at the turtle. Patrolling in Mo aki harbor.
![turtle](https://user-images.githubusercontent.com/38759823/104856994-d5bc3a00-5915-11eb-95c0-8f290bfb8484.png)

**How it should work:**
I guess it should have an animation like it's walking? I'm assuming.

**Comment by mdlsvensson** [comment]
Moa'Ki Turtle Rider

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues/174
