### ISSUE TITLE
Server disconnect

### ISSUE THREAD

**Issue by garoliman** [SallyWhitemane/Mograine#245]
**Description:**
This issue disconnects you from the server

**How to reproduce:**
You have to spam ESC -> logout or exit game when you are in combat

**How it should work:**

**Comment by WubWub24** [comment]
you get disconnect even if you /who and spam it from frame.

**Comment by scrublama** [comment]
ddos protection XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
