### ISSUE TITLE
Paladin: mount

### ISSUE THREAD

**Issue by Knapec** [SallyWhitemane/Mograine#247]
**Description:**
Dont know if you removed autolearning paladin mounts on purpose, but it stopped working. Also lvl 40 mount cannot be learned at trainer.

**How to reproduce:**
Level up paladin to 40 lvl.

**How it should work:**
You should either get them on 20 and 40 lvls

**Comment by Jamiexdx** [comment]
It was removed on purpose

**Comment by Knapec** [comment]
But you should be able to train it on 40 or no?

**Comment by mrnuggets** [comment]
> 
> 
> But you should be able to train it on 40 or no?

You have to learn / buy the 40 speed mount first at the mount trainer.

**Comment by SallyWhitemane** [comment]
The auto-learn feature doesn't teach mounts anymore, and Apprentice Riding (level 20) will be learned automatically for free as one of the Autolearn features. You will still have to purchase the mount for 85 silver or learn it at your class trainer
