### ISSUE TITLE
[Storm Peaks] Garm's Bane mobs

### ISSUE THREAD

**Issue by ammenvale** [SallyWhitemane/Mograine#248]
**Description:**
Garm invaders and snowblind followers are standing still in Garm's Bane
Currently there are also bugged mobs getting zapped then resetting indefinitely (see vid below)

These mobs are used for quest
https://www.wowhead.com/quest=12820/a-delicate-touch

https://streamable.com/qi0mv5

**How to reproduce:**
Go to Garm's bane

**How it should work:**
Garm invaders and snowblind should be running towards Snowblind hills and get zapped at the end. Then respawn in waves

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
