### ISSUE TITLE
Innervate and other druid spells not autolearned

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#249]
**Description:**
Innervate and some other minor druid spells not being autolearned

**How to reproduce:**
Level druid to the point where they can get innervate

**How it should work:**
Should be autolearned

https://gyazo.com/042130162f14d40528323797f95279c0

**Comment by styxel** [comment]
Worked like 3 days ago for me.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
