### ISSUE TITLE
Quest "Kodo Roundup" in Desolace

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Mograine#251]
**Description:**
After taming kodo in Desolace and bringing it to quest giver NPC, nothing happens. At this moment it's impossible to complete this quest.

**How to reproduce:**
Tame Kodo with quest item and drag it to quest giver NPC.

**How it should work:**
After dragging kodo to quest giver NPC should say something from his available scripts about inspecting the kodo, kodo should be then talkable in order to inspect it and count kodo as tamed for quest. It should look in similar way to this video https://www.youtube.com/watch?v=TDotkQnD0gY&t=58s .

**Comment by NonIdentifie** [comment]
Still not counted when you deliver the kodos to the indicated NPC.

**Comment by alexspew** [comment]
Fixed.
