### ISSUE TITLE
Clicking "Refresh" on "Who" tab disconnects you

### ISSUE THREAD

**Issue by mixit11** [SallyWhitemane/Mograine#252]
**Description:**

As in title, when you click Refresh on tab Who a lot of times in a row, you're gonna get disconnected from the server.
**How to reproduce:**
Just spam Refresh on Who tab

**How it should work:**
Idk? I'm not the developer, but I guess it shouldn't dc.

**Comment by alexspew** [comment]
This is a server-protection against spamming.
