### ISSUE TITLE
Druid Cat Tiger's fury interaction with Rake and Rip

### ISSUE THREAD

**Issue by Kepquet** [SallyWhitemane/Mograine#256]
**Description:**Druid Cat Tiger's fury is not working properly because the rake and Rip damage is not afected

**How to reproduce:**
Use  rip with same comob points Rip and rake with and without tiger's fury and the damage will be the same everytime

**How it should work:**Tiger's fury should increase the dmg on the spells by 10% so the tick dmg is auto increased too

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues/183
