### ISSUE TITLE
Unholy DK Summon Gargoyle Issues

### ISSUE THREAD

**Issue by Rugsz** [SallyWhitemane/Mograine#26]
**Description:**
Currently, the gargoyle from Summon Gargoyle is capped at only 29 casts of Gargoyle Strike & never interacts with a melee swing on this server.

**How to reproduce:**

I've tested this on target dummies on my DK on the PTR. 

**How it should work:**

The Summon Gargoyle has 2 key issues with the scripting.
1. The gargoyle should be melee attacking in between casts of "Gargoyle Strike" if it is summoned (or gets in melee range) of its target.

> https://www.youtube.com/watch?v=xWXVSnvD3Rg&feature=emb_title&ab_channel=Vodkaguild  -- This is a video where you can see the animations of the gargoyle melee attacking on DBS. Proper unholy DK gameplay is to just move out of melee range when you cast Summon Gargoyle and you won't run into this issue (which is a DPS increase to avoid the melees). Here is a log from a PP kill where you can confirm that the Gargoyle can and will melee attack if it's in range & there is a downtime on Gargoyle Strikes http://www.worldoflogs.com/reports/vweyx535vlctx49l/details/74/?s=10870&e=11167  -- additionally, there is a _reposted_ retail guide (original link expired) on unholy DKs that is on the warmane forums: http://forum.warmane.com/showthread.php?t=326654  only thing worth noting is "Also remember, your Gargoyle has horrid AI. It will not attack Yogg-saron's brain if summoned within the brain room (but will attack the brain if you summon it before entering the brain room) and will (usually) only **melee** XT Deconstructor's Heart."

2. The gargoyle should be able to exceed the gcd cap allowing more than 29 casts of Gargoyle Strike to hit the target. 

> https://imgur.com/gallery/dAB5uhT -- I've shown on the Whitemane core that you can max out the Gargoyle Strike count with only a 1070 haste snapshot and unholy presence. The snapshot with 2392 haste shows that you cannot exceed past the 1 second cast time. http://www.worldoflogs.com/reports/vweyx535vlctx49l/xe/?s=9471&e=9612&x=type+%3D+TYPE_CAST%0D%0AAND+sourceName+%3D+%22Ebon+Gargoyle%22%0D%0A

To end, Sunwell had this exact same issue and resolved it on their changelog on March 14, 2020. However, out of some quality of life change the reverted their fix on the melee scripting on September 28th, 2020. Gargoyles are still able to exceed gcd on Sunwell as it did on retail.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by Dunderj** [comment]
Garg is now doing 155k dmg in blue gear, might aswell remove other melee classes if this change stays
