### ISSUE TITLE
Quest npcs

### ISSUE THREAD

**Issue by corpsy13** [SallyWhitemane/Mograine#262]
**Description:**The lazy peons NPCs in durotar never sleep so we can't complete the quest

**How to reproduce:**

**How it should work:**
they should sleep sometime so we can all complete the quests

**Comment by alexspew** [comment]
Quest Name / QuestID
Lazy Peons / 5441

Npc Name / NpcID
Lazy Peon / 10556

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
