### ISSUE TITLE
Wolves in Duskwood not skinable

### ISSUE THREAD

**Issue by ossyn** [SallyWhitemane/Mograine#263]
**Description:**
When the wolves in duskwood are killed, I only get the loot symbol again after they are looted, hence I cannot skin them. Happened to multiple types of wolves, not sure if it is other types of mods.

**How to reproduce:**
Kill e.g a "Starving Dire Wolf", loot, then try to skin.

**How it should work:**
Should be skinable.

**Comment by alexspew** [comment]
Name / Entryid
Starving Dire Wolf / 213
Most likely missing skinloot id in creature_template

**Comment by alexspew** [comment]
Duplicate issue -> https://github.com/SallyWhitemane/Mograine/issues/261
