### ISSUE TITLE
Wintergrasp teleports not working

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#264]
**Description:**
Wintergrasp teleporters dont port you inside the fort or inside the base if  your faction owns WG

**How to reproduce:**
Click on the portal

**How it should work:**
It should port you into the fort or building but it doesnt.

https://gyazo.com/6a55be4d4c3f656f606e4dea6a642ac1
https://gyazo.com/03e00e80ed14da49c4e01b6424ccd846

these

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
