### ISSUE TITLE
Recipe: Transmute Arcanite

### ISSUE THREAD

**Issue by revrox** [SallyWhitemane/Mograine#265]
**Description:**
Recipe is limited stock but should be unlimited for sale @ npc - Alchemist Pestlezugg
item id 12958
**How to reproduce:**
Check vender - Alchemist Pestlezugg

**How it should work:**
Recipe should be unlimited stock.

**Comment by alexspew** [comment]
Alchemist Pestlezugg NPCID : 5594

maxcount = 0 (unlimited)
