### ISSUE TITLE
Only worgens in duskwood skinnable

### ISSUE THREAD

**Issue by umilic16** [SallyWhitemane/Mograine#268]
**Description:**
Cant skin anything but worgens. When i kill some wolf or something doesn even show "skinnable" when someone else kills it it shows skinnable but tells me the corpse should be looted even tho it is.

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Duplicate issue -> https://github.com/SallyWhitemane/Mograine/issues/261
