### ISSUE TITLE
Quest: WANTED: Murkdeep! (Darkshore)

### ISSUE THREAD

**Issue by Wayran-is-typing** [SallyWhitemane/Mograine#269]
I was in group with a hunter and we killed all the murloc's camp.

Murkdeep never appear.

Maybe the murlocs respawn to fast and thats the reason why the event never complete.

**Comment by alexspew** [comment]
Quest Name : WANTED: Murkdeep!
Quest ID : 4740

Npc Name : Murkdeep
Npc ID : 10323

**Comment by alexspew** [comment]
Quest fixed, thanks!
