### ISSUE TITLE
spirit healer missing borean tundra

### ISSUE THREAD

**Issue by herbhenk** [SallyWhitemane/Mograine#27]
Description:

I died as horde in valiance keep and when i released there was no spirit healer
![WoWScrnShot_111120_021409](https://user-images.githubusercontent.com/64539747/98753303-4f8af100-23c4-11eb-80d4-f42c29f7b9ae.jpg)

How to reproduce:

died in valiance keep as horde

How it should work:

there should be a spirit healer
https://www.wowhead.com/npc=6491/spirit-healer

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
