### ISSUE TITLE
"Thrusting Hodir's Spear" bugged

### ISSUE THREAD

**Issue by Smackadack** [SallyWhitemane/Mograine#273]
**Description:**

The dragon simply drops you to the ground while entering the execute phase, 4/4 attempts happened the exact same way. Not a grip issue.

**How to reproduce:**

Simply attempt the quest.

**How it should work:**

It should enter the execute phase (prying open the jaws of the dragon).

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
