### ISSUE TITLE
Warrior Charge Bug

### ISSUE THREAD

**Issue by omgitspancake** [SallyWhitemane/Mograine#277]
Warrior has a charge bug to run up walls, kinda fun but well Warsong Gulch will 

be a different story if someone charges into the spawn ....

BTW had to compress the doobie out of this video, gifthub 10mb only really ....?

https://user-images.githubusercontent.com/77955330/105671030-bb242b00-5eea-11eb-9f26-6c8868caac27.mp4

**Comment by danniellos94** [comment]
https://www.youtube.com/watch?v=n1YLzAEOs6M 5:39 + you should be able to charge on respawn on warsong gulch.

**Comment by alexspew** [comment]
Invalid. Please follow proper report forms
