### ISSUE TITLE
Herbalism and Minning tracking icons 

### ISSUE THREAD

**Issue by lapoki** [SallyWhitemane/Mograine#28]
Hi there,
I noticed that when you learn herbalism or minning there is a visual bug for the tracking icon on mini map it shown twice and both of them are working fine. Maybe they are just doubled in the mini map tracking options.

How to reproduce:
-Learn herbalism->go to mini map and track herb nodes-> you should see two icons for tracking nodes;
-same for minning

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
