### ISSUE TITLE
Auctioneer addon posting item

### ISSUE THREAD

**Issue by skanderbenalaya** [SallyWhitemane/Mograine#280]
**Description:**
Using auctioneer to facilitate the search/sell items, search works fine but the selling function doesn't work, if you post an item and click "create auction" you would get a queue error saying the item couldn't be posted.

**How to reproduce:**
Use auctioneer to create an auction through the sell tab.

**How it should work:**
Creating auction with auctioneer should post items as it's intended to.

**Comment by Kraxit** [comment]
Hello ,
I use auctionner addon and it works as it's intended. 
You need to download correct version of auctioneer addon for Wotlk 3.3.5
[Link](https://legacy-wow.com/wotlk-addons/auctioneer/)  you can try this one.

**Comment by alexspew** [comment]
Addon issue. Closed
