### ISSUE TITLE
[Quest] Mystery of the Infinite

### ISSUE THREAD

**Issue by xaring** [SallyWhitemane/Mograine#283]
**Description:**
Mystery of the Infinite is not working correctly

**How to reproduce:**
Try to place the hourglass, error message pops up.
![image](https://user-images.githubusercontent.com/22470824/105694071-cc783200-5f00-11eb-915e-a907299cafb5.png)

**How it should work:**
https://www.youtube.com/watch?v=5rFGhuJsh3I

**Comment by Pawaox** [comment]
Already did this quest succesfully, you have to be closer to the corpse / bones
