### ISSUE TITLE
Eldon Watcher(shade form) Dephase doesn't work.

### ISSUE THREAD

**Issue by AndreiGameDev** [SallyWhitemane/Mograine#287]
**Description:**
When you have to go in shade form for the quests [From whence they came], [Honor is for the weak], [An Undead's Best Friend] spell number 3  on the action bar is bugged [Dephase] and doesn't get you out of combat.

**How to reproduce:**
Get in combat then use Dephase.

**How it should work:**
Dephase should get you out of combat and make enemies not attack you.

**Comment by alexspew** [comment]
Spell Name : Dephase 
Spell Id : 58543

**Comment by alexspew** [comment]
As I am unable to fix the Dephase spell, i've fixed the Ethernal aura you should gain when entering the shade form instead.
