### ISSUE TITLE
https://wotlk.evowow.com/?quest=13169

### ISSUE THREAD

**Issue by AndreiGameDev** [SallyWhitemane/Mograine#288]
**Description:**
When you feed the hounds that are moving, they won't get fed and just reset back to their orignial position

**How to reproduce:**
attack  one and then try to feed it

**How it should work:**
You should still be able to get it fed even when they are moving.

**Comment by AndreiGameDev** [comment]
Sometimes you can feed them when mooving but they don't fall asleep and just reset back to the original position causing them to be able to be fed again.

**Comment by alexspew** [comment]
NPC Name / NPC ID
Bloody Meat / 31119

Spell Name  / SpellID for credit
Feed Hungering Plaguehound Credit / 58564
