### ISSUE TITLE
Autolearning spells

### ISSUE THREAD

**Issue by lapoki** [SallyWhitemane/Mograine#29]
Hi there,

I noticed that when you learn a spell with ranks from a talent tree it does not level ot it's highest rank when you are 80lv. Maybe it was intended to level as you are leveling but I think it should be auto learned at max level ot it's higher rank considering that you are featuring auto learn spells in the server. Otherwise it's needed to go to a trainer to learn higher ranks. The same issue is when when you swap between talent trees at max level, once you have learned the spell for it's highest rank, when you go back to that talent tree it should be auto learned to it's highest rank. I tried this on priest and mage.

how to reproduce:
go to PTR->Level a class to 80 with ranking spells (pref caster)-> see if it spell from talent tree is auto learned to it's highest rank

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
