### ISSUE TITLE
Taking Wing

### ISSUE THREAD

**Issue by Smoroyet** [SallyWhitemane/Mograine#290]
The quest "Taking Wing" doesn't work https://wotlkdb.com/?quest=11680
I pick up the quest, but can't turn it in

Pick up quest, walk over to Warmage Anzim

You should be able to turn it in

**Comment by alexspew** [comment]
You do have "Salrand's Key" in your bags? If not then you can't turn the quest in (if you deleted it).

Note to devs : Might want to check if quest id : 11679 provides the item 34909 for quest : 11680.

**Comment by Smoroyet** [comment]
I did have it in my bag, i double checked

**Comment by alexspew** [comment]
Hi, this seems to be an old issue. If you still have issues with this quest let me know. I was unable to reproduce the error
