### ISSUE TITLE
Right after mob respawn ,mobs attacking , immediately

### ISSUE THREAD

**Issue by Kraxit** [SallyWhitemane/Mograine#291]
**Description:**

Right after mob respawn ,mobs are attacking immediately .
Even they attack in miliseconds while there are fading to solid condition .
Players has no time for to escape from agro range of a mob when the mob respawn.

**How to reproduce:**

Kill a mob pack , then wait for respawn . And see .

**How it should work:**

This is from WoWwiki : 
When players first enter a new area, and some time ago other players killed many mobs (e.g. to fulfill a quest), the new arrivals may easily be surprised by respawns. This effect is alleviated by the fact that right after a respawn, mobs stand still and do not attack for about 5 seconds. This gives players enough time to move out of the aggro radius, if they react quickly.

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues/195

**Comment by Kraxit** [comment]
#195 has written it 16 days ago , it means it has written before you release the game . 
So, after launch (3 days ago) of the game, if this issue still happens , needed to report it again . 
This is kind of important issue in game play . Also you closed the topic before you fix it . At least close the topics after you release the fix. When people see the closed topic , people think it is fixed . And In the game if they see still it is not fixed , it breakes the trust to the game and devs.  
Also If it will stay like this , at least specify as comment , thus people can understand what is going on .
