### ISSUE TITLE
 Return of the High Chief

### ISSUE THREAD

**Issue by Smoroyet** [SallyWhitemane/Mograine#292]
Boss despawns https://wotlkdb.com/?quest=12069

You click the orb, RP happends, wait for the boss to leap down and despawn.

The boss (Under-king Anub'et'kan) is supposed to leap down and im supposed to fight him. He leaps down but despawns

**Comment by Smoroyet** [comment]
It worked when I tried again
I attacked the boss before he could despawn
And the RP was fucked

**Comment by alexspew** [comment]
Fixed the speed on when he jumps down
Made item party lootable.
Thanks!
