### ISSUE TITLE
ZD Disclosure quest bug

### ISSUE THREAD

**Issue by vkdog** [SallyWhitemane/Mograine#294]
**Description:**
Near end of quest chain for Disclosure in Zuldrak, attempt to go into the upper chamber where the skeleton guides you around the place. 4 spawned for me.. got to the end and didn't complete it just stopped on the spot. 

**How to reproduce:**
Click the coffin in the upper chamber to spawn a skeleton to guide you round. 

**How it should work:**
The skeleton gets to the end of it's path and you should have explored the upper chamber. Once done you should be able to then speak to Drakuru to learn his secret.. 

https://www.youtube.com/watch?v=8dUexGT1ysA like this but the upper chamber secret should be discovered once Malmoris takes you around the upper chamber - not immediately after clicking the coffin

**Comment by alexspew** [comment]
Most likely summons the wrong NPC. 

Correct NPC ID : 28998

**Comment by vkdog** [comment]
https://www.youtube.com/watch?v=8dUexGT1ysA like this but the upper chamber secret should be discovered once Malmoris takes you around the upper chamber - not immediately after clicking the coffin

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
