### ISSUE TITLE
Sons of hodir chain quest bug (The Drakkensryd)

### ISSUE THREAD

**Issue by bojinkata03** [SallyWhitemane/Mograine#295]
there is no mobs around and barely any drakes

**How to reproduce:**

**How it should work:**    there must be a lot of drakes and spawns on mobs so it can be much faster

**Comment by alexspew** [comment]
Quest Name : The Drakkensryd
Quest ID : 12886

Npc Name : Hyldsmeet Drake-Rider Credit
Npc ID : 29800

Lower respawn ?

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
