### ISSUE TITLE
Cold Hearted

### ISSUE THREAD

**Issue by darklord221** [SallyWhitemane/Mograine#299]
**Description:**
Mobs respawn extremely slowly causing a huge bottleneck in a place of this essential wotlk quest line

**How to reproduce:**
accept quest Cold Hearted and try doing it

**How it should work:**
Mobs should respawn faster and drake should move faster.. it flies in slow motion now

**Comment by alexspew** [comment]
Quest Name : Cold Hearted
Quest ID : 12856

Npc Name : Liberated Brunnhildar
Npc ID : 29734

Needs lower respawn time after despawning.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by Fyurie** [comment]
These are still criminally slow. Is the speed correct?

**Comment by Raulfin** [comment]
The drakes always flew pretty slowly under the players control, their movement speed increases when they 'smell home' and ignore the players input for the auto flight portion.
