### ISSUE TITLE
Explosive Trap Crit multiplier irregularities.

### ISSUE THREAD

**Issue by HuntRF** [SallyWhitemane/Mograine#30]
I am just going to shamelessly post a bugtracker post from a different server that was already resolved with all the proof in the world. I am aware the format of my post is irregular but I find it unnecessary to waste time writing it when its all clear in the link.

https://github.com/SunwellTracker/issues/issues/3301

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
