### ISSUE TITLE
Can't inspect other people's talents

### ISSUE THREAD

**Issue by darklord221** [SallyWhitemane/Mograine#300]
**Description:**
When you inspect people's talents you don't see nothing

**How to reproduce:**
Inspect a player

**How it should work:**
You should be able to see their talents

**Comment by Rugsz** [comment]
I just wanted to point out that this issue is causing talented raid CD trackers to be scuffed. Weak Auras or addons that use code to inspect talents to track CDs aren't working properly because we can't confirm the spec of players in a raid. This should be a high priority fix before naxx release.

**Comment by alexspew** [comment]
This is now fixed.
