### ISSUE TITLE
Quest: Bitter Rivals (Dun Morogh)

### ISSUE THREAD

**Issue by Wayran-is-typing** [SallyWhitemane/Mograine#302]
I gave the beer to NPC Jarven for end the event, but the new barrel for complete the quest appear and dissappear to fast

**Comment by alexspew** [comment]
gameobject
object id : 270
spawntimesecs needs to be  -600 so it despawns after 600 seconds instead of 0 seconds.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
