### ISSUE TITLE
[Heroic Dungeon] Halls of Stone - The Tribunal of Ages

### ISSUE THREAD

**Issue by mrnuggets** [SallyWhitemane/Mograine#303]
Decription:

Right now after finishing "the tribunal of ages" encounter you won't get an ID and you can leave and do the boss over and over again.

How it works:

After finishing encounter you get no ID.

How it should work:

Finish encounter and get ID.

Source (you should point out proofs of your report, please give us some source):

Since i just finished the heroic dungeon i don't have anything to provide. Tomorrow i will record a video to show you.

ref: #https://github.com/SunwellTracker/issues/issues/3327

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
