### ISSUE TITLE
Quest: the jig is up ID11471

### ISSUE THREAD

**Issue by kokobedima** [SallyWhitemane/Mograine#304]
Description: The NPC in the cave is unattackable. 

How to reproduce: enter cave try attack npc

How it should work:enter cave, fight npc, get him to 30%, he jumps down a get eaten By bear, kill bear get item.

**Comment by alexspew** [comment]
Npc Name : "Mad" Jonah Sterling
Npc Id : 24742

Npc Name : Hozzer
Npc Id : 24547

Object Name : Jonah Sterling's Spyglass
Object Id : 34128

Enter cave -> Get Jonah down to 30% HP -> Jonah jumps down and wakes up bear(hozzer) -> bear kills Jonah -> 
kill bear (hozzer) -> loot bear get Jonah Sterling's Spyglass from bear.

**Comment by kokobedima** [comment]
Seems like restart fixed the issue

**Comment by Fyurie** [comment]
Not sure why you've closed this, still very much broken.

**Comment by Fyurie** [comment]
Opened a new ticket at #322 so this issue doesn't go unchecked.
