### ISSUE TITLE
greater blessing of sanctuary not auto learned 

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Mograine#306]
**Description:**
since its a improved talent its not on the autolean list

**How to reproduce:**
learn talent blessing of sanctuary and levelup. it doesnt get added automatically

**How it should work:**
add the spell into the auto learn list

**Comment by alexspew** [comment]
Spell Name : Greater Blessing of Sanctuary
Spell ID : 25899
Spell learned at level : 60

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
