### ISSUE TITLE
multiple solid chests in aszhara are respawning every 5min

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Mograine#308]
**Description:**
there are 4-5 solid chests which have a broken respawn timer
1. 17, 69
2. 32, 45
3. 38, 48

just check them all

**How to reproduce:**
tp to the coords and loot the chest, wait a few minutes 

**How it should work:**
chests shouldn't spawn that frequent, i already saw the character "Oilprince" camping one of the chests.

**Comment by alexspew** [comment]
Object Name : Mossy Footlocker
Object ID : 179497

Confirmed to have a respawn rate of 180 seconds. Required by rogues to level up lockpicking, low chance of Citrine.

**Comment by V3n1m** [comment]
I'm speaking of SOLID CHESTS not Footlockers.

**Comment by alexspew** [comment]
> I'm speaking of SOLID CHESTS not Footlockers.

Ah my bad, you didn't say which chest it was.

Object Name : Solid Chest
Object ID : 2850

Should have a respawn timer between 3600 seconds and 7200 seconds.

**Comment by V3n1m** [comment]
i said it multiple times in my report but k
