### ISSUE TITLE
Small Barnacled Clam / Full Inventory 

### ISSUE THREAD

**Issue by Kraxit** [SallyWhitemane/Mograine#311]
**Description:**
 
If your  inventory is full and if you have Small Barnacled Clam (from oasis snapjaw in the barrens) , when you try to open it , it disappers from your bag by a "full inventory" warning . If you have space in bag you can get clam meat normally. Maybe all other type clam loots behave same , you need to test it

**How to reproduce:**

Have a 1 empty space inventory , Kill an oasis snapjaw in the barrens , loot the Small Barnacled Clam , right click it for to take clam meat which is in it. Then see how it disappears.

**How it should work:**

Calam should be opened in loot window with warning about full inventory . when you click cross sign of loot window , Small barnacled Clam should stay in the bag .
Maybe it happens with all clams loot and all loots in box container like that . you need to test them also .

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
