### ISSUE TITLE
Forgotten Depths Slayer

### ISSUE THREAD

**Issue by Hemass** [SallyWhitemane/Mograine#315]
Forgotten Depths Slayer, mob in Icecrown, near the Ardent Vanguard, does way too much damage, it's like 450 damage every 0.2 seconds, almost like a buff that would return damage when damage is taken(ex. Lightning Shield), except there is no buff active on them. Making them almost unkillable. 

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Npc Name : Forgotten Depths Slayer

Npc Id's : 30333 | 30593 | 30673 | 31038

They might have wrong npc id spawning near this area as there are multiple id's.

**Comment by squal123** [comment]
Hits too quickly
![image](https://user-images.githubusercontent.com/78042097/105887509-1bf75480-600c-11eb-8f4a-c20c36e68dd5.png)

**Comment by Raulfin** [comment]
The 'Claw Slash' skill is whats bugged, they are fine till they use it. The skill will deal damage multiple times a second and will never end once used. Did about 14k dmg to me in ~5sec.
