### ISSUE TITLE
mob groups in The Nexus

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Mograine#320]
**Description:**
on the last platform before the 3rd boss there are way to many mobs, usualy there is only a rift + some elementals but here are three more dragonkins on the platform which makes it more difficult

**How to reproduce:**
tp into nexus and take a look

**How it should work:**
usualy there are only elementals + one rift

**Comment by Pawaox** [comment]
As can be seen in the below video, the humanoid creatures are supposed to be corpses/dead:
https://youtu.be/aFCXoPdsE8E?t=295

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
