### ISSUE TITLE
[QUEST] The Jig is Up - Howling Fjord (ID: 11471)

### ISSUE THREAD

**Issue by Fyurie** [SallyWhitemane/Mograine#322]
**Description:**
https://www.wowhead.com/quest=11471/the-jig-is-up

After a certain point (I believe it to be the first completion after each server restart), the mobs required for this quest are alive but flagged as unattackable, making the quest impossible to complete.

**How to reproduce:**
Travel to the quest location. You will likely find Jonah Sterling and his ursine friend there alive but unable to be attacked.

**How it should work:**
Enter cave -> Get Jonah down to 30% HP -> Jonah jumps down and wakes up bear (hozzer) -> bear kills Jonah ->
kill bear (hozzer) -> loot bear get Jonah Sterling's Spyglass from bear.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
