### ISSUE TITLE
Hammer of Wrath

### ISSUE THREAD

**Issue by skanderbenalaya** [SallyWhitemane/Mograine#325]
**Description:**
When you target a dead mob, the popup message for Hammer of Wrath appears on the screen.

**How to reproduce:**
Just kill a mob with a paladin, then keep retargeting it, you will get the message pop as much as you do it.

**How it should work:**
The message shouldn't appear when the target is dead.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
