### ISSUE TITLE
Warriors cannot use fists, why?

### ISSUE THREAD

**Issue by Zka-StarSchema** [SallyWhitemane/Mograine#331]
**Description:**
My lvl 35 draenei prot warrior (Delicatesse) cannot use fist weapons. Unarmed skill is present and maxed.
Weapon I'm trying to use is Bloody Brass Knuckles.

**How to reproduce:**

**How it should work:**
It should work :)

**Comment by alexspew** [comment]
Spell Name : Fists Weapons
Spell ID : 15590

Should be learnable for Warriors at level 10.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
