### ISSUE TITLE
Zul Drak quest Sabotage

### ISSUE THREAD

**Issue by squal123** [SallyWhitemane/Mograine#333]
**Description:**
Skeleton Malmortis stops in the 3rd part of the quest Learn Drakuru's secret. Many players have same issue. Cant restart/end q. 

**How to reproduce:**
After clicking on box skeleton starts walking. Before first stairs skeleton is standing next to the stairs with other stacked skeletons.

**How it should work:**
Skeleton should go down and after some talking end walking in the middle of the room,

**Comment by squal123** [comment]
![image](https://user-images.githubusercontent.com/78042097/105886136-52cc6b00-600a-11eb-869e-bd9510b8677c.png)

**Comment by alexspew** [comment]
Fixed few weeks ago, from changelog. Fix for Disclosure Quest: player may summon only one Malmortis now.
