### ISSUE TITLE
Quest [A Delicate Touch] [Storm Peaks] bugged

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#334]
**Description:**

You're supposed to place mines to kill the Garm Attackers. if they die by mines [Improved Land Mines] they should die and give kill credit. however on Whitemane currently the only way you can get the kill credit is to just attack and kill them normally this is not intended.

**How to reproduce:**
Place mines near Garm Attacker mobs near K3 and check if you get kill credit

**How it should work:**
You should get kill credit from the mines exploding them not you attacking them

**Comment by alexspew** [comment]
Quest Name :  A Delicate Touch
Quest ID : 12820

Object Name : Improved Land Mines
Object Id : 40676

Object missing kill credit for quest?

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by Fyurie** [comment]
![mobs going wrong way](https://puu.sh/HaQYl.jpg)

A new bug has appeared, it seems.

**Comment by Vanroden141** [comment]
Seems this quest is bugged again, Mobs are spawning inside and around K3, Stormpeaks. Some stand still while some run towards garms bane where they should spawn. luckily we can still kill for quest credit

**Comment by xouved** [comment]
still not working, the mob are spawning randomily at the underground and charging the at the wrong way.
