### ISSUE TITLE
[Spell bug] Cannot cast death grip while jumping, falling, etc.

### ISSUE THREAD

**Issue by sicknot1** [SallyWhitemane/Mograine#335]
**Description:**
Cannot cast death grip while jumping, falling, etc.

**How to reproduce:**
Target and try to cast Death Grip while in the air/ jumping

**How it should work:**
Instant spell should be able to be casted while jumping

**Comment by SallyWhitemane** [comment]
http://web.archive.org/web/20160310135709/http://www.arenajunkies.com/topic/63834-deathgrip/
