### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by ohcan27** [SallyWhitemane/Mograine#337]
**Description:* Quest: "Elixir of Suffering"
"Gray Bear Tongue"     (0/10)
"Creepe Ichor"             (0/01)

**How to reproduce:**
Doesn´t drop the "Creepe Ichor"

**How it should work:**

Mob "Forest Moss Creeper's" should drop it

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
