### ISSUE TITLE
Becoming a Spellfire Tailor - Not Working

### ISSUE THREAD

**Issue by BruunHero** [SallyWhitemane/Mograine#339]
**Description:**
The Nether-wraith Beacon does NOT summon the quest mob, making it impossible to complete the quest.

**How to reproduce:**
Attempt to use Nether-wraith Beacon in Netherstorm.

**How it should work:**
It should summon a quest mob. There are no other requirements for this than simply using the quest item in Netherstorm.

https://www.wowhead.com/quest=10832/becoming-a-spellfire-tailor

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by alexspew** [comment]
Item name : Nether-wraith Beacon
Item Id : 31742

Quest name : Becoming a Spellfire Tailor
Quest Id : 10832

Spell Name : Activate Nether-wraith Beacon
Spell Id : 39105

Spell should spawn following : 

Spell Name : Serverside - Summon Furious Nether-wraith
Spell Id : 39111

Npc Name : Furious Nether-wraith
Npc Id : 22408
