### ISSUE TITLE
A/H and Viewing Talents On Others.

### ISSUE THREAD

**Issue by Ochikanda** [SallyWhitemane/Mograine#340]
When making a auction on the a/h it makes the buyout and bid price like 10x higher than when I put it. I thought it was just a issue with me but I asked others and they said they had the problem too.

Another issue I found was when you inspected someone and clicked on their talents, they just dont show up lol. Dont know if the server implemented this on purpose or not but if not, would love for it to be fixed.

**Comment by alexspew** [comment]
Invalid. Please follow our report form for reporting issues thanks!
