### ISSUE TITLE
Totem of Wrath 3% crit debuff not appearing on enemies

### ISSUE THREAD

**Issue by sefamurat** [SallyWhitemane/Mograine#341]
**Description:**
Totem of Wrath 3% crit debuff is not appearing on enemies debuff slots. Could be a visual bug, or could be that the debuff isn't applied at all.

**How to reproduce:**
Put a Totem of Wrath 40 yards within an enemy.

**How it should work:**
Enemies in range of Totem of Wrath should have a debuff on them.

**Comment by alexspew** [comment]
Spell Name : Totem of Wrath (Rank 1)
Spell Id : 30706

Applies following spell auras when casted :: 

Spell Name : Totem of Wrath
Spell Id : 57658

Spell Name : Totem of Wrath
Spell Id : 30708

Both have 40 yard range from totem.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by cocojumbo321** [comment]
![image](https://user-images.githubusercontent.com/78087259/106272251-07e06c80-6231-11eb-8947-c82762f1d1a1.png)

not working...yd it worked today its buged again
