### ISSUE TITLE
PvP BUG - Disengage and Death Grip interaction

### ISSUE THREAD

**Issue by Docent-hunter** [SallyWhitemane/Mograine#343]
**Description:**
When DKs use DeathGrip and hunter use Disengage while griped, it eat hunter´s disengage cooldown but you are still griped to DK.

**How to reproduce:**
--

**How it should work:**
When DKs use DeathGrip and hunter use Disengage while is griped, hunter should be disengaged away from dk. ( That is how it works on warmane, and how it should work in general)

**Comment by Jamiexdx** [comment]
Can confirm that this is how the interaction should work

**Comment by Docent-hunter** [comment]
Also death-grip pull speed is unaturaly too fast, it should be slower.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
