### ISSUE TITLE
Druids not autolearning fist weapons

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#344]
**Description:**
Druids aren't autolearning first weapons (they should) - they use raid weapons such as [Wraith Strike] as their ''achievable bis'' during T7.

**How to reproduce:**
Make it a druid .ding to 80 and see if it learns fist weapons

**How it should work:**
Druids should learn it by default

**Comment by alexspew** [comment]
Druid learn fist weapons at lvl 10.

Spell Name : Fists Weapons
Spell Id : 15590

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
