### ISSUE TITLE
 Rouges quest [Destiny Calls], the quest item doesnt drop 

### ISSUE THREAD

**Issue by Lexri** [SallyWhitemane/Mograine#345]
**Description:**

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Quest Name : Destiny Calls
Quest Id : 2242

Item Name : Sethir's Journal
Item Id : 7737

Item is pickpocketed from mob ::

Npc Name : Sethir the Ancient
Npc Id : 6909

**Comment by alexspew** [comment]
Invalid. Item is there on mob
