### ISSUE TITLE
[Foolish Endeavors (H)] Bug

### ISSUE THREAD

**Issue by MoonZapdos** [SallyWhitemane/Mograine#347]
**Description:** The quest bugs out if anyone or anything interacts with Varidus the Flayer before the RP commences between Getry and him.

**How to reproduce:** Literally just have anything or anyone go near or attack Varidus after accepting the quest.

**How it should work:** I'm pretty sure Varidus is not meant to be interactible until the RP is concluded.

**Comment by alexspew** [comment]
Quest Name : Foolish Endeavors
Quest Id : 11705

Npc Name : Varidus the Flenser
Npc Id : 25618

**Comment by alexspew** [comment]
Fixed on next server restart.
