### ISSUE TITLE
Heavy Netherweave Bandage

### ISSUE THREAD

**Issue by Raulfin** [SallyWhitemane/Mograine#348]
**Description:**
Heavy Netherweave Bandage is learned at skill 330.

**How it should work:**
Heavy Netherweave Bandage should be learned at skill 360.

**Comment by alexspew** [comment]
Incorrect, post 3.2 it changed to be learned at Aresella/Burko at 330 skill.

**Comment by Raulfin** [comment]
Ahh kk, the item texts list 360.
