### ISSUE TITLE
Minor bug - naxx graveyard

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#35]
Description: naxx graveyard is badly implemented into Venomspite, it should be nearer naxx in front of statue at these coordinates
![WoWScrnShot_111220_105514](https://user-images.githubusercontent.com/52035924/98925082-df6c9000-24d5-11eb-9981-39ed1420b39e.jpg)
How to reproduce: die in naxx
How it should work: proof is on this old stream from original wotlk
[Link](https://www.twitch.tv/videos/47162138?t=0h4m4s)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
