### ISSUE TITLE
sons of hodir

### ISSUE THREAD

**Issue by lucario201** [SallyWhitemane/Mograine#350]
After finish a quest "A Spark of Hope" my reputation decreased to hated with 22000.

https://gyazo.com/780aa19d2b21dd8e84dc4e891db6c185

after finish that quest my reputation should be honored im not sure its a bug or what

nick : Desmond

**Comment by Raulfin** [comment]
Sounds like you forgot to pick up one of two quests while doing Mending Fences (pick up the rocks and throw them at 5 giants and the giant by the anvil). Completing Mending Fences will give you 22k rep and leave you in the middle of Hated.
While killing the 5 giants they will drop a quest starter item to kill 10 of the elements and turn in at the anvil. the anvil then gives a follow up quest, A Spark of Hope, to go to Thorim, turning this in will give another 28.6k rep, leaving you 400 short of honored, and give the quest 'Forging an Alliance' to start building rep normally.

Seems you need to turn in 'Mending Fences' before 'A Spark of Hope' is available at the anvil.

**Comment by alexspew** [comment]
Hello! Please follow our proper report forms for posting issues, thanks!
