### ISSUE TITLE
Character getting stuck constantly in Valley of Echoes in Icecrown

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#354]
**Description:**
I was running around Valley of Echoes on my Elekk and I would randomly get stuck and start falling on the spot. Relog fixes it but it would happen a few steps later.

**How to reproduce:**
Mount up (possibly on foot as well) and move around the Valley of Echoes near the tunnel towards Scourgeholme in Icecrown.

**How it should work:**
I should not be getting stuck.

**Comment by Tonneff** [comment]
Can confirm, i got stuck while flying and had to restart client. i also got stuck in a tent with a npc falling endlessly
