### ISSUE TITLE
Quest : Samophlange - The Barrens 

### ISSUE THREAD

**Issue by Kraxit** [SallyWhitemane/Mograine#356]
**Description:**

Quest : Samophlange - The Barrens  , when you reach to the control console (52.40 - 11.65 coordinate) you click and you see quest window . You click complate quest button but anyhow quest window not get closed . You need to close quest window by clicking X on quest window or escape button on keyboard .
All serie of that quest has same issue . Quest window not getting closed after complating quest . It still keep quest window open which has complate quest button .

**How to reproduce:**
 Take quest and go to control console and click it for to complate quest . And click complate quest button on the quest window .

**How it should work:**
After clicking complate button , quest window also should get closed . and if there is chain quest, new quest window should get open automatically .

**Comment by alexspew** [comment]
Quest works fine, no fix needed.
