### ISSUE TITLE
Mount not working in Iron Forge.

### ISSUE THREAD

**Issue by Mightiecake** [SallyWhitemane/Mograine#357]
**Description:**
Flew into Iron forge. When I landed I couldn't mount up anywhere in Iron Forge.

**How to reproduce:**

**How it should work:**

**Comment by Tonneff** [comment]
If i am not wrong this is caused by the client with updated models, Totally not server side fault, but i might be wrong

**Comment by Mightiecake** [comment]
Personally I've never had a problem on other servers with updated  models.

**Comment by Tonneff** [comment]
http://forum.warmane.com/showthread.php?t=352628

In this thread they talk about the exact bug you have. I also read the other bug you posted (insta dismount) and they talk about it too.
Mount problems are only caused by gnome mount by the way, are you a gnome?

**Comment by alexspew** [comment]
Issue is related to Modern Client with updated models. Invalid
