### ISSUE TITLE
The Last Line of Defense quest zone and turrets are buggy

### ISSUE THREAD

**Issue by urban9** [SallyWhitemane/Mograine#359]
**Description:**
Like the title says, when you try to leave the quest zone without completing it, you get stuck in an invisible sandbox and you get stuck mid-air. When you try hearthstone you get bugged out mid-air but you can fix this by closing and reopening the game. And also turrets which you need to kill icy dragons and undead there, can be used to kill players. Nearly one shotting anyone.

**How it should work:**
Turrets should not damage anyone and should only be used for mobs not pvp. And you should be able to leave the quest zone without any harm or so.

Video proof: https://www.youtube.com/watch?v=0YJ-vpudJ9c&feature=youtu.be ( File was too big so i had to upload to youtube)

Also i didnt record the "cant leave the quest zone" bug, but you i hope you understand what i mean by that.
Thank you.

**Comment by alexspew** [comment]
Hi, thanks! Fixed
