### ISSUE TITLE
Visualize improvement - Quest [Patching Up]

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#36]
Description: After completing quest [Patching Up] goblin starts little scenario with his flying machine. Pathing and dialogs are ok, but movement visualization looks bad. Like a bunny-hopping in air instead of flying.

How to reproduce: Complete quest [Patching Up]

How it should work: Like on this video, but as i said. Only movement visualization needs fix.
[video](https://youtu.be/OAXV6u7stqE?t=130)

P.S: I don't know if it's just this quest or some general implementation of flying npc's movement. But if general movement, that fix will be great for flying bosses etc.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
