### ISSUE TITLE
Resurrections Sickness 

### ISSUE THREAD

**Issue by NPC69** [SallyWhitemane/Mograine#361]
**Description:**
Resurrection sickness' remaining time pauses with logging off.

**How to reproduce:**
Fix it.

**How it should work:**
The time remaining should go off whether or not the user is logged in.

**Comment by Jamiexdx** [comment]
Nope

**Comment by Kraxit** [comment]
hello. 11 days passed . fix it guys .

**Comment by cachocarne** [comment]
Still not fixed. You can log out for days and still, when you log back, you will have the remaining debuff timer.
