### ISSUE TITLE
Disclosure quest in Zul'Drak

### ISSUE THREAD

**Issue by TwiceWarrior** [SallyWhitemane/Mograine#362]
**Description:**
I can't seem to finish Disclosure quest in zul'drak, and when i redo the quest i can't summon the skeleton guide

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Fun fact : This quest was one of the most bugged quests on retail. They broke it after each patch

Quest Name : Disclosure
Quest Id : 12710

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
