### ISSUE TITLE
Warlock Imp's Fire Shield Spell

### ISSUE THREAD

**Issue by kyler3133** [SallyWhitemane/Mograine#363]
**Description:**
Warlock's version of thorns pretty much, it autobuffs everyone in your party and refreshes it when the effect ends, but doesn't do the same on the warlock.

**How to reproduce:**
You have to target yourself and buff it manually every 3 minutes, which is annoying.

**How it should work:**
Imp should autobuff you in the first place himself, and refresh it when it ends.

**Comment by alexspew** [comment]
Spell Name : Fire Shield (Rank 1)
Spell Id : 2947

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
