### ISSUE TITLE
Druid - Mangle

### ISSUE THREAD

**Issue by pinkisnotgay** [SallyWhitemane/Mograine#364]
**Description:**
After unlocking Mangle (Rank1) the game doesn't automatically learn new ranks.

![obraz](https://user-images.githubusercontent.com/44933866/105991036-98894200-60a3-11eb-8222-d3f7572d579a.png)

**Comment by alexspew** [comment]
Spell Name : Mangle (Cat) Rank 1
Spell Id : 33876


Spell Name : Mangle (Bear) Rank 1
Spell Id : 33878

Requires talent check for auto learn(?)

**Comment by Raulfin** [comment]
Mangle (33917)? is the lvl 50 talent in the Feral Combat tree that is required for ranks 2-5. The talent requires 1 point in Leader of the Pack to unlock.
The talent grants both Mangle (Cat) Rank 1 and Mangle (Bear) Rank 1.

**Comment by cachocarne** [comment]
I can confirm these ranks are not auto-learned. Found out when clicking on a trainer just by chance.
![ 2021-01-30 at 01 25 54](https://user-images.githubusercontent.com/77953030/108847220-82ae6480-75f0-11eb-8b5f-544bb6f0ffc7.png)
![ 2021-01-30 at 01 26 01](https://user-images.githubusercontent.com/77953030/108847227-85a95500-75f0-11eb-9a5c-94dfd0532018.png)

**Comment by sorcererer** [comment]
![image](https://user-images.githubusercontent.com/15989840/114622779-16c6af00-9cb7-11eb-9f85-213cf7f58976.png)
like many other noob dudus, I was shocked to see that my mangle has been r1 the entire time :D but now that I needed swift flight form, I learned all of the ranks.

This won't take long to fix xd
