### ISSUE TITLE
Shaman talent totem of wrath does not apply 3 % crit chance debuff on enemies

### ISSUE THREAD

**Issue by cocojumbo321** [SallyWhitemane/Mograine#366]
**Description:*Shaman talent totem of wrath does not apply 3 % crit chance debuff on enemies*

![image](https://user-images.githubusercontent.com/78087259/105994653-341cb180-60a8-11eb-96fa-e35cd3a93c8b.png)
 

![image](https://user-images.githubusercontent.com/78087259/105994862-7ba33d80-60a8-11eb-8b17-fd7cb888bbec.png)

It should apply debuff on enemies shown as aura

![image](https://user-images.githubusercontent.com/78087259/105995169-e9e80000-60a8-11eb-81cf-606f32957d55.png)

this is an example of how it should be shown on enemies

**Comment by alexspew** [comment]
Replica of https://github.com/SallyWhitemane/Mograine/issues/341

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by cocojumbo321** [comment]
![image](https://user-images.githubusercontent.com/78087259/106272931-2004bb80-6232-11eb-84cb-2f02f5435133.png)
 
worked yd today its buged again
