### ISSUE TITLE
Spelltext in actionbars do not show up

### ISSUE THREAD

**Issue by mailtheman** [SallyWhitemane/Mograine#367]
**Description:**
When i mouse over any of my skills only spell name and rank are visable. no spell text or mana costs. this is the same for all my characters. verything works in the spellbook.
![Skärmbild 2021-01-27 143153](https://user-images.githubusercontent.com/78088599/105997946-70521100-60ac-11eb-8e22-4623ee49cd0c.png)

**How to reproduce:**

**How it should work:**

**Comment by Penthax** [comment]
you turned off Enhacned Tooltipps ?

**Comment by mailtheman** [comment]
I am Officialy an idiot ty
