### ISSUE TITLE
[Quest] Generosity Abounds

### ISSUE THREAD

**Issue by Grzegorz-Kolaty** [SallyWhitemane/Mograine#368]
**Description:**
Picking up quest should autimatically transform me in undead so I can touch objects.

**How to reproduce:**
Just pick Quest and u will see.

**How it should work:**
Here is a video.
https://youtu.be/kwhA01aCSjM

**Comment by alexspew** [comment]
Quest Name : Generosity Abounds
Quest Id : 13146

Object Name : Eye of Dominion
Object Id : 193424

Missing 2 spells(?)

Spell Name : Forcecast: Control Lithe Stalker
Spell Id : 58106

Spell Name : Control Lithe Stalker
Spell Id : 58037

**Comment by alexspew** [comment]
Quest works fine, remember to click on Eye of Dominion a bit behind the npc.
