### ISSUE TITLE
[quest] get to getry (borean tundra) hord quest bugged, nbpc stuck downstairs

### ISSUE THREAD

**Issue by Metasaigneur** [SallyWhitemane/Mograine#369]
**Description:**
getry is stuck downstairs

**How to reproduce:**
?

**How it should work:**
getry should be doing siomething; and be on top of tower to interact with

**Comment by alexspew** [comment]
Quest Name : Get to Getry
Quest Id : 11703

Npc Name : Shadowstalker Getry
Npc Id : 25729

**Comment by alexspew** [comment]
Duplicate -> https://github.com/SallyWhitemane/Mograine/issues/449
