### ISSUE TITLE
Dismount in captials

### ISSUE THREAD

**Issue by Mightiecake** [SallyWhitemane/Mograine#371]
**Description:**
Getting dismounted when trying to mount in capital cities

**Comment by jan-varga** [comment]
for me not only in cities, elsewhere too. Sometimes it works though. Also: I was in Shattrath and couldn't mount up ground mount, but i flying mount worked. There are certain areas in cities that prevents mounting up.

**Comment by alexspew** [comment]
Issue is related to "Modern Client" with updated models, please change clients if possible.
