### ISSUE TITLE
[Quest][Northrend] Cutting Off the Source - Missing eggs

### ISSUE THREAD

**Issue by wesliel** [SallyWhitemane/Mograine#372]
**Description:**
[Quest description](https://mmo4ever.com/wow/quest.php?id=11602)
Players are required to destroy 10 egg sacs, but these are not found anywhere.

**How to reproduce:**
Acquire the quest, go around the quarry, no egg sacs.

**How it should work:**
Egg sacs should spawn throughout the quarry to be destroyed.

For developers: I have found the same issue on another private server, might be a TrinityCore issue. [Here's the ticket](https://github.com/dalaranwow/dalaran-wow/issues/4002).

**Comment by alexspew** [comment]
Quest Name : Cutting Off the Source
Quest Id : 11602

Object Name : Nerub'ar Egg Sac
Object Id : 187655

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
