### ISSUE TITLE
[quest] matis the cruel id:9711

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#376]
**Description:**
you are provided a quest ite "flare gun" id:24278 the item could be used by mistake which makes the quest uncompletable, suggestion: add a option to speak with the quest giver and receive the quest item. 
npc is named "Vindicator Kuros" and his id:17843

**How to reproduce:**

**How it should work:**

**Comment by ghost** [comment]
mm yes i had a problem with that quest too, very nice suggestion!

**Comment by alexspew** [comment]
Invalid. If you've used the item by mistake, abandon the quest and take it again.
