### ISSUE TITLE
[quest] razormaw id:9689

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#377]
**Description:**
you are provided with quest item "Bundle of Dragon Bones" id:24221
the quest item is used to summon the npc that needs to be killed
if the quest is taken on low level characters the summoned npc is very likely to kill you
the grave is far away and the summoned npc despaws by the time you get to your corpse
upon using the quest item, the quest item is consumed and the npc cannot be summoned second time
suggestion: add a option to speak with the quest giver and receive second quest item to summon the npc
quest giver "Prince Toreth" id:17674 

**How to reproduce:**

**How it should work:**

**Comment by ghost** [comment]
ah, i wiped at that fight too and couldnt summon the npc second time, would be great if there was a way to resummon it! your suggestion is on point bro!

**Comment by alexspew** [comment]
Invalid. This is a group quest, it's not meant to be solo'd, if you fail the quest, abandon the quest and take it again.
