### ISSUE TITLE
[quest] Dahlia's Tears id:192773

### ISSUE THREAD

**Issue by blackouths** [SallyWhitemane/Mograine#378]
**Description:**
Dahlia's Tears don't seem to be spawning in Dragonblight after a Ruby Watcher kills an undead on the grassy patch.

**How to reproduce:**
50.4, 52.1 coords in Dragonblight.

**How it should work:**
Dragon should kill undead, flowers spawn on grassy patch which are looted by player.

**Comment by alexspew** [comment]
Dahlia's Tears have fixed spawn locations around the area.
