### ISSUE TITLE
Quest - Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by weldim** [SallyWhitemane/Mograine#382]
**Description:**
I do not receive the Nas NPC.  when asking the npc to give me another one I am not presented with one.  Have dropped quest and am still not given Nas

**How to reproduce:**
Accept quest or ask for a new Nas

**How it should work:**
Nas should accompany you at the start of the quest, and you should be able to get a new one from the npc if you lose him.

**Comment by alexspew** [comment]
Quest Name : Kickin' Nass and Takin' Manes
Quest Id : 12630

Npc Name : Nass
Npc Id : 28521

Spell Name : Summon Nass
Spell Id : 51865

Quest is not summoning Nass

**Comment by Fixetza** [comment]
Have in mind that if you are mounted you won't get a Nas NPC. You have to be unmounted to get one currently. I am not sure if it's a bug or not (can't find any proof that it is or isn't)

**Comment by alexspew** [comment]
Quest works fine, Nass spawns and what Fixetza said, you won't get Nass if you are mounted (if you lost him and clicking to spawn a new Nass)
