### ISSUE TITLE
[Quest] Scourgekabob

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#383]
**Description:**
[Scourgekabob](https://wotlkdb.com/?quest=12484)
The 3 troll mummies close to Prigmon can't be looted for the quest item needed to procced in the quest.

**How to reproduce:** 
Grab the quest and try.

**How it should work:**
You should be able to loot the 3 mummified trolls that is around Prigmon they should give you [Scourged troll mummy](https://wotlkdb.com/?item=38149) which you should then use on the fire by Mack Fearsen to complete the quest.

**Comment by alexspew** [comment]
Object Name : Scourged Troll Mummy
Object Id : 190223

Should always contain Scourged Troll Mummy when looted while player has quest.

**Comment by alexspew** [comment]
Object works fine, there is no loot if you've already looted it once.
