### ISSUE TITLE
Quest Gaffer Jacks [1579]

### ISSUE THREAD

**Issue by Bluecow941** [SallyWhitemane/Mograine#385]
**Description:**
Despite of where you're fishing for q items: rocks, docks, shore, on island, north of Auberdine, nowhere quest item drops(or it's drastically low that there is no chance to complete this quest at normal pace).

**How to reproduce:**
Fish in quest zone for some time then look for any quest items in bag (But no quest item dropped....)

**How it should work:**
Fishing in ocean around Auberdine should have a decent loot chance when having quest Gaffer Jacks to drop quest item [6717] in order to get 8 of them so you can complete this quest.

**Comment by alexspew** [comment]
Quest Name : Gaffer Jacks
Quest Id : 1579

Item Name : Gaffer Jack
Item Id : 6717

Requires 30 or more in Fishing to accept quest. Should be around 18-20% drop rate while fishing in Darkshore while having this quest accepted in player quest log.

**Comment by alexspew** [comment]
Hello! A fix is under way, it didn't get fixed in the fishing world update, however I went back and fixed it. Should be live within a few days.
