### ISSUE TITLE
Last Rites (Quest)  bugged. Valanar shows up twice.

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#386]
**Description:**
The mob you have to kill for Last Rites shows up twice (Valanar).
If you kill the wrong one you get no quest credit

**How to reproduce:**
Teleport there

**How it should work:**
One guy should be present

**Comment by Jamiexdx** [comment]
He also moves away and evades after the RP instead of attacking

**Comment by Jamiexdx** [comment]
Therassian also does not assist you in killing  him making this quest harder than it should be

**Comment by alexspew** [comment]
Quest Name : Last Rites
Quest Id : 12019

Npc Name : Therassian
Npc Id : 26170

Npc Name : Prince Valanar
Npc Id : 25601

**Comment by alexspew** [comment]
Duplicate removed
