### ISSUE TITLE
Rejuvenation Talent bugged

### ISSUE THREAD

**Issue by Nabilac1** [SallyWhitemane/Mograine#387]
The spell "Rejuvenation" (druid) doesnt get affected by the "Nature´s Splendor" (plus 3 seconds duration in the Balance tree).
It will remain on 15 seconds instead of having a duration of 18 seconds.
But the tooltip on Rejuvenation says "18 seconds duration" after skilling into Nature´s Splendor.

After skilling into "Nature´s Splendor" the duration from "Rejuvenation" should be 18 seconds.

I tried it now with different groups in 5m hcs and even logged of and back on, but it doesnt change.

**Comment by Jamiexdx** [comment]
I've been getting 18 seconds just fine. you may be running rapid rejuv glyph?

**Comment by Nabilac1** [comment]
Yes, I'm running the rapid rejuvenation glyph.
But shouldn't it still be 18 seconds duration then and only the ticks are faster?

**Comment by Jamiexdx** [comment]
No rapid rejuv  ticks make the ticks go faster but the duration shorter.

**Comment by Nabilac1** [comment]
Ty mate, didn't know that, I will delete this report then! Have a good day!
