### ISSUE TITLE
[Quest] The Force of Neltharaku

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#39]
Description: [Quest] [The Force of Neltharaku](https://www.wowhead.com/quest=10854/the-force-of-neltharaku).
When you use the [Enchanted Netervine Crystal](https://wotlkdb.com/?item=31652) on a [Enslaved Netherwing Drake](https://wotlkdb.com/?npc=21722) you get 1 freed drake when the dragon is hit and after you help it fight against the orcs it runs back to it's "starting point" and do the thing it did before, standing or lying. When it walks in the air you get an additional freed Drake. 

How to reproduce: [Quest] [The Force of Neltharaku](https://www.wowhead.com/quest=10854/the-force-of-neltharaku) Use the quest item: [Enchanted Netervine Crystal](https://wotlkdb.com/?item=31652) on a [Enslaved Netherwing Drake](https://wotlkdb.com/?npc=21722) 

How it should work: You should only get 1 freed after you have helped it fight the closest orc/-s and it flies away.
https://www.wowhead.com/quest=10854/the-force-of-neltharaku#comments wowhead comments on the quest.
The drake should also fly away not walk in the air away.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
