### ISSUE TITLE
The Ring of Blood's second to last quest doesn't give you credit

### ISSUE THREAD

**Issue by Dryhqt** [SallyWhitemane/Mograine#391]
**Description:**
we tried to kill the required mob (warmaul champion) and it does not give you the credit for the kill. We contacted a gm and he could help either

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Unable to reproduce. Did quests multiple times, please try again. If you still have issues with these quests, contact me on discord (alexs) thanks!
