### ISSUE TITLE
The Sons of Hodir interact error

### ISSUE THREAD

**Issue by RobesCarlos** [SallyWhitemane/Mograine#395]
**Description:**
After taking the following quests, I cant complete them ,because there is no way to interact with NPCs. My player can only hit them, but cant open any interaction panel.

- Whatever it takes!
- Diametrically Opposed
- Raising Hodir's Spear

It could be a layering issue.

**How to reproduce:**
Taking the above mentioned quests or some of them. I took them together, so I am not sure, if all of them or only some of them causing the problem.

**How it should work:**
Normally the player could not hit them by right clicking on them.

**Comment by styxel** [comment]
Check rep tab if u have "at war" or smthing like that selected.

**Comment by RobesCarlos** [comment]
Thank you! That was the case.
