### ISSUE TITLE
Mimicking Nature's Call Quest 

### ISSUE THREAD

**Issue by Zeekheart** [SallyWhitemane/Mograine#397]
**Description:**
Blowing the Horn at the Frozen Waterfall has no effect

**How to reproduce:**
Blow the horn at the waterfall 

**How it should work:**
Should spawn a yeti to kill for the quest

**Comment by Zeekheart** [comment]
quest=11281

location Howling Fjord

**Comment by alexspew** [comment]
Hi!, this quest fixed a few weeks ago.
