### ISSUE TITLE
Val'anyr, Hammer of Ancient Kings not activating

### ISSUE THREAD

**Issue by Pepegun** [SallyWhitemane/Mograine#4]
Description: 
Hammer of Val'anyr was proccing off heals prior to the most recent reset on 11/8 (Server). 

How to reproduce:
Healing on a holy paladin does not seem to produce the proc activating.

How it should work:
The way this works is that when the proc happens (which is a 10% chance whenever a hot or direct spell heals, with a 45 sec internal cooldown) you gain a buff (the Blessing) on yourself. Now all of your heals for the next 15 sec cause an 8 sec damage shield. The shield stacks with itself. It includes healing done by subsequent ticks of existing hots on the target. Note that the spell has to actually heal, so hots ticking on a fully-healed target cannot cause the proc. However the shield is based on the size of the heal itself, not the amount healed – i.e. 100% overhealing will not proc the Blessing on the healer, but the shield itself includes overhealing once the Blessing is active. The shield can grow to a maximum size of 20,000 damage absorbed.

**Comment by Pepegun** [comment]
Update: Proc only seems to activate in combat. While this isn't necessarily much of an issue, it was working fine prior to the update when this ticket was made.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
