### ISSUE TITLE
[Spells] Warlock mount not auto-learned.

### ISSUE THREAD

**Issue by AugustFloden** [SallyWhitemane/Mograine#40]
**Description:**
Warlocks do not auto-learn mount the same way as paladins are doing.
**How to reproduce:**
Get to level 20 as a warlock (blood-elf and you will not learn the mount-skill but all other skills.
**How it should work:**
Warlocks should be able to train level 20 mount at their trainer, and with whitemane's autolearn of spells to tackle economy on 5x rates, they should auto-learn mount like paladins (which do work on this server).
Cheers!

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
