### ISSUE TITLE
Zul'Drak Quests: Disclosure and Sabotage

### ISSUE THREAD

**Issue by relinkosed** [SallyWhitemane/Mograine#405]
**Description:**
The quest Disclosure (https://wotlkdb.com/?quest=12710) requires you to enter the upper chamber of Drakuru and click the casket, from which a skeleton named Malmortis appears and gives you a tour of the upper chamber and is suppose to walk you to the green teleporter in the middle at the end and thus completing the quest, but the skeleton Malmortis bugs out and stops moving at a certain point but his dialogue continues to the end, and the quest does not finish, and with it Sabotage (https://wotlkdb.com/?quest=12676) cannot be finished which requires you to finish Disclosure. https://i.imgur.com/SvfQV7m.png

**How to reproduce:**
Enter the upper chamber, and right click the coffin in front of you, then follow the skeleton Malmortis until he bugs and stands still 

**How it should work:**
Malmortis is suppose to escort you to the middle part with the portal, finish dialogue and bow to you, at which point the quest is finished. https://www.youtube.com/watch?v=KbpfXX3E_H8

**Comment by Duttycyat** [comment]
I'm also getting this bug 
![image](https://user-images.githubusercontent.com/78172805/106186423-a362d600-617a-11eb-875f-3a8a04475436.png)

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
