### ISSUE TITLE
[Quest] Northern pylons in ungoro.

### ISSUE THREAD

**Issue by AugustFloden** [SallyWhitemane/Mograine#41]
**Description:**
The pylon quests in Un'goro do not work. When interacting with the pylons, they do not complete their respective quests.
**How to reproduce:**
https://wotlk-twinhead.twinstar.cz/?quest=4285 is a good example, get this quest and go to the said pylons and you wont be able to complete it.
**How it should work:**
Interacting with the pylon should complete the quest.
Cheers!

**Comment by Josarth** [comment]
If im not wrong i completed all the pylons quest's with my paladin

**Comment by AugustFloden** [comment]
@Josarth Okay, this video is few days old but heres how it looked for me.
https://www.youtube.com/watch?v=A2bwla26xV4&feature=youtu.be

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
