### ISSUE TITLE
[Quest][Northrend] The Thane of Voldrune

### ISSUE THREAD

**Issue by Aelysin** [SallyWhitemane/Mograine#415]
**Description:**
On [The Thane of Voldrune] quest, the https://www.wowhead.com/npc=27292/flamebringer npc doesn't spawn

**How to reproduce:**
1. take the quest
2. travel to where the https://www.wowhead.com/npc=27292/flamebringer npc should be
3. it's missing

**How it should work:**
https://www.wowhead.com/npc=27292/flamebringer should be spawned

**Comment by alexspew** [comment]
Npc is there, not missing. If the npc is missing again in the near future, please make a gm ticket / report it on github again thanks!
