### ISSUE TITLE
[Quest][Icecrown][Watts My Target]

### ISSUE THREAD

**Issue by xouved** [SallyWhitemane/Mograine#416]
Hi,

**Description:**

https://www.wowhead.com/quest=13381/watts-my-target

this quest is impossible since we can't shield the plane properly. Each time a ennemie deals dammages, the shield stay intact, and the plane take a lot of dammage. You can't go through the all flight and kill the frostbrood sentry to finish the quest.

**How to reproduce:**
take the quest, take the plane try to go to the frostbrood sentry, you won't be able to go there since you can't shield properly .

**How it should work:**

if you can shield, the plane won't explose and you will be able to end this.

Thanks a lot
Regards,
Xouv

**Comment by alexspew** [comment]
Quest Name : Watts my Target
Quest Id : 13381

Npc Name : Alliance Infra-green Bomber
Npc Id : 31406

Missing Regen in flags?

**Comment by xouved** [comment]
I don't think there is any flags,

The plane should be able to shield himself, but each time you use the ability, you got the shield buff but he doesn't protect the plane...

**Comment by alexspew** [comment]
Hi! The issue was duplicated spawns of gargoyles and dragons. They have now been removed and should be applied on next server update.
