### ISSUE TITLE
The will of the naaru - portal to shattrah not spawning

### ISSUE THREAD

**Issue by Tonneff** [SallyWhitemane/Mograine#419]
**Description:**
https://wotlkdb.com/?quest=13081
Upon accepting this quest, it should appear an npc creating a portal to Shattrath but it's not appearing.

**How to reproduce:**

Take the quest, it's part of a long chain in icecrown.

**How it should work:**

https://wotlkdb.com/?npc=30656 This npc should appear and create a portal to Shattrath

**Comment by alexspew** [comment]
Spell Name : Portal Effect: Shattrath
Spell Id : 57677

Object Name : Portal to Shattrath
Object Id : 192786

**Comment by Tonneff** [comment]
redid that quest with an alt-pg and it worked as intended
