### ISSUE TITLE
Feral lacerate tick

### ISSUE THREAD

**Issue by styxel** [SallyWhitemane/Mograine#420]
lacerate tick is bugd 

Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
The druid spell Lacerate Refreshes the tick period of the damage over time component.

Expected behaviour: Tell us what should happen instead
Lacerate should not refresh the tick period, only the duration of the debuff. This is how it worked until recently on this server.

Steps to reproduce the problem:

Use lacerate repetedly, one after the other.
See that no damage over time damage is dealt.
Stop using lacerate, and see that now the damage over time happens.
Include proofs for this behaviour

The way Lacerate works now is how most dots should behave:
"Also as of patch 4.0.1, DoTs no longer can be 'clipped'. Previously, if a DoT was refreshed before it had expired, the tick timer was reset, causing a delay of up to double the normal time between ticks between the last tick that occurred and the first tick of the refreshed DoT. " (https://wow.gamepedia.com/Damage_over_Time)
Lacerate should be an exception to this.

Because you need to use lacerate multiple times to build and maintain stacks, refreshing the tick period on cast causes major issues, as seen in this video: https://www.youtube.com/watch?v=sJYAPf4i0h4&feature=youtu.be
Notice how no damage over time damage is dealt until the player stops spamming lacerate.

Video of how Lacerate worked on retail wotlk: https://www.youtube.com/watch?v=4EboiQyuU60
Notice at 0:31 the player uses lacerate to deal 322 damage, and immediately after it ticks for 1029 damage. This is only possible if lacerate does not refresh the tick period.

https://github.com/dalaranwow/dalaran-wow/issues/4919

**Comment by alexspew** [comment]
Spell Name : Lacerate (Rank 1)
Spell Id : 33745

**Comment by petrHendrych** [comment]
Yo, I was testing lacerate today and it still override. Fight Loken in HoL, 19x used Lacerate as you can see in recount and only 1 recort for Lacerate (DoT). That 1 tick is coz I didn't have rage to apply another

![lacerate](https://user-images.githubusercontent.com/32193900/112039940-defb9a00-8b44-11eb-953f-5ff7d42f920e.png)
