### ISSUE TITLE
[quest] The Bloodcurse Legacy

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Mograine#422]
**Description:**
you are mailed the item which begins this quest "A Letter from the Admiral", but upon right clicking it it states: You don't meet the requirements for that quest.

**How to reproduce:**

**How it should work:**
you shouldnt be unable to start the quest, since the only requirements for it is to have "urgent delivery" quest completed

**Comment by alexspew** [comment]
Item Name : A Letter from the Admiral
Item Id : 24132

Starts following Quest -- Only requirement 

Quest Name : Urgent Delivery
Quest Id : 9671

Quest Id : 9672
Quest Name : The Bloodcurse Legacy

**Comment by alexspew** [comment]
Quest fixed a few weeks ago, requires Urgent Delivery completed.
