### ISSUE TITLE
Forgotten Depths Slayer

### ISSUE THREAD

**Issue by Painsawz** [SallyWhitemane/Mograine#425]
**Description:**
Mobs in Icecrown named Forgotten Depths Slayer in the Valley of Echoes will occasionally spam an ability that hits for 300+ plus repeatedly that will one shot anyone in about a second.

**How to reproduce:**

**How it should work:**
Should be an ability that hits for about that much once not every millisecond for a one shot.

**Comment by alexspew** [comment]
Duplicate : https://github.com/SallyWhitemane/Mograine/issues/315
