### ISSUE TITLE
Quest Disclosure

### ISSUE THREAD

**Issue by Zyksklo** [SallyWhitemane/Mograine#428]
**Description:**
You have to follow the skeleton around, but at the end of the tour you will not the task completed for quest.

**How to reproduce:**
Simply follow the skeleton around

**How it should work:**
By the end of the tour, skeleton should despawn, and you should get quest completed

**Comment by alexspew** [comment]
Same issue as https://github.com/SallyWhitemane/Mograine/issues/434

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
