### ISSUE TITLE
[Deathknight] Dancing rune weapon is not doing 50% of dk damage

### ISSUE THREAD

**Issue by danniellos94** [SallyWhitemane/Mograine#433]
**Description:**

Dancing rune weapon is not doing 50% of dk damage

**How to reproduce:**

https://prnt.sc/xt86mn dk damage
https://prnt.sc/xt87h3  dancing rune weapon damage

**How it should work:**
Should just do 50% of dk damage.

**Comment by alexspew** [comment]
Spell Name : Dancing Rune Weapon
Spell Id : 49028

**Comment by danniellos94** [comment]
Any progress at fixing it?

**Comment by danniellos94** [comment]
Still not working

https://prnt.sc/10juenp dk heartstrike damage
https://prnt.sc/10jufd4 dk deathstrike damage
https://prnt.sc/10jug42 heartstrike dancing rune weapon damage
https://prnt.sc/10jugzd deathstrike dancing rune weapon damage
