### ISSUE TITLE
Disclosure quest

### ISSUE THREAD

**Issue by thzeus** [SallyWhitemane/Mograine#434]
**Description:** https://www.wowhead.com/quest=12710/disclosure#comments

**How to reproduce:** Malmortis should give you the tour, it gets stuck on the stairs with multiple instances of the same mob stuck there from other players.

**How it should work:** He should come back to his coffin and complete the quest.

**Comment by alexspew** [comment]
Spell Name : Summon Escort
Spell Id : 52775 -- Might have a spell_trigger

Npc Name : Malmortis
Npc Id : 28948

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
