### ISSUE TITLE
Warlock Talent : Everlasting Affliction 5/5 - Corruption not refreshed instantly

### ISSUE THREAD

**Issue by cachocarne** [SallyWhitemane/Mograine#435]
"Drain Life, Drain Soul, Haunt and Shadow Bolt spells have a 100% to reset the duration of your Corruption spell on the target". This is a key mechanic in Affliction. It's known that a simple cast of Drain Life or Drain Soul is enough to refresh the Corruption debuff on target. However, using such spells is not refreshing instantly Corruption; it only gets reset/refreshed with the first Tic of the channeled skill, which occurs a few seconds after cast.

**How to reproduce:**
Cast Corruption on target. Wait for it to be about to end and proceed with casting Drain Soul or Drain Life. Corruption will not be refreshed even if you hold Drain Soul/Life for a couple of seconds

**How it should work:**
Corruption should be reset / refreshed INSTANTLY the moment the Drain spell is applied.

**Comment by Jamiexdx** [comment]
Can confirm this is how it should work

**Comment by cachocarne** [comment]
https://github.com/SunwellTracker/issues/issues/1903

Wowhead (forums&topic=162195): "I didn't even have to wait for the first damage tick - as long as the channel actually started and connected with the target, Corruption seemed to refresh."
