### ISSUE TITLE
UNCUT GEMS MISSING FROM THE VENDOR.

### ISSUE THREAD

**Issue by AndreiGameDev** [SallyWhitemane/Mograine#438]
**Description:**
Scarlet ruby and other uncut gems alike are missing from the Emblem of Heroism Quartermaster on both factions, there is meant to be an uncut gem for 10 and 20 heroism each and get replaced in toc by epic gems.
https://wowwiki.fandom.com/wiki/Scarlet_Ruby
https://wotlk.evowow.com/?item=40752#currency-for:0-13-2

**Comment by Jamiexdx** [comment]
This is not the case on start of launch - it should be there at patch 3.1 or 3.2 which one I can't remember.
