### ISSUE TITLE
Bug quest Disclosure At voltarus

### ISSUE THREAD

**Issue by apakaz** [SallyWhitemane/Mograine#447]
**Description:**
cannot summon the skeleton, have notification "A summon is already pending"

**How to reproduce:**

**How it should work:**
when we right click the coffin there is a skeleton coming out
![unknown](https://user-images.githubusercontent.com/78228398/106311169-4d378500-6297-11eb-8faf-c4a2e4affdea.png)

**Comment by alexspew** [comment]
Duplicate https://github.com/SallyWhitemane/Mograine/issues/434

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
