### ISSUE TITLE
Skeleton in the quest Disclosure

### ISSUE THREAD

**Issue by Thobias89** [SallyWhitemane/Mograine#448]
**Description:** Malmortis stops in the stairs and doesnt move on.

**How to reproduce:** Malmortis should give u the full tour but now he stop on the top of staircase.

**How it should work:** Malmortis should give u the full tour from his chest around Voltarus and also back to his chest so you explore it fully.
![WoWScrnShot_012921_192406](https://user-images.githubusercontent.com/37160144/106313430-7b51a080-6268-11eb-8af5-392214718482.jpg)

**Comment by alexspew** [comment]
Duplicate : 
https://github.com/SallyWhitemane/Mograine/issues/434

**Comment by SallyWhitemane** [comment]
Issue fixed, thanks for contribution!
