### ISSUE TITLE
Quest: Get to Getry bugged

### ISSUE THREAD

**Issue by Kaptajnu** [SallyWhitemane/Mograine#449]
The quest Get to Getry in Borean Tundra, Northrend is bugged out. Getry is standing around not doing anything and isn't interactable. This is presumably because someone started the scenario and then left.

**Comment by alexspew** [comment]
Quest Name : Get to Getry
Quest Id : 11703

Npc Name : Shadowstalker Getry
Npc Id : 25729

**Comment by alexspew** [comment]
Fixed on next server restart.
