### ISSUE TITLE
Death Knight->Unholy->Gargoyle 

### ISSUE THREAD

**Issue by foxeelol** [SallyWhitemane/Mograine#45]
Hello , The Gargoyle not benefit from Death Knight haste , having global cooldown on hes spell (officially should not) and sometime just melee attacking except shoting.
How it works : When you summon your Gargoyle he recive the current haste and critical chance  of the Death Knight (also benefit from Unholy presence) and there is no global cooldown on the Gargoyle Strike( https://www.wowhead.com/spell=51963/gargoyle-strike ) and never using melee attacks
https://prnt.sc/vj4ie5   there is 9 attacks over 30 seconds because of melee attacking and global cooldown and no haste benefit.

**Comment by Fulgurancex** [comment]
False report.Gargoyle SHOULD melee attack if summoned in melee range

**Comment by foxeelol** [comment]
lol no , and why there is a global cooldown on hes spell ?

**Comment by foxeelol** [comment]
https://www.wowhead.com/spell=43802/gargoyle-strike      GDC = 0  1.5 casting speed + haste from dk

**Comment by foxeelol** [comment]
Hes melee attacking cuz of global cooldown
