### ISSUE TITLE
Jedoga Shadowseeker Bug (Old Kingdom)

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#450]
**Description:**
Jedoga enrages even before the add reaches her circle to be sacrificed 

**How to reproduce:**
Do the fight and check the interaction for when her phase shifts and see that she enrages too early

**How it should work:**

She should only enrage once a volenteer gets on the circle

No Vod can record next time I do the fight

**Comment by alexspew** [comment]
Npc Name : Jedoga Shadowseeker
Npc Id : 29310
