### ISSUE TITLE
Destruction warlock

### ISSUE THREAD

**Issue by per0ken** [SallyWhitemane/Mograine#453]
**Description:**
The destruction lock is kinda bugged, there is a talent point called Backdraft, which makes destruction spells faster.

**How to reproduce:**
The Backdraft doesn't make warlock's Rain of Fire spell faster and it doesn't count as a tick of 3 Backdrafts.

**How it should work:**
Rain of Fire is a destruction spell and it should be faster to cast with Backdraft ticks.

**Comment by alexspew** [comment]
Talent name : Backdraft (Rank 1)
Talent Id : 47258
Aura Proc Id : 54274

Spell Name : Rain of Fire (Rank 1)
Spell Id : 5740

**Comment by Jamiexdx** [comment]
The Backdraft doesn't make warlock's Rain of Fire spell faster and it doesn't count as a tick of 3 Backdrafts.


That's because it is an unintended mechanic. it works fine.

**Comment by per0ken** [comment]
Hmm okay, I was wondering because I'm sure Rain of Fire did count as a tick of 3 Backdraft on another wotlk server. But I guess that was the bug.
