### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Crisp99** [SallyWhitemane/Mograine#454]
A bug where my character would be stuck in one place when I should be able to move. Usually happens after dying and being ported to the graveyard or at an inn after using my hearthstone.

Not sure how to reproduce it and not too sure if anyone else is having this issue. Only happened for the first time today and it happened about 4 times in 20 minutes.

Relogging seemed to fix the issue until I died again or used my hearthstone.

**Comment by alexspew** [comment]
Please include information about which zone and what you were doing?

**Comment by Crisp99** [comment]
I was in Icecrown at the Argent Vanguard being ganked while questing

**Comment by Crisp99** [comment]
But it also happened when I hearthstoned back to the Horde inn at Dalaran.

**Comment by alexspew** [comment]
Unable to reproduce. If issue happens again, please make a gm ticket.
