### ISSUE TITLE
Shattered Hand Guard spawns/falls underground every time in hellfire peninsula(see video)

### ISSUE THREAD

**Issue by EmmieQ** [SallyWhitemane/Mograine#455]
**Description:** a bug where a specific Shattered Hand Guard spawns underground https://youtu.be/h_m1G49P3JU

**How to reproduce:** walk there and see

**How it should work:** the mob should be spawning on the ground like any other mob.

**Comment by alexspew** [comment]
Npc Name : Shattered Hand Guard
Npc Id : 19414
