### ISSUE TITLE
Prospecting Thorium Ore

### ISSUE THREAD

**Issue by AHBARAR** [SallyWhitemane/Mograine#456]
**Description:**As jewel Crafting you have option to prospect 5 ore to discover gems different gems in it, Thorium ores is only giving 1 type of gems star ruby, and mithril ore only giving Citrine.

**How to reproduce:**the ores should give other kind of gems depending on the ore.

**How it should work:**  https://wowwiki.fandom.com/wiki/Prospecting

**Comment by V3n1m** [comment]
bad luck, i prospected thorium and got other rare gems

**Comment by alexspew** [comment]
Replica https://github.com/SallyWhitemane/Mograine/issues/202
