### ISSUE TITLE
Durnhold Thrall Gamebreaking bug for elixir mastery?

### ISSUE THREAD

**Issue by Jamiexdx** [SallyWhitemane/Mograine#457]
**Description:**
As part of the quest for elixir mastery I need to complete https://gyazo.com/d2dc59b08fede14e50ca0149888b27be
however thrall is unresponsive and just stands there not getting out his cell 

**How to reproduce:**
Go to Thrall inside Durnholde

**How it should work:**
He shou;ld accept your quest follow you and ride to the town to defeat the drakes which will ultimately give u a followup quest so u can enter black morass

**Comment by Jamiexdx** [comment]
Don't know how to reproduce it. may have been because of auti turn in quest addon.
but when I resetted instance without addons I had the same issue.

**Comment by alexspew** [comment]
Hi, unable to reproduce. Tried the quest multiple times, seems to work fine. Let me know if you manage to bug it again
