### ISSUE TITLE
[Paladin] Sanctified Wrath 

### ISSUE THREAD

**Issue by rndtestmag** [SallyWhitemane/Mograine#46]
The in title mentioned talent (retribution row 8) is bugged - it ignores absorb effects completly rn.

How to reproduce:
Buff mage with ice barrier, buff ret with avenging wrath, let ret hit mage.

What is supposed to happen:
dmg will consume ice barrier b4 hit the mage.

What happens right now:
dmg will bypass ice barrier competly - leaving a dead mage with icebarrier up.

The in title mentioned talent is causing this bug (sanctified Wrath), it should bypass any form of dmg reduction (including 50% of resilience, any talent/spell that provide %based dmg reduction) but not absorbs.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
