### ISSUE TITLE
Problems skinning wolves in Ashenvale

### ISSUE THREAD

**Issue by Jarvs97** [SallyWhitemane/Mograine#460]
Description:
When trying to skin the wolves found in Ashenvale, only the option to loot appears and nothing else.
The Npcs that have this error are the following:
Ghostpaw Runner (https://wotlkdb.com/?npc=3823)
Ghostpaw Howler (https://wotlkdb.com/?npc=3824)
Ghostpaw Alpha (https://wotlkdb.com/?npc=3825)
Mist Howler (https://wotlkdb.com/?npc=10644)

How to reproduce:
Loot them and try to skin them.
Class: DK

How it should work:
It should show the option to skin them.

-Arius (Mograine)

**Comment by alexspew** [comment]
Similar to https://github.com/SallyWhitemane/Mograine/issues/261
(Just linking issues)
