### ISSUE TITLE
Quest :  [Gadgetzan Water Survey]

### ISSUE THREAD

**Issue by Kraxit** [SallyWhitemane/Mograine#461]
**Description:**

Querst tells "Use the untapped dowsing widget near the pool of water by Sandsorrow Watch."

You can just use the widget middle of pool . And mob spawn at middle of pool and cant move , so you can kill spawned mob by range without taking any damage .

**How to reproduce:**

Take quest and try to use widget in pool except middle of pool .
**How it should work:**

It should be able to used at everywhere around pool and that spawned mob should be able to move .

**Comment by alexspew** [comment]
Quest Name : Gadgetzan Water Survey
Quest Id : 992

Item Name : Untapped Dowsing Widget
Item Id : 8584

Spell Name : Dowsing (This summons the Centipaar Tunneler near Sandsorrow Watch Water Hole)
Spell Id : 11758

Object Name : Sandsorrow Watch Water Hole
Object Id : 174796

Npc Name : Centipaar Tunneler
Npc Id : 5459

**Comment by alexspew** [comment]
Hi! Added more spawns for the object, so it should appear more blizzlike in the future. Thanks!
