### ISSUE TITLE
Battling the Elements

### ISSUE THREAD

**Issue by sefamurat** [SallyWhitemane/Mograine#464]
**Description:**
During the quest "Battling the Elements", Seething Revenants spawn at a staggeringly slow rate. Even at the lowest population times there are 3+ players waiting for one revenant to appear to finish the quest, essentially bottlenecking the sons of hodir questline.

**How to reproduce:**
Just do the quest

**How it should work:**
They should spawn at more spots and faster. Example video: https://www.youtube.com/watch?v=aRwHz4r3NdQ&ab_channel=wtbblue

**Comment by alexspew** [comment]
Quest Name : Battling the Elements
Quest Id : 12967

Npc Name : Vengeful Revenant KC Bunny
Npc Id : 30125
