### ISSUE TITLE
The Egg of Mortal Essence Affliction Warlock?

### ISSUE THREAD

**Issue by Smackadack** [SallyWhitemane/Mograine#465]
**Description:**

Hey, I wasn't quite sure if this would be considered a bug or not, but it's behaved differently from server to server, so figured here would be the best place to get a definitive answer.

The "Egg of Mortal Essence" trinket states that my direct healing and heal over time spells (haunt/soul siphon) can trigger the proc on the trinket, as it has on previous servers. Is this mechanic intended to not work on Whitemane, or is it perhaps bugged?

Cheers!

**How to reproduce:**

**How it should work:**

**Comment by Raulfin** [comment]
Warlock self heals could proc the effect in 3.0.3 but was fixed in next patch and was patched to not proc from life tap in 3.3.0.
