### ISSUE TITLE
Prospecting on this server doesn't work properly

### ISSUE THREAD

**Issue by Zeorgbugfinder** [SallyWhitemane/Mograine#467]
**How to reproduce:**
Prospect Thorium Ore - u will only get Star ruby and Azerothian Diamond (0 Huge emeralds, 0 Blue sapphires, 0 Large Opals)
I prospected over **40 stacks**!! of thorium ore and I did only get Star Rubys and Azerothian Diamonds
It can't be luck because Huge Emerald, Blue Sapphire and Large Opal have same chance to get from prostecting like Azerothian or Star ruby (15%)

**How it should work:**
https://wotlk.evowow.com/?item=10620#prospecting

**Comment by alexspew** [comment]
Replica https://github.com/SallyWhitemane/Mograine/issues/202

**Comment by Zeorgbugfinder** [comment]
> Replica #202

ah ok, but he didn't mention how much he prospected so if he did like 2stacks it means nothing.

**Comment by Zeorgbugfinder** [comment]
#202 is closed so i opened this

**Comment by Zeorgbugfinder** [comment]
Idk what happened with prospecting but on PTR I think it worked I tested it there
