### ISSUE TITLE
witchdoctor unbagwa

### ISSUE THREAD

**Issue by StoneBeardx** [SallyWhitemane/Mograine#468]
**Description:**
witchdoctor unbagwa in the spirit den in stranglethorne vale quest event keeps repeating after i finished the quest

**How to reproduce:**
had to have him killed by a gm to be able to start the quest, after i finished the quest the monkeys kept running into the cave like the quest was looping

**How it should work:**
it doesn't do that

**Comment by alexspew** [comment]
Npc Name : Witchdoctor Unbagwa
Npc Id : 1449

**Comment by alexspew** [comment]
Unable to reproduce. Please open new ticket if it keeps bugging out thanks!
