### ISSUE TITLE
Nesingwary base camp pvp guards not attacking

### ISSUE THREAD

**Issue by urban9** [SallyWhitemane/Mograine#469]
**Description:**
Guards in nesingwary base camp in Sholazar basin Northrend, dont attack when you open pvp or attack someone.

**How it should work:**
When you pvp in a guarded area guards should attack you.

![WoWScrnShot_013021_172358](https://user-images.githubusercontent.com/78081314/106358964-60dafe00-6320-11eb-8625-8cbabc7cd3ca.jpg)

^ Just killed an ally here and stood beside two guards, they did nothing to me.

**Comment by alexspew** [comment]
Npc Name : Nesingwary Game Warden
Npc Id : 30737
