### ISSUE TITLE
[Rogue] Vanish makes you about 0.5sec immune to snares/root.

### ISSUE THREAD

**Issue by rndtestmag** [SallyWhitemane/Mograine#47]
Vanish applies a brief layer of immunity toward snares and roots.

How to reproduce:
Get mage, get rogue, make rogue cast vanish, make mage immediatly cast frostnova after.

Another way:
vanish (instantly afterward) ambush on mage buffed with ice barrier (r1) and talented shattered barrier.

What is supposed to happen:
mage will frostnova the rogue out of stealth leave him in root by frostnova.

What happens right now:
rogue "dodges"/ immune the nova/snares from ice armor. (he gets unstealthed but not rooted/snared)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
