### ISSUE TITLE
bug in northrend map

### ISSUE THREAD

**Issue by maybenotxd** [SallyWhitemane/Mograine#470]
i have found this bug in northred when i was flying from dalaran to howling fjor. my games interface disappears and the framerate of the game is very bad, and because i was near water, the water disappeared too but when i dragged my view to other point the bug disappeared. the bug happened when i alt tabed back in the game
![WoWScrnShot_013021_171801](https://user-images.githubusercontent.com/78268146/106360183-c8dd1480-631f-11eb-84ee-b024e77bbd79.jpg)

**Comment by SallyWhitemane** [comment]
clientside issue
