### ISSUE TITLE
[ID: 11910] Secrets of the Ancients

### ISSUE THREAD

**Issue by MoonZapdos** [SallyWhitemane/Mograine#473]
**Description:** Respawn timer for both types of Ancients has been confirmed to be currently around 6 minutes, which is incredibly slow compared to every other mob in the server right now. It takes an absurd amount of time to complete the quest with all the players in Coldarra.

**How to reproduce:** Camped the spawn location of one of each until respawn.

**How it should work:** Every other monster in the game I've come across while questing has spawned considerably faster than this. Respawn timer should be at the very least halved.

**Comment by alexspew** [comment]
Quest Name : Secrets of the Ancients
Quest Id : 11910

Npc Name : Glacial Ancient
Npc Id : 25709

Npc Name : Magic-bound Ancient
Npc Id : 25707

**Comment by alexspew** [comment]
Hi!, they have respawn time around 5 minutes which is the normal value. They spawn all around Coldarra like a circle, so it shouldn't be a problem getting those.
