### ISSUE TITLE
[WARRIOR] stanceswap from Defensive Stance to Battle Stance not working via macro

### ISSUE THREAD

**Issue by kevblaha** [SallyWhitemane/Mograine#475]
**Description:**
I can't switch the stance as warrior from defensive stance to battlestance via macro.

**How to reproduce:**
Level 21 orc warrior, not able to chat atm (maybe the problem is with that) 

**How it should work:**
I should be able to cast battlestance via the /cast Battle Stance macro

**Comment by kevblaha** [comment]
After doing my 10 first quests, I'm able to swap the stance via macro again

**Comment by alexspew** [comment]
Can be closed. Is related to unable to chat
