### ISSUE TITLE
Quest "A delicate touch"

### ISSUE THREAD

**Issue by variabug** [SallyWhitemane/Mograine#477]
**Description:**
There are no attackers

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Quest Name : A delicate touch
Quest Id : 12820

Npc's are not spawning correctly.

Npc Name : Garm Invader
Npc Id : 29619

Npc Name : Snowblind Follower
Npc Id : 29618

**Comment by alexspew** [comment]
Hi all! This is now fixed, thanks!
