### ISSUE TITLE
soulshatter is not working

### ISSUE THREAD

**Issue by danniellos94** [SallyWhitemane/Mograine#480]
**Description:**
Soulshatter doesnt decrease aggro.

**How to reproduce:**
Use soulshatter.

**How it should work:**
It should decrease aggro.

**Comment by alexspew** [comment]
Spell Name : Soulshatter
Spell Id : 29858

**Comment by cachocarne** [comment]
I didn't experience any problem with Soulshatter. Bare in mind that you need to pop it before it's too late. Also, it doesn't "remove aggro" instantly, it **reduces** it by 50%. There must be another strong source of aggro to take it from you after you use the skill.

**Comment by danniellos94** [comment]
It is working, I think the issue is you can "miss" with it, looking at wiki it shouldn't miss im hit capped now and I dont have problems.
