### ISSUE TITLE
Quest - The Jig is up

### ISSUE THREAD

**Issue by Awkakelen** [SallyWhitemane/Mograine#487]
**Description:**
The Jig is Up quest in Howling Fjords won't work

**How to reproduce:**
"Mad" Jonah Sterling marked as grey and can't be attacked.

**How it should work:**
When he's injuried he should run to the nearby sleeping bear and be eaten by him.

**Comment by mrjonulis** [comment]
Yes,and now he is down just standing with low hp and you can't kill him and bear still sleeping
![WoWScrnShot_013121_032310](https://user-images.githubusercontent.com/78285363/106372011-feabe880-6373-11eb-8cde-c5faf648ba17.jpg)

**Comment by alexspew** [comment]
Npc Name : "Mad" Jonah Sterling
Npc Id : 24742

Npc Name : Hozzer
Npc Id : 24547

Object Name : Jonah Sterling's Spyglass
Object Id : 34128

Enter cave -> Get Jonah down to 30% HP -> Jonah jumps down and wakes up bear(hozzer) -> bear kills Jonah ->
kill bear (hozzer) -> loot bear get Jonah Sterling's Spyglass from bear.

**Comment by bjh368** [comment]
can confirm still broken

**Comment by atmichalak** [comment]
Still broken.

**Comment by alexspew** [comment]
Hi, please let me know on discord (alexs) if this remains broken after latest server restarts. Thanks!
