### ISSUE TITLE
[10854] The force of Neltharaku

### ISSUE THREAD

**Issue by SALOMONkevin** [SallyWhitemane/Mograine#489]
**Description:**

This quests asks to use an item on drakes. Unfortunately these drakes are not spawn on the server.

**How to reproduce:**

Go here : https://www.youtube.com/watch?v=zX9kFJxL9vU&ab_channel=TomSanGames
There is no drake in the area (I waited 1 hour, maybe the respawn time is very long).

**Comment by alexspew** [comment]
Quest Name : The Force of Neltharaku
Quest Id : 10854

Npc Name : Enslaved Netherwing Drake Kill Credit
Npc Id : 22316

Missing spawns?

**Comment by alexspew** [comment]
Duplicate -> https://github.com/SallyWhitemane/Mograine/issues/406
