### ISSUE TITLE
Quest: Return of the High Chief 

### ISSUE THREAD

**Issue by krangmang** [SallyWhitemane/Mograine#491]
**Description:**
Quest: Return of the High Chief - the Prison Key supplied by Banthok Icemist gets consumed when used on the crystal to summon Anub'et'kan, however, Anub'et'kan will only supply one party member with the quest item Fragmet of Anub'et'kan's Husk. This only seems to happen when multiple party members use the Prison Key on the crystal at the same time. Not knowing this, the quest was needed to be abandoned and re-accepted to complete. 

**How to reproduce:**
Anub'et'kan will only supply one party member with the quest item Fragmet of Anub'et'kan's Husk. This only seems to happen when multiple party members use the Prison Key on the crystal at the same time. Not knowing this, the quest was needed to be abandoned and re-accepted to complete. 

**How it should work:**
Probably should allow any party member to loot the husk no matter who uses it

**Comment by alexspew** [comment]
Duplicate -> https://github.com/SallyWhitemane/Mograine/issues/292
