### ISSUE TITLE
The talent  [Precision] in the Fury Warrior talent tree dosent work

### ISSUE THREAD

**Issue by Imorphius** [SallyWhitemane/Mograine#492]
**Description:**
Hi! 
I have noticed that I am missing when I am at 6.16% hit with the  [Precision] talent and I should be at a cool 9.16% hit well above the hit cap. And when I remove all of my gear I drop down to 0% hit 

**How to reproduce:**
Well by making a lvl 80 Fury Warrior and getting 5% hit (163.95 rating) and the  [Precision] talent you should be at 8% which is the hit cap for melee and if you miss then you know it's not working as intended 

**How it should work:**
I think it should show your actual hit % with the 3% baked in on the character pane thingy

**Comment by alexspew** [comment]
Talent Name : Precision (Rank 3)
Talent Id : 29592

**Comment by cloud1121** [comment]
With my war 5% hit, none of my yellows miss. 
Remember hit cap is for yellow attacks, not whites. Whites will always miss. And if it says Dodge/Parry, that is expertise.

**Comment by alexspew** [comment]
Invalid -- Talent works as it should.
