### ISSUE TITLE
Taking back Acherus quest

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#494]
**Description:** [DEATH KNIGHT] Quest titled "Taking Back Acherus" was not given to me by High Lord Darion Mograine after the previous quest was completed. He just poof'ed. Now I can't continue my DK starter story

**How to reproduce:** Be a DK. Do quest titled "The Light of Dawn."
Wait for all the RP to happen between Tirion Fordring, Alexandros Mograine, Darion Mograine & The Lich King to finish.
Complete "The Light of Dawn" quest as you talk w/High Lord Darion Mograine.
He shows you the following quest titled "Taking Back Acherus" but poofs before u can accept it. In it, it'd said to to use "Death Gate" ability to meet him back at Acherus. Use Death Gate ability but you have no quest to turn in to him & now you're back in the "normal world" (Mograine isn't back in front of Light's Hope Chapel.
Causes unable to proceed on DK starter storyline 😦

**How it should work:** DK is able to accept "Taking Back Acherus" quest & can continue w/DK starter quest/storyline

**Screenshot/video:** https://imgur.com/fBwNTtG https://imgur.com/L4zjcCq

**Comment by alexspew** [comment]
It seems this user was very unlucky on timing. The scenario event most likely happened when user turned in the first quest, so user was unable to take second quest.
