### ISSUE TITLE
Warrior - Intercept phasing through wall with no fall damage

### ISSUE THREAD

**Issue by aschrecashrehad** [SallyWhitemane/Mograine#5]
On the metal wall just outside the Icecrown Citadel raid, the sloped one on the left of the stairs heading up to the enterance to the raid, I was on a flying mount just above the gargoyle mobs on the edge of this wall.  Dismounting in the air and casting Intercept correctly charged to the mob, but then had me fall through the wall through the floor of the top of the wall. Upon hitting the ground a fair way down, no fall damage was dealt to me. I was unsuccesful in getting to happen a second time.

A screenshot of the mob/area in question is linked below:
https://imgur.com/a/sgLuktx

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
