### ISSUE TITLE
Gargoyle Strike ( I put it wrong last time ) 

### ISSUE THREAD

**Issue by foxeelol** [SallyWhitemane/Mograine#50]
There is a global cooldown on Gargoyle spell and it doesent have to.

Cost | None
40 yards 
Cast 1.5 seconds
GCD 0 seconds
https://www.wowhead.com/spell=43802/gargoyle-strike
Im playing DK 10 years ago and there was no GDC on it anywhere.   Check it more precisely this time please .

**Comment by rndtestmag** [comment]
To contribute abit in this topic:

Source: 
https://www.wowhead.com/spell=49206/summon-gargoyle#comments

From Bloodysorc (Patch 3.1.3):
"Current status of gargoyle:
-scales with all physical haste benefits at the same rate as the player
-attack power coefficient is 0.4
-base damage per strike is 120
-does not inherit any crit from the player
-does not inherit any +damage % modifiers from the player, such as bone shield, desecration, or blood presence
-player stats are taken as a snapshot when the gargoyle is launched; that is, when you cast this spell, however much attack power and haste is the amount your gargoyle strikes will be basing themselves off of."

Gargoyle Strike does not have an gcd however gargoyle will "request" server if the previous gargoyle strike has been finished casting already. This leaves a small "gap" between 2 gargoyle strikes - just a brief moment between two garg strikes.

Im still searching for a proof video from 2010, will link one once i've found it.

**Comment by foxeelol** [comment]
I don't remember that being so

**Comment by SallyWhitemane** [comment]
http://www.worldoflogs.com/reports/vweyx535vlctx49l/xe/?s=10358&e=10530&x=sourceName+%3D+%22Ebon+Gargoyle%22

There is a small delay between casts, for example:
[19:58:11.498] Ebon Gargoyle begins to cast Gargoyle Strike
[19:58:12.621] Ebon Gargoyle Gargoyle Strike Festergut 7480
[19:58:12.714] Ebon Gargoyle begins to cast Gargoyle Strike
[19:58:13.837] Ebon Gargoyle Gargoyle Strike Festergut 6735 (R: 662)

**Comment by foxeelol** [comment]
https://www.youtube.com/watch?v=jA5I7jCqyfg  this is a video from retail wotlk , yes there is a little delay but this delay bigger on Whitemane and gargo never melee attacking.

**Comment by foxeelol** [comment]
@SallyWhitemane
