### ISSUE TITLE
Feral druid Infected Wounds

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#503]
**Description:** I dont get Infected Wounds Buff on my feral druid anymore, or just sometimes.

**How to reproduce:** Play feral and use shred, maul and mangle.

**How it should work:** It should be actived with Shred,  Maul & Mangle attacks.
![54E4D177-E110-41D5-BDDB-F407AA185F80](https://user-images.githubusercontent.com/78295842/106381479-a56aa600-63c1-11eb-962d-682df47cfe58.png)

**Comment by alexspew** [comment]
Spell Name : Infected Wounds (Rank 1)
Spell Id : 48483

Applies following debuff on enemy by using Shred,Maul or Mangle
Debuff Name : Infected Wounds
Debuff Id : 58179

Spell Name : Shred (Rank 1)
Spell Id : 5221

Spell Name : Maul (Rank 1)
Spell Id : 6807

Spell Name : Mangle Cat (Rank 1)
Spell Id : 33876

Spell Name : Mangle Bear (Rank 1)
Spell Id : 33878

**Comment by styxel** [comment]
Has been working fine while ive been taking In hcs
