### ISSUE TITLE
Horde Quest: Get to Getry

### ISSUE THREAD

**Issue by kacak0** [SallyWhitemane/Mograine#504]
**Description:**
NPC is stuck, didn't despawn or didn't got killed after someone did the quest.

**How to reproduce:**
don't know

**How it should work:**
NPC should despawn or die, and get respawned at the original location.

Quest Name : Get to Getry
Quest Id : 11703

Npc Name : Shadowstalker Getry
Npc Id : 25729

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/449
