### ISSUE TITLE
QUEST The force of Neltharaku 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#507]
Has been reported before but person reporting claimed it wasn’t full.
**Description**
*[Quest][The force of Neltharaku]*
Enslaved Netherwing Drakes are not spawned in the Dragonmaw Fortress area. 
**How to reproduce:**
Take the mentioned quest and head to Dragonmaw Fortress. When you are there you can notice lack of the mentioned drakes.
**How it should work:**
There should be mobs called Enslaved Netherwing Drakes connected to Dragonmaw Subjugators. When used quest item on a drake, it should attack its captors and then fly back giving quest credit.
**Screenshot/video:**
https://www.youtube.com/watch?v=negt5rQFBoQ

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/406
