### ISSUE TITLE
Shadow priest : Dispersion

### ISSUE THREAD

**Issue by jelszos** [SallyWhitemane/Mograine#508]
**Description:**
I got killed twice by a rpally, and i took insane damage considering I used dispersion. Since it reduces damage taken by 90%, getting a 2k crit while Im udner the effect of it is ridiculous. I didnt have this problem before, maybe its a factor than i got stunned by hammer of justice but basically it shouldnt make any difference at all.

**How to reproduce:**
Basically doesnt work its main function, fix that part.

**How it should work:**
90% dmg reduction for 6 sec, the mana gaining function works correctly.
This is the screenshot of the combat log
![WoWScrnShot_013121_164321](https://user-images.githubusercontent.com/71779180/106389678-e0ca9c00-63e4-11eb-9eb3-234bc0863a10.jpg)

**Comment by alexspew** [comment]
Spell Name : Dispersion
Spell Id : 47585

**Comment by truepojkee** [comment]
not sure its a bug. 
ret pala has a tallent. which is called  "Sanctified Wrath" which is ignore 50% deff cds with Avengine Wrath

**Comment by Zeorgbugfinder** [comment]
Ret pal Avenging Wrath ignores 50% of reduced dmg.
2K crits while u have dispersion for winged ret are normal thing.

Nothing bugged here - close the issue.
