### ISSUE TITLE
Quest: Oracle Chain

### ISSUE THREAD

**Issue by Cipelin** [SallyWhitemane/Mograine#511]
**Description:**
I started The Part-time Hunter quest which leads to Chain that grants you access to Oracles. After I did the quest I turned to Tracker Gekgek to complete my quest. Shortly after whole server crashed. After I logged in, there weren't any quest I could take and return. I suppose that this crash broke my whole chain and now I can't continue it. I wish I could redo this quest cause Its very important to me.

**How to reproduce:**

**How it should work:**

**Comment by alexspew** [comment]
Invalid. Make a GM Ticket ingame next time this happens.
