### ISSUE TITLE
QUEST Stranglethorn Fever

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#515]
**Description:** Quest "Stranglethorn Fever" NPC stuck summoning
**How to reproduce:** Go to cave at 35, 60 and see Witch Doctor Umbagwa. He is noninteractive, and appears to be mid summon of Mokk.
**How it should work:** Should be able to interact with Umbagwa to summon Mokk the Savage so you can kill him for the quest.
**Screenshot/video:**see attached
![55B10473-5209-4D06-B92C-BCC9EF2914D6](https://user-images.githubusercontent.com/78295842/106396017-19cb3680-640e-11eb-87d3-63713eccfaa3.jpeg)

**Comment by alexspew** [comment]
Quest Name : Stranglethorn Fever
Quest Id : 348

Npc Name : Witch Doctor Unbagwa
Npc Id : 1449

Summons following mob : 
Npc Name : Mokk the Savage
Npc Id : 1514

**Comment by NonIdentifie** [comment]
![bug](https://user-images.githubusercontent.com/15000147/107412905-6d293d00-6b10-11eb-81f2-e25750999e47.png)
Still not working.

**Comment by alexspew** [comment]
Unable to reproduce. Please open new ticket if it keeps bugging out thanks!
