### ISSUE TITLE
QUEST The last line of defence 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#517]
**Description:** Argent Cannon 
**How to reproduce:** On quest : The Last Line Of Defense (Part 4 of 4)
**How it should work:** Horde can shot with cannon on Alliance player and cannon and vice versa
**Screenshot/video:**
![396944E1-D368-4453-A872-4A5174CE9535](https://user-images.githubusercontent.com/78295842/106397189-be507700-6414-11eb-88e1-7f57e2e00c95.jpeg)

**Comment by alexspew** [comment]
Quest Name : The Last Line Of Defense
Quest Id : 13086

Npc Name : Argent Cannon
Npc Id : 30236

Uses following spells while controlling "NPC" ::

Spell Name : Argent  Cannon
Spell Id : 57385

Spell Name : Reckoning Bomb
Spell Id : 57412

**Comment by alexspew** [comment]
Hi! Thanks! Issue has been resolved.
