### ISSUE TITLE
Master of Anatomy

### ISSUE THREAD

**Issue by Raulfin** [SallyWhitemane/Mograine#521]
**Description:**
Master of Anatomy skill is not removed when Skinning is unlearned.

**How it should work:**
The skill should be removed when the profession is unlearned.

**Comment by Raulfin** [comment]
Seems it will be the same for Toughness from Mining.

**Comment by alexspew** [comment]
Same issue as https://github.com/SallyWhitemane/Mograine/issues/519

Seems to be related to all Profession skills.

I think the issue is related to "Autolearn" system, needs investigation by devs.

**Comment by Royalwax** [comment]
Tested on toughness. Correctly losing passive of toughness after relog
