### ISSUE TITLE
Rogue stealth problem

### ISSUE THREAD

**Issue by Montanax1994** [SallyWhitemane/Mograine#522]
**Description:**
When i enter stealth or i vanish and quickly try to cheap shot or ambush it does the skill thats out of my stealth bar so my stealth breaks... Please fix that !

**How to reproduce:**
vanish and quickly try to cheap shot or any other stealth ability

**How it should work:**

**Comment by truepojkee** [comment]
its not a  bug. 100%
idk how its called. Delay or something else. Its connection issues. 
Same, same shit was on sunwell, I even made 2 video about it . 
AT ( Warmane blackrock) has fixed it , but idk how.

so its 100% server, but not a bug

**Comment by Montanax1994** [comment]
so will they fix it? i cant pvp with this thing

**Comment by truepojkee** [comment]
ofc no.

**Comment by alexspew** [comment]
Connection (ping) issue. Please check your Spell Queue (ms)
