### ISSUE TITLE
QUEST Bugged wyrm after Thrusting Hodir’s Spear

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#526]
Description: Bugged wyrm after finishing Thrusting Hodir's Spear. Was able to fly to Dalaran. Logging off dismounts.
How to reproduce: probably finish q in textures bc those fly in them.
How it should work: Definitely not like this
Screenshot/video:
![F30267F7-8EAE-4A0B-BABB-04D0F7D9B474](https://user-images.githubusercontent.com/78295842/106409045-5ddb2d00-6448-11eb-86bf-ddd5c26cb51c.png)

**Comment by alexspew** [comment]
Duplicate -> https://github.com/SallyWhitemane/Mograine/issues/393
