### ISSUE TITLE
quest "The Force of Neltharaku" not possible since enslaved dragons are missing

### ISSUE THREAD

**Issue by V3n1m** [SallyWhitemane/Mograine#534]
**Description:**
at this quest the dragons are invisible

**How to reproduce:**
fly to the dragonmaw fortress and look for the enslaved drakes

**How it should work:**
some orc npcs are casting a spell on the dragons, when entering combat they stop and attack the player. when the orc is killed you should be able to use the crystal you got from the NPC earlier

![image](https://user-images.githubusercontent.com/47416114/106457317-162bc400-648f-11eb-9b48-5a983c21f139.png)

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/406
