### ISSUE TITLE
The Force of Neltharaku quest can't be completed

### ISSUE THREAD

**Issue by roeland25** [SallyWhitemane/Mograine#537]
**Description:**
The quest Force of Neltharaku can't be completed because the Enslaved Netherwing Drakes aren't there. 
Somehow the drakes are invisible

**How to reproduce:**
Speaks for itself

**How it should work:**
Drakes should be visible and targetable by the provided item

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/406
