### ISSUE TITLE
Death Grip is unusable in mid-air.

### ISSUE THREAD

**Issue by itsnotbugged** [SallyWhitemane/Mograine#540]
**Description:**DK's cant use Deat Grip mid-air (Being knocked back by Thunderstorm,Typhoon, jumping off from something, etc)

**How to reproduce:**
If you mid-air and try to use death grip you get the "You cant use that right now" text.

**How it should work:**

Death Grip should be usable mid-air

**Comment by SallyWhitemane** [comment]
http://web.archive.org/web/20160310135709/http://www.arenajunkies.com/topic/63834-deathgrip/
