### ISSUE TITLE
ERROR #134 (0x85100086) Fatal Condition Program:	E:\World of Warcraft 3.3.5\Wow.exe  Failed to read file item\objectcomponents\head\helm_robe_pvpalliance_a_01_hum.m2.  Debug Details:  [2] err=0 text=SFileReadFile - item\objectcomponents\head\helm_robe_pvpalliance_a_01_hum.m2 - Data\common-2.MPQ [1] err=0 text=ReadSectors/DecompressData failed [0] err=0 text=ReadSectors/DecompressData failed Storm Error Msg:Reached the end of the file.

### ISSUE THREAD

**Issue by eobinn** [SallyWhitemane/Mograine#545]
Flew for the first time from DK starting place (level 80) to the nearest flight path (church below) after landing got message: 

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal Condition
Program:	E:\World of Warcraft 3.3.5\Wow.exe

Failed to read file item\objectcomponents\head\helm_robe_pvpalliance_a_01_hum.m2.

Debug Details:

[2] err=0 text=SFileReadFile - item\objectcomponents\head\helm_robe_pvpalliance_a_01_hum.m2 - Data\common-2.MPQ
[1] err=0 text=ReadSectors/DecompressData failed
[0] err=0 text=ReadSectors/DecompressData failed
Storm Error Msg:Reached the end of the file.

And now im stuck. Each time I log in this error comes and i'm unable to play.

**How to reproduce:**

**How it should work:**

**Comment by Platinumcoated** [comment]
your files are corrupted, download client from a different source
