### ISSUE TITLE
The Force of Neltharaku

### ISSUE THREAD

**Issue by zelatoswow** [SallyWhitemane/Mograine#549]
**Description:**
 [The Force of Neltharaku] Is part of the quest chain for the Netherwing drake mounts. You're supposed to use the Enchanted Nethervine Crystal on Enslaved netherwing drakes, but currently they are invisible. If you look in the combat log you can see that they are hitting you. 

**How to reproduce:**

**How it should work:**

You're supposed to use the Enchanted Nethervine Crystal on Enslaved netherwing drakes, but currently they are invisible. If you look in the combat log you can see that they are hitting you.

**Comment by wesliel** [comment]
There's a workaround to complete it.

Those enslaved drakes are invisible, but they're spawned with the Subjugators. Target these mobs instead and use the quest item. It would shoot 2 streams, one to drake and one to the enslaving subjugator. When you see the subjugator taking damage, kill it. Wait a few seconds for the stream to shoot back at you to get the quest credit.

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/406
