### ISSUE TITLE
Some little things in the Howling Fjord

### ISSUE THREAD

**Issue by Josarth** [SallyWhitemane/Mograine#55]
First i saw a visual bug on all the elevators with dragon stone head looking them from the top.

Second after i completed the chain quest from NPC Hidalgo the Master Falconer, some falcons appear in my bag if i fly around the Explorer's League Outpost.

Third the sharks i saw at the west coast of the Scalawag Point are flying on the sea.

Fourth for complete the Kalu'ak's Daily Quest: The Way to His Heart... it took six tasty reed fish, because the Reef Bull stopes moving all the time. And i remember complete it on other servers with one fish.

**Comment by Josarth** [comment]
Forgot add when i completed the Quest: Swabbin' Soap the NPC dont do the animation of the brooms cleaning the ship

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
