### ISSUE TITLE
bug in talent Soul Warding

### ISSUE THREAD

**Issue by Taytacha** [SallyWhitemane/Mograine#552]
**Description: The Soul Warding talent from the Discipline branch in the Priest's talents reduces the cooldown from 15 seconds to 10 seconds, but the buff does not happen. Please hope they can fix it as it is a good talent from priest heal.

**How to reproduce: the talent Soul Warding does not have its effect on skill Word of power: Shield

**How it should work: the talent Soul Warding make what the skill Word of power: shield can be used in 10 seconds

**Comment by SallyWhitemane** [comment]
Can't reproduce
