### ISSUE TITLE
Battle at Valhalas: Fallen Heroes 

### ISSUE THREAD

**Issue by Sinisterlady** [SallyWhitemane/Mograine#557]
**Description:**
Battle at Valhalas: Fallen Heroes bug. only 4/6 heroes spawn, when kited they reset and despawn.
**How to reproduce:**
Talk to Geirrvif in Valhalas once the player got the quest. 

**How it should work:**
Once the battle have started, all six of the fallen heroes should spawn. if kited, they will not reset and despawn.

screenshot/video: https://www.youtube.com/watch?v=O0cw0Xn7Zuk

**Comment by alexspew** [comment]
Hi, this is now fixed thanks!
