### ISSUE TITLE
[Priest][Shadow]  Pain and Suffering talent not working properly on 2 points

### ISSUE THREAD

**Issue by xaring** [SallyWhitemane/Mograine#558]
**Description:**
Shadow Priest Pain and Suffering talent not working properly on 2 points

**How to reproduce:**
Put 2 points in the talent instead of 3?

**How it should work:**
Should have 66% chance to refresh the duration of shadow word pain on the target, currently it does not refresh it at all. Its not being unlucky, its always like that.

**Comment by SallyWhitemane** [comment]
Can't reproduce.
