### ISSUE TITLE
[Quest] Battle of Valhalas: Fallen Heroes

### ISSUE THREAD

**Issue by xaring** [SallyWhitemane/Mograine#559]
**How to reproduce:**
Talk to Geirrvif in Valhalas once the player got the quest. 

**How it should work:**
Once the battle have started. all six of the fallen heroes should spawn. if kited, they will not reset and despawn. 
https://www.youtube.com/watch?v=O0cw0Xn7Zuk

**Comment by alexspew** [comment]
Hi, this is now fixed. Thanks!
