### ISSUE TITLE
Quest:Kindness (Shadowmoon Valley)

### ISSUE THREAD

**Issue by Goreblade** [SallyWhitemane/Mograine#560]
**Missing NPC - Mature Netherwing Drake while on ground**

**How to reproduce: Take the quest and try to use quest item**

**How it should work: Mature Netherwing Drake required while grounded to be fed quest item used close to the drake which will then cause the drake to fly off after feeding:**

**Comment by alexspew** [comment]
Quest works fine, it takes a while for dragon to go around.
