### ISSUE TITLE
''A Delicate Touch'' quest

### ISSUE THREAD

**Issue by DiogoJCA** [SallyWhitemane/Mograine#563]
**Description:**
When trying to do the quest '' A Delicate Touch'' at Storm Peaks location Garm's Bane near K3 the npc's are spawning from the k3 side instead of spawning from the east where they did

**How to reproduce:**
Go to the quest location in storm peaks and try to do it

**How it should work:**
The mobs should spawn from the east side and run into the mines players put down to do the quest but eventually they they to the turrets that are on the floor atm killing them while they spawn from k3 side which is wrong

**Comment by alexspew** [comment]
https://github.com/SallyWhitemane/Mograine/issues/477
