### ISSUE TITLE
[Client] Constant fatal error while using the Whitemane client

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#568]
Description:
Constant fatal error since i downloaded the whitemane client.
How to reproduce:
It occured when i downloaded the whitemane client.Can occur if you use the whitemane client. Kekw

How it should work:
It shouldn't throw you out of the game every 1 minute in dalaran.

![4B0CB3D6-C3B6-48BE-8052-6E59FA909C25](https://user-images.githubusercontent.com/78295842/106601709-a556db80-6564-11eb-88ec-7fa84380d5bb.png)

**Comment by Platinumcoated** [comment]
Looks like the RAM issue, it's not just the whitemane client, it's the WotLK client in general.
Lowering draw distance will help reduce these crashes, but patching the executable will fix the problem.
https://ntcore.com/?page_id=371
this patch worked for me
