### ISSUE TITLE
[Quest] Territorial Trespassing 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#569]
Description:
The quest Territorital tresspass does not work, placing the stack of eggs does not summon Veranus.
How to reproduce: Place the stacks of eggs, observe.
How it should work: Veranus should be summoned when placing the stacks of eggs.

**Comment by Platinumcoated** [comment]
I've done this quest yesterday and it worked, although it took a really long time for Veranus to spawn. Could have been like half a minute of waiting while nothing is happening

**Comment by TheRealestMcCoy** [comment]
It does work but the time for Veranus to appear is almost a minute or more.

**Comment by alexspew** [comment]
Hey all! I've looked into the issue, the issue is related to the eggs (gameobjects). I've applied a fix and seems to be working good (instant spawn) now, fix should be live when reflected in #changelog at discord! Thanks
