### ISSUE TITLE
When your pet kills a mob.. you can't loot it.

### ISSUE THREAD

**Issue by darklord221** [SallyWhitemane/Mograine#570]
**Description:**
Pet kills mob.. mob can't be looted (or skinned)

**How to reproduce:**
Be a class with a pet (warlock), have your pet solo kill a mob. mob drops nothing or you cant loot anything from said mob..

**How it should work:**
you should be able to get drops from mobs your pet kills

**Comment by Raulfin** [comment]
This was how loot worked untill 7.0.3, before the change you had to deal at least 1 dmg to a target your pet kills to get quest/loot credit for it.

https://wow.gamepedia.com/Patch_7.0.3_(undocumented_changes)
Player pets can now kill enemies entirely on their own, and can loot the corpse afterward.
