### ISSUE TITLE
Wolves in north duskwood can't be skinned

### ISSUE THREAD

**Issue by darklord221** [SallyWhitemane/Mograine#571]
**Description:**
Wolf mobs inhabiting north of duskwood map: Starving Dire wolf, Rabid Dire wolf cannot be skinned even tho they are beasts and you loot everything from them. 

**How to reproduce:**
Kill a wolf and loot everything and try to skin him.

**How it should work:**
You should be able to skin them after you kill them and loot them.

**Comment by alexspew** [comment]
Duplicate issue -> https://github.com/SallyWhitemane/Mograine/issues/261
