### ISSUE TITLE
[Quest] Recharging The Batteries

### ISSUE THREAD

**Issue by z4ika** [SallyWhitemane/Mograine#572]
**Description:**
Recharging the Batteries quest in Netherstorm, Outlands is not working.
Using a quest item on wyrms doesn't count charge levels.

**How to reproduce:**
Use Battery Recharging Blaster on Phase Hunter NPC's in the Ruins of Enkaat

**How it should work:**
[wowhead description](https://www.wowhead.com/quest=10190/recharging-the-batteries)

**Comment by alexspew** [comment]
Quest works fine, you have to damage them to under 30% hp before using item on Phase Hunter. Which turns them into "Drained Phase Hunter" and after you kill it, you get progress.
