### ISSUE TITLE
[Quest] Shoot ‘em up combat bug

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#576]
**Description: Combat bug after Shoot 'Em Up**
**How to reproduce: Do the (Daily)quest**
**How it should work: Shoot down drakes with the harpoon, get into combat bug after.**
**Screenshot/video: Sadly no, I died being stuck on 600 HP because I couldn't eat as a result.**

**Comment by alexspew** [comment]
Remember to kill all the drakes you have aggro on.
