### ISSUE TITLE
Obliterate

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#58]
Description: Obliterate counts both weapons hence why you get 10 runic power from 4set bonus instead of 5.Same with https://wotlk.evowow.com/?spell=50115

How to reproduce: get 4set t7 and spec into https://wotlk.evowow.com/?spell=50115

How it should work: 4set and the talent should only give you 5 runic power

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
