### ISSUE TITLE
thunderstorm in sap

### ISSUE THREAD

**Issue by truepojkee** [SallyWhitemane/Mograine#581]
**Description:**

shaman can use thunderstorm in sap.

**How it should work:**

he shouldn't. Only in stun..  https://imgur.com/a/L35IE4u

SAP IS NOT STUN!

**Comment by alexspew** [comment]
Sap is a stun. Invalid

**Comment by truepojkee** [comment]
sap is not stun, u  idiot.
sap is  incapacite, like gouge, blind etc

**Comment by truepojkee** [comment]
https://youtu.be/_xA_1KnMs3k
