### ISSUE TITLE
Flying in cat form

### ISSUE THREAD

**Issue by sclefe** [SallyWhitemane/Mograine#587]
**Description:** Glitch while transforming into cat from flight form, which allows cats (presumably other forms too) to fly while shapeshifted

**How to reproduce:** I could only test this for around 15-30 seconds before i got autobanned, but i guess it works like this: you approach a big mass of water while in flight form, and while trying to enter the water, switch to cat form. You will change form to cat, wont be able to enter the water, but will be able to attack and use cat skills, while also flying.

**How it should work:** It should take away the flying capacity xd (kids at home: dont try to reproduce this because you'll get autobanned)

**Comment by Rukstone** [comment]
I record a exemple on how to perform this bug.
https://www.youtube.com/watch?v=1Hgil8c2TV8&feature=youtu.be
if used for bad intention can be verry disruptive.

**Comment by sclefe** [comment]
Thanks for uploading a video about it. Yes, i also found out that the glitch could be performed while jumping out of water and shapeshifting into flight form, with the right timing.
