### ISSUE TITLE
[Quest] Victory is near/Rifle the bodies

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#588]
**Description:** cant get the quest Victory is near/rifle the bodies even tho i have completed all quest until it 
**How to reproduce:**? when a quest is missing?
**How it should work:** get the quest?
**Screenshot/video:** well how when i cant get any quest?

**Comment by alexspew** [comment]
Hi, issue was resolved a few weeks ago, this is a quest chain in dragonblight. https://www.wowhead.com/quest=12034/victory-nears
