### ISSUE TITLE
Balance druid threat 

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#59]
Description:

Balance druid seems to be doing too much threat on single targets. https://www.twitch.tv/videos/832653003 check 2:20

How to reproduce:

Get BiS naxx prot paladin and BiS naxx balance druid and see if he overaggroes paladin. 
We did naxx 25, even had Hand of Salvations on the druid and paladin was pulling under Avenging Wrath/Tricks of the Trade, but boomkin still managed to get aggro, even if he was 6th, 7th on DPS. 

How it should work:

Boomkin shouldn't do this much threat.

**Comment by ghuser44** [comment]
Can confirm.
Boomkins pull aggro very fast, as if the talent **Nature's Reach** (16820) isn't reducing threat properly.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
