### ISSUE TITLE
Bugged Quest - Pathing

### ISSUE THREAD

**Issue by tojara04** [SallyWhitemane/Mograine#592]
**Description:**
Thrusting Hodir's Spear quest.

The Wild Wyvern stays dead and flying after you kill it.
The Wild Wyvern flyes inside the mountains and despawns causing the character to fall and die below the map.

**How to reproduce:**

IDK what to put here.

Here are some img

![imagen_2021-02-03_181802](https://user-images.githubusercontent.com/25622033/106821944-28069600-664c-11eb-8876-fe2f4d847d24.png)

**How it should work:**
It should drop you to the ground after you kill it and the corpse should dissapear.
The fly path should be scripted correctly to not go inside terrain or buildings.

**Comment by alexspew** [comment]
Duplicate -> https://github.com/SallyWhitemane/Mograine/issues/393
