### ISSUE TITLE
[Fishing] Raw Redgill seems unobtainable 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#594]
**Description:**
Fishing Raw Redgill seems bugged, none caught so far in 6 different zones. Using a lvl 80 character with >300 fishing skill.
I got a lot of the "special" Redgills, like the "xx Pound Redgill", which suggests I was in the right areas!
**How to reproduce:**
Go to any of the following zone and try to fish some Raw Redgill.
So far I tried the following zones: Western Plaguelands, Moonglade, The Hinterlands, Feralas, UnGoro Crater, Felwood
**How it should work:**
According to wowhead you should be able to fish Raw Redgill in a couple of zones.
https://classic.wowhead.com/item=13758/raw-redgill

EDIT:  There is lots more fish that dont work right. So far I found: darkclaw lobster, Raw Redgill, Raw Glossy Mightfish, Raw Spotted Yellowtail, Raw Summer Bass
and probably lots more

**Comment by alexspew** [comment]
Related to -> https://github.com/SallyWhitemane/Mograine/issues/501. I've linked ur report thanks!
