### ISSUE TITLE
[Naxxramas] Heigan dance does damage on spots where it doesnt "visually" reach.

### ISSUE THREAD

**Issue by tdymel** [SallyWhitemane/Mograine#599]
**Description:**
In Naxx 25 on Heigan the dance has more reach than it should. It clearly does damage where it is not visually.
See the Shaman Lucker that died in the middle of the safe spot and various other players.
Link: https://www.twitch.tv/videos/899509442?t=03h22m50s

**How to reproduce:**
Try the dance at the spots where the people died in the video.

**How it should work:**
Should only have the visual range.

**Comment by DkLock2** [comment]
same thing happened to us, fix pls
