### ISSUE TITLE
Mobs Evade

### ISSUE THREAD

**Issue by CryWolfOHS** [SallyWhitemane/Mograine#6]
Description : If you attack a non aquatic NPC ( humanoids / beasts ) and jump in water, they evade and reset
How to reproduce : I tested this on Echo isles with tigers - attack a tiger then jump in water - he evade 
Also tested on THe Forgotten Pools with centaurs 
How it should work - mobs should chase you in water and attack 

Kind Regards,
CryWolf

**Comment by SallyWhitemane** [comment]
This is working as intended, based on retail WoW data from 2.3 and 3.1 patch.
