### ISSUE TITLE
[DRUID(balance)] Force of Nature treant health is too low

### ISSUE THREAD

**Issue by Zeorgbugfinder** [SallyWhitemane/Mograine#60]
![without gear](https://user-images.githubusercontent.com/58181528/101828472-e4068180-3b31-11eb-9ae2-f3c0b448ac97.jpg)
This is treant health without gear
![with gear](https://user-images.githubusercontent.com/58181528/101828863-6a22c800-3b32-11eb-9ef0-7f67df9470f8.jpg)
this is treant health with gear (scales from items well)

but 8k treant health is still low

Treants are supposed to have 13k+ health on lvl 80
there might be scaling from lvl missing becoz if we ignore gear scaling then health of treant has same health on lvl 50 as on lvl 80 (im pretty sure treant has like 4.8k health on lvl 50 coz i lvled bala alot)

or there might be this change missing
World of Warcraft: Wrath of the Lich King Patch 3.3.0 (08-Dec-2009): Health on the treants has been increased.
(taken from https://wowwiki.fandom.com/wiki/Force_of_Nature)

![sunwell](https://user-images.githubusercontent.com/58181528/101831931-ef0fe080-3b36-11eb-8463-7c7e5b3ccfc1.jpg)
This is treant health on sunwell (they had it bugged too but they fixed it https://github.com/SunwellTracker/issues/issues/2598)

I know I should not give proofs from other private servers coz they might not be good but im pretty sure treant should have 13k+ health on 3.3.5a lvl 80

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
