### ISSUE TITLE
[Shaman] Feral Spirits don’t retain previous Pet options

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#601]
**Description:** Feral Spirits (Enhancement Shaman) don't retain previous "Pet" options aka Spirit Walk/Twin Howl don't remain autocasted after being set and they also won't retain aggreesive settings aka if you set it to passive, next time you cast it is agressive always no matter if you change the settings it resets to (no spirit walk autocast/twin howl and aggressive setting)

**How to reproduce:** Play enha.

**How it should work:** -

**Comment by tdymel** [comment]
ohya this is annoying.
