### ISSUE TITLE
[Warlock] Decimation spell issue

### ISSUE THREAD

**Issue by creativemonkeyz** [SallyWhitemane/Mograine#603]
**Description:** 
    When a target is at or below 35%HP and Shadow bolt, Incinerate or Soul Fire is used on this target, Decimation MUST be activated. Problem appear when you hit the target with one of those 3 spells and target dies, in this case Decimation will not be activated anymore.
**How to reproduce:**
    You need to have a demonology warlock with Decimation spell selected on talent tree. Try to hit the target with spells like searing pain which don't deal too much dmg so you can have your target below 35% hp. Try to hit the target until it will be at 10% HP so you can be sure you will kill it with your next Shadow bolt spell. After the target is below 10%HP hit it with shadow bolt. if it will die from it you will see that Decimation will not be activated.

**How it should work:**
Decimation spell doesn't specify that if target die it should not be activated, so when you hit the target below 35% hp with Shadow bolt, Incinerate or Soul Fire Decimation should be activated even if the target die from this cast.

**Comment by danniellos94** [comment]
That's right and that an important bug. When you get a killing blow with shadow bolt, incinerate or soulfire you don't get a decimation buff.

**Comment by herbhenk** [comment]
also right now you cant get decimate proc when you receive hand of protection from paladin but you should be able too
