### ISSUE TITLE
(daily quest) Break the Blockade ID: 11153

### ISSUE THREAD

**Issue by DkLock2** [SallyWhitemane/Mograine#605]
**Description:**
I completed the quest, but I did not get the exp reward.

**How to reproduce:**
Complete the quest and claim the rewards.

**How it should work:**
You should get exp for it.
https://www.wowhead.com/quest=11153/break-the-blockade#guides
https://www.youtube.com/watch?v=u-63dkdHUg0

**Comment by alexspew** [comment]
Hi, this quest does indeed have exp on it (at least what I can see) what level were you when you turned it in? If you don't want to respond here, that's fine too! I cannot reproduce the error from latest fixes
