### ISSUE TITLE
[Quest] Still at it

### ISSUE THREAD

**Issue by xaring** [SallyWhitemane/Mograine#607]
**Description:**
When "tipsy" (quest giver) says "light up the brazier" and i did light the brazier and few seconds he will say "YOU HAVE FAILED".
https://www.wowhead.com/quest=12644/still-at-it

**How to reproduce:**
snip

**How it should work:**
it should continue the quest after i light the brazier and go on and go on ...

**Comment by alexspew** [comment]
Hi, quest should be solvable on next server restart! Thanks
