### ISSUE TITLE
Val'kyr protectors do incorrect damage

### ISSUE THREAD

**Issue by Starcallerx** [SallyWhitemane/Mograine#61]
**Description:**

Val'kyr protector which spawn from the staff Nibelung (Heroic) does very little damage.

**How to reproduce:**

1) Equip the item Nibelung (Heroic).
2) Start dpsing with spells on a dummy
3) Wait for Val'kyr protector to proc
4) Notice that the val'kyr protector does very little damage.

**How it should work:**

According to wowhead the val'kyrs should do 1591 - 1785 damage. But currently, they do only 29 damage.
Please refer to this wowhead link : https://www.wowhead.com/item=49992/nibelung#comments

**Note :**

This issue only occurs with Nibelung heroic and not with Nibelung normal.

![val'kyr incorrect damage](https://user-images.githubusercontent.com/46014106/101852100-e0e7b180-3b82-11eb-9284-07b80939c63b.jpg)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
