### ISSUE TITLE
Quest Bug A Strange Device

### ISSUE THREAD

**Issue by Balinha1994** [SallyWhitemane/Mograine#612]
**Description:**
Quest A Strange Device not working since mob does not drop the item
The Mob is called Goramosh and shoudl drop an item to start the quest

**How to reproduce:**
Mob does not drop the loot
**How it should work:**
Mob should drop item 
Goramosh's Strange Device
Quest Link https://wotlk-twinhead.twinstar.cz/?quest=12059

**Comment by alexspew** [comment]
Hi, thanks for the report. Drop has been fixed and should be live within a few days.
