### ISSUE TITLE
Retribution Paladin Hit Cap bugg

### ISSUE THREAD

**Issue by kamile3k123** [SallyWhitemane/Mograine#618]
**Description:**
im missing hits with 268 Hit rating

**How to reproduce:**

**How it should work:**
with 263 hit rating u cant miss melee att
![obraz_2021-02-04_213945](https://user-images.githubusercontent.com/78565935/106952525-82c5ed80-6731-11eb-953f-0979321d7907.png)
![obraz_2021-02-04_214021](https://user-images.githubusercontent.com/78565935/106952590-983b1780-6731-11eb-82a0-771d424ffae3.png)

ack

**Comment by potiput** [comment]
Same thing happend to me as mage in naxxramas, i was 1% over capped with hit rating yet i was missing my spells

**Comment by scrublama** [comment]
enhancement guy in my guild also missed lightning bolts while being spell hitcapped

**Comment by Zeorgbugfinder** [comment]
are u sure u wasnt voa on stone boss who reduce hit chance
