### ISSUE TITLE
Naxxramas

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#62]
1.Loatheb spores moving too fast and cannot be gripped (check https://www.twitch.tv/videos/832653003  00:13:55)
2. Slimes before patchwerk cannot be slowed and move too fast (check https://www.twitch.tv/videos/832653003 00:19)
3.Orb doesn't port you out of Saphiron Lair (https://www.twitch.tv/videos/832653003 00:16:40)

**Comment by SallyWhitemane** [comment]
Couldn't find any confirmation that slimes can be slowed, but they should move at 50% speed.
https://www.wowhead.com/npc=16011/loatheb#comments:id=648118 - spores should be immune to grip.
Rest of the issues are fixed.
