### ISSUE TITLE
[Quest] Reconnaissance flight 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#622]
Description: 
https://www.wowhead.com/quest=12671/reconnaissance-flight The quest "Reconnaissance Flight" is not working correctly. When you glide the damaged plane down, it's supposed to descend quickly while on fire. Like seen here 
Instead the plane just flies slowly at the same altitude.

How to reproduce:
Accept the quest, and wait for the damage phase part of it

How it should work:
Like seen here https://www.youtube.com/watch?v=aw-Eugwg7eI&feature=emb_title the plane glides quickly when damaged

**Comment by Mugera500** [comment]
having the same issue and is unable to complete quest, plane is just flying straight

**Comment by alexspew** [comment]
Hi! Quest has been fixed, I also added a quality of life when plane is damaged (it's faster now)
