### ISSUE TITLE
Argent Vanguard Walking

### ISSUE THREAD

**Issue by Hraiboi** [SallyWhitemane/Mograine#624]
**Description:**
Ever since I have had/turned in the quest "The Last Line of Defense" my character starts floating randomly about 1ft off of the ground, then gets stuck falling in the same position

**How to reproduce:**
Happens every couple of steps and I need to restart WoW to stop it

**How it should work:**
Shouldnt get stuck walking

**Comment by alexspew** [comment]
Should be resolved now (2 weeks ago), if you still have the issue please contact me on discord (alexs). Thanks!
