### ISSUE TITLE
[Quest] Poached, Scrambled, Or Raw?

### ISSUE THREAD

**Issue by Peppersprayz** [SallyWhitemane/Mograine#625]
**Description:**

The quest "Poached, Scrambled, Or Raw?", given by the Venomhide Hatchling (raptor for [Whistle of the Venomhide Ravasaur]) is undoable cause you can't click the Silithid Eggs.

**How to reproduce:**

Take the quest "Poached, Scrambled, Or Raw?" and try to get the eggs in Tanaris.

**How it should work:**

You should be able to click and loot the Silithid Eggs in Tanaris, like in this video : https://www.youtube.com/watch?v=q-TMMFJR59U&ab_channel=rangercolts

**Comment by Peppersprayz** [comment]
It seems fixed

**Comment by alexspew** [comment]
Fixed.
