### ISSUE TITLE
Quest gold lower than it should be.

### ISSUE THREAD

**Issue by erykos22** [SallyWhitemane/Mograine#635]
**Description:**
When a quest is viewed in a log, it shows the right amount of awarded gold, but when it is turned in, the reward is lower than in the log description. The difference can be as high as 50% in some cases.
![WoWScrnShot_020421_221013](https://user-images.githubusercontent.com/78063610/107067853-28d03100-67e0-11eb-8cc0-178f2cd4ab83.jpg)
![WoWScrnShot_020421_221316](https://user-images.githubusercontent.com/78063610/107067888-308fd580-67e0-11eb-8c2d-644d6b623ee8.jpg)

**Comment by mdeluca0** [comment]
I'm experiencing this as well. Horde side.

**Comment by scrublama** [comment]
https://wotlk.evowow.com/?quest=12699

**Comment by scrublama** [comment]
**It's just visual bug.**
look at this gallery of picture from my daily jwc quest. You end up with the correct amount of gold and it's just visually showing different numbers on questlog, why I don't know but it's been the same on all private servers I played.
https://imgur.com/a/UxtL7Ql

**Comment by alexspew** [comment]
Hi! Visual Bug
