### ISSUE TITLE
Paladin Reckoning talent proc chance issue

### ISSUE THREAD

**Issue by Bigmike4470** [SallyWhitemane/Mograine#638]
**Description:**
The Paladin talent Reckoning talent does not proc as often as it should.

**How to reproduce:**
Get hit by a bunch of mobs as a prot pally with Reckoning talent and have it not proc

**How it should work:**
Should proc on 10% of hits and blocks

**Comment by SallyWhitemane** [comment]
Can't reproduce, chance is correct.
