### ISSUE TITLE
[Quest] Betrayal friendly adds disappearing 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#639]
**Description:** The quest Betrayal [Zul'Drak].
You got the scepter which help kill Drakuru.
You take control under mob and go to kill Drakuru. But during fight or at start, your controlled mob just disappears.
Note from Anna: ALSO sometimes the skull just disappears after kill. 

**How to reproduce:** The adds should stay up till the boss dies. 

**How it should work:** Adds should not die and the skull should stay lootable.

**Comment by alexspew** [comment]
Invalid. Quest works fine after removal of duplicate mob, they do not despawn. 
If you use the scepter too soon (before the raid warning), you will get control of a troll, but Drakuru will not attack. The troll will eventually despawn and then Drakuru will attack. The scepter has a longish cooldown, so you will be stuck soloing Drakuru. He simply stands in the center and casts shadow bolts and eventually Blight Crystals.
