### ISSUE TITLE
[Quest] Fire at will!

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#641]
Another bug in the series of "who gives a shit":

Description: The quest "Fire at will!" (https://www.wowhead.com/quest=10911/fire-at-will) doesnt work properly, it turns a cannon into a minion that follows you around.
How to reproduce: Use the quest item on a cannon 
How it should work: Not sure exactly, but its supposed to be used to destroy portals
Screenshot:
![3B8946F5-E12B-407E-9114-816D56BEEF2A](https://user-images.githubusercontent.com/78295842/107102864-6d7dbb80-6824-11eb-9164-2f7d4739b84b.png)

**Comment by alexspew** [comment]
Hi! Quest seems to be working fine however Void Hounds have wrong size and Cannon has wrong flags set. Quest fixed
