### ISSUE TITLE
[Quest] Return my Remains

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#648]
Description:

I cannot pickup Farseer Grimwalker's remains to start the quest "Return my Remains", this is a horde only quest.

How to reproduce:
My class is a druid , I am level 80. I am at Farseer Grimwalker's remains . Which is where, I am supposed to pickup his remains, for this quest: https://wotlk.evowow.com/?quest=11638
If yall want to reproduce, maybe yall can try and start the quest on a horde character. 

How it should work:
I should be able to go to Farseer Grimwalker's body, I should be able to pick up his remains to start the quest "Return my Remains".  Here is the quest link: https://wotlk.evowow.com/?quest=11638

**Comment by alexspew** [comment]
Quest confirmed working fine. Object has a respawn time of 300 seconds, someone must've looted it before you. Also this quest requires you to have completed Kaganishu - 11637 before you can start this quest.
