### ISSUE TITLE
Apothecary Hummel Reward

### ISSUE THREAD

**Issue by Jsanzo97** [SallyWhitemane/Mograine#656]
**Description:**

Yesterday I did the Apotecary Hummel quests in group, when we killed it he drop me a tanky neck (Shard of Pirouetting Happiness) which was better than the neck that I had equipped so I change them and I sell my old neck (Amulet of Authopsy from Heigan the Unclean in Naxx 10) and I equip my new neck. After that i disconnect until today. When i log in the game I had a letter in my mailbox saying that "There was a problem equipping your item" and my new neck attached, the Apotecary Hummel's neck now is only for level 85 or more and I think that this has no sense due to the maximum level is 80 so it should be equippable

**How to reproduce:**

Kill the Appotecary Hummel and equip the item drop, the log out and log in

**How it should work:**

I think that items dropped should be for level 80 and not for level 85

**Comment by alexspew** [comment]
Neck from the event is only suppose to be valid when Ulduar releases. Sorry!
