### ISSUE TITLE
Utgarde Keep

### ISSUE THREAD

**Issue by boostedmonkey** [SallyWhitemane/Mograine#660]
**Description:**
![Untitled](https://user-images.githubusercontent.com/25875469/107122671-5b8a3000-6899-11eb-8d54-f29794485a75.png)
This pack in Utgarde Keep seems to have spawned duplicates, its not the best proof but u can see both packs u typically kill to go through here. One pack has double the mobs (its the pack near the end of that room, not the start), the only mobs that didn't duplicate in that pack are the drake and the rider.

(Its the dead pack of mobs right in front of me, not the alive drake in the back)

**How to reproduce:**
Not sure, it was through RDF if that helps at all. I'd guess u just zone in and it happens. Only saw it this 1 time.

**How it should work:**
The pack shouldn't duplicate any mobs.

**Comment by scrublama** [comment]
noticed it happening today
![WoWScrnShot_040721_014521](https://user-images.githubusercontent.com/24984413/113791063-153f3900-9743-11eb-90aa-6d15d0683b7d.jpg)
