### ISSUE TITLE
Quest "Still At It"

### ISSUE THREAD

**Issue by Ciclope69** [SallyWhitemane/Mograine#662]
**Description:**
The quest "Still At it" from Scholazar Basin doesnt works properly.

**How to reproduce:**
When the mob ask u for add ingredients like the 3 fruits, doesnt count at all, only counts when he ask for use the Brazier or the pressure valve.

**How it should work:**
It should work when u use any of the 5 actions, not only the brazier or pressure valve

**Comment by TemaZpro** [comment]
All described upper is true.

**Comment by Bolt892** [comment]
Yep

**Comment by alexspew** [comment]
Duplicate --> https://github.com/SallyWhitemane/Mograine/issues/607
