### ISSUE TITLE
Darkclaw Lobster location

### ISSUE THREAD

**Issue by alexandre-costa-81** [SallyWhitemane/Mograine#665]
**Description:**
Hi, I looked for Darkclaw Lobster in Bay of Storms and I can't catch it. Where can I find it? In the official database and on other servers it says that's there.

**How to reproduce:**
Go to Bay of Storms and try fish.

**How it should work:**

**Comment by nightcat91** [comment]
I can confirm, Darkclaw Lobster cant be fished anywhere in Azasha and the Bays, tried multiple spots where it normally works

**Comment by alexspew** [comment]
Related to -> https://github.com/SallyWhitemane/Mograine/issues/501. I've linked ur report thanks!

**Comment by Kepquet** [comment]
related but never solved
