### ISSUE TITLE
[Love Is In The Air] No "Heart-Shaped Box" reward from dungeon finder "Crown Chemical Co."

### ISSUE THREAD

**Issue by hgpdbg** [SallyWhitemane/Mograine#668]
When you queue for "Crown Chemical Co." using the dungeon finder tool you are supposed to get an item called "Heart-Shaped Box" after you finish the dungeon.

Sadly, I've queued on the first and second days of the event and did not get the said reward while the dungeon finder tool showing I was available for the loot.

I've also got reports from others players that got the item itself, so I'd like to know if I can get this issued fixed and get the boxes I missed this two days!

Here are some links to the item and to the npc from the dungeon:

https://www.wowhead.com/item=54537/heart-shaped-box#comments
https://www.wowhead.com/npc=36296/apothecary-hummel

Thanks.

**Comment by annaqtie** [comment]
DM me on discord, I’ll try to help you and get it solved. Your issue isn’t really for GitHub.

**Comment by Veresa** [comment]
The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.

**Comment by hgpdbg** [comment]
> The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.

Are you trying to say I need to choose between the daily rhc reward or the box? If that's the case that is not intended as you could do both the random hc daily and the event daily during WotLK retail times.

**Comment by Veresa** [comment]
> > The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.
> 
> Are you trying to say I need to choose between the daily rhc reward or the box? If that's the case that is not intended as you could do both the random hc daily and the event daily during WotLK retail times.

Up to now I have always had to choose, if there is a way to get them both I don't know.
There are some events that give you emblems as well but I think that's something added later.

**Comment by hgpdbg** [comment]
> > > The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.
> > 
> > 
> > Are you trying to say I need to choose between the daily rhc reward or the box? If that's the case that is not intended as you could do both the random hc daily and the event daily during WotLK retail times.
> 
> Up to now I have always had to choose, if there is a way to get them both I don't know.
> There are some events that give you emblems as well but I think that's something added later.

The quests you are talking about are the ones that show up next to violet hold entrance, those show up everyday.
I'm talking about the daily valor emblems you get for queuing the 1st rhc of the day

**Comment by Veresa** [comment]
> > > > The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.
> > > 
> > > 
> > > Are you trying to say I need to choose between the daily rhc reward or the box? If that's the case that is not intended as you could do both the random hc daily and the event daily during WotLK retail times.
> > 
> > 
> > Up to now I have always had to choose, if there is a way to get them both I don't know.
> > There are some events that give you emblems as well but I think that's something added later.
> 
> The quests you are talking about are the ones that show up next to violet hold entrance, those show up everyday.
> I'm talking about the daily valor emblems you get for queuing the 1st rhc of the day

I'm talking about the join too.
The choice is or this https://ibb.co/XtQM4Vc or this https://ibb.co/Lhz6tyN, I hope they show up.

**Comment by hgpdbg** [comment]
> > > > > The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.
> > > > 
> > > > 
> > > > Are you trying to say I need to choose between the daily rhc reward or the box? If that's the case that is not intended as you could do both the random hc daily and the event daily during WotLK retail times.
> > > 
> > > 
> > > Up to now I have always had to choose, if there is a way to get them both I don't know.
> > > There are some events that give you emblems as well but I think that's something added later.
> > 
> > 
> > The quests you are talking about are the ones that show up next to violet hold entrance, those show up everyday.
> > I'm talking about the daily valor emblems you get for queuing the 1st rhc of the day
> 
> I'm talking about the join too.
> The choice is or this https://ibb.co/XtQM4Vc or this https://ibb.co/Lhz6tyN, I hope they show up.

Damn Veresa, I just confirmed your theory and you are right. The rhc first dungeon of the day reward is overwriting the event dungeon reward, so you can only do one of the two per day. Pretty sure it's not as it's supposed to work but i'll look into it

**Comment by Veresa** [comment]
> > > > > > The box works like the 2 Valor of the DF hero, you have to choose one of the 2 daily.
> > > > > 
> > > > > 
> > > > > Are you trying to say I need to choose between the daily rhc reward or the box? If that's the case that is not intended as you could do both the random hc daily and the event daily during WotLK retail times.
> > > > 
> > > > 
> > > > Up to now I have always had to choose, if there is a way to get them both I don't know.
> > > > There are some events that give you emblems as well but I think that's something added later.
> > > 
> > > 
> > > The quests you are talking about are the ones that show up next to violet hold entrance, those show up everyday.
> > > I'm talking about the daily valor emblems you get for queuing the 1st rhc of the day
> > 
> > 
> > I'm talking about the join too.
> > The choice is or this https://ibb.co/XtQM4Vc or this https://ibb.co/Lhz6tyN, I hope they show up.
> 
> Damn Veresa, I just confirmed your theory and you are right. The rhc first dungeon of the day reward is overwriting the event dungeon reward, so you can only do one of the two per day. Pretty sure it's not as it's supposed to work but i'll look into it

Thx man :D
I think it should work like this but I don't know until what patch.
It could be Ulduar or ToC or ICC, here I have doubts too.
