### ISSUE TITLE
Quest: Take their rear! ID12216

### ISSUE THREAD

**Issue by nesferatuh** [SallyWhitemane/Mograine#681]
**Description:**
Quest item: Grizzly Flank (ID: 37200) doesn't drop.

**How to reproduce:**
Anderhol at Amberpine Lodge wants you to collect 8 Grizzly Flanks from the Grizzly Bears in Grizzly Hills.

**How it should work:**
Slay the grizzly and collect the drops until 8 and turn in the quest.

**Comment by nesferatuh** [comment]
Source: https://www.wowhead.com/quest=12216/take-their-rear

**Comment by alexspew** [comment]
Hi!, Quest fixed, increased the drop rate.
