### ISSUE TITLE
Drop item "Black pearl"

### ISSUE THREAD

**Issue by Naskyy** [SallyWhitemane/Mograine#683]
**Description:**
Hello I faced issue with "Black pearl".

**How to reproduce:**
It's says that it dropps from "Big-mouth Clam".

**How it should work:**
It actually never dropped so far farmed it like 150 "Big-mouth Clam" never seen it so far.

**Comment by alexspew** [comment]
Hi, Black Pearl is one of the rarest crafting materials from Big-mouth Clam. There is lots on AH, meaning it should drop.

**Comment by Naskyy** [comment]
Hello.
 I have checked ,it’s rare but I received every single item except the Black Pearl even one of them-Iridescent Pearl .I had it 10 times,which has Lower rate!

**Comment by alexspew** [comment]
Hi, an update to the ticket. Big-mouth Clam has been updated
