### ISSUE TITLE
No valor points

### ISSUE THREAD

**Issue by willse2414** [SallyWhitemane/Mograine#685]
**Description:**
So i did random hc yesterday before i did the love is in the air event and i didnt recieve a box.
Today i did the love is in the air before i did my daily heroic and now i cant recieve valor points from my daily heroic.

**How to reproduce:**

**How it should work:**

**Comment by Veresa** [comment]
It should be like this https://github.com/SallyWhitemane/Mograine/issues/668

**Comment by willse2414** [comment]
I did not get any valor from the heartshaped box either.

**Comment by Veresa** [comment]
> I did not get any valor from the heartshaped box either.

From what I remember I believe that the addition of the emblems in the DF event is something later, for the moment we have to choose.

**Comment by willse2414** [comment]
I am 100% sure its not suppose to be like this

**Comment by Veresa** [comment]
In later patches I'm sure the emblems are given from the event box but at first I'm not sure.
