### ISSUE TITLE
[Quest] Assault by ground, multiple quest givers

### ISSUE THREAD

**Issue by xaring** [SallyWhitemane/Mograine#689]
**Description:**
There are multiple NPCs where there shouldnt be
![image](https://user-images.githubusercontent.com/22470824/107155527-3967df00-6979-11eb-9453-b1e26c1829b3.png)

**How it should work:**
Only 1 should exist.
https://discord.com/channels/738431894823108629/803414621112500244

**Comment by alexspew** [comment]
Invalid. It's a squad leader for a reason, there's troops behind him. Was the case on retail as well.
