### ISSUE TITLE
[Quest] The Brothers Bronzebeard

### ISSUE THREAD

**Issue by xaring** [SallyWhitemane/Mograine#690]
**Description:**
The Brothers Bronzebeard quest is not able to be completed as the mobs double spawn and shoot down the plane before you can leave the Engine of the Makers. 

**How to reproduce:**
Accept the quest and be shot down every time.

**How it should work:**
Much less mobs spawn, and they are supposed to jump on the plane to be killed by the player.

**Comment by Taskforce84** [comment]
This is also happening to me, unable to complete quest due to overtuned double spawns.

**Comment by alexspew** [comment]
Hey guys! Duplicates are being removed soon enough. Sorry for the long time it tok
