### ISSUE TITLE
[Rogue] Vanish

### ISSUE THREAD

**Issue by ruireis97** [SallyWhitemane/Mograine#691]
**Description:**
Vanish isn't getting rogues out of combat in boss fights in raids.

**How to reproduce:**
You can test it out in a boss encounter. When you vanish as rogue you don't get out of combat.

**How it should work:**

When you vanish in the middle of a boss encounter in a raid, you get out of combat for 0.1secs, which enables the reset of the CD from the potion of speed.
Most classes use 2 potions of speed per encounter (max), rogues can use 2, then 1 per vanish.

**Comment by SallyWhitemane** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/5023
