### ISSUE TITLE
[Quest] Not able to accept A Cold Front approaches

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#694]
https://wotlk.evowow.com/?quest=13070 "A Cold Front Approaches"
Desc: I cannot accept the quest. Upon originally accepting the quest it was in my quest log and I couldn't find the turn in NPC. After looking for a while online, i discovered he wasn't there. I abandoned the quest and con no longer accept it.
Screenshots:
https://imgur.com/a/IXnJi2l

**Comment by alexspew** [comment]
Hi, this quest chain has been fixed as of a few days ago, if issue persists please make a new bug report. Thanks!
