### ISSUE TITLE
[Paladin] Switching from prot to ret doesn’t remove aggro from RF

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#695]
Description:

If you are in Naxx25, if you go prot spec as a ret, turn on RF, and then go back to ret, it seems as if your threat from RF stays even tho its not active anymore, so in turn you end up pulling the threat very easily. Had it happen after respeccing on Gluth to prot and going back ret on Thaddius sapph and KT, alt f4 doesn't fix it.

How to reproduce: Just go prot enable RF and try going ret, your threat should spike up way above tanks threat on a boss like Sapph lets say.

How it should work: 

Having no Righteous Fury on shouldn't spike up your threat like that.

**Comment by Spartanv** [comment]
I have the same issue on my ret with prot offspec

**Comment by kyotpls** [comment]
This problem happens every time for me as well, and it seems this might be the reason for the insane threat over tanks in raids. I can be botton of DPS, but still highest on threat. It makes no sense. It must be something with RF threat still being on, even without the buff enabled in regarding to dual spec.
