### ISSUE TITLE
[Sons of Hodir] Rep getting lowered using the badges

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#697]
Description: 

Sons of hodir rep getting lower by using the commendation badge.

How to reproduce:

Be hated with sons of Hodir and use commendation badge and that will increase the hated rep (noticed this at 2k hated rep with sons of hodir)

How it should work:

It should become less hated.

**Comment by mrnuggets** [comment]
The guy posting this report probably hasn't finished the 'Sons of Hodir' quest chain.

**Comment by alexspew** [comment]
Player needs to do Sons of Hodir quest chain.
