### ISSUE TITLE
[Sons of Hodir] Can't interact with NPC's

### ISSUE THREAD

**Issue by Discopak** [SallyWhitemane/Mograine#699]
**Description:**
The NPC's are shown as friendly, yet I can't interact with them whatsoever. They show quests like they should but I'm not able to turn them in or pick them up. Also when I dismount, I can attack them.

 **How to reproduce:**
I did the Questchain to get Friendly with them, after that I accepted all the quests King Jokkun offered, did the one where I had to use "Snorri" to kill 10 Elementals and return an Amboss, after that, I left, abandoned all the other Quests after deleting the Items first.

**How it should work:**
Well, I should still be able to interact with them even after abandoning all the quests and deleting the Quest Items

**Comment by bjh368** [comment]
Are you "at war" with them in your reputation tab?

**Comment by Discopak** [comment]
> Are you "at war" with them in your reputation tab?

Yes, I actually am. I don't know why it even swaped to it. Thanks
