### ISSUE TITLE
[Roleplay] Barmaids doesn't responds to emotes

### ISSUE THREAD

**Issue by Synful-Syn** [SallyWhitemane/Mograine#7]
According to the wowhead comments about Kylene, NPCs should responds to some emotes.

Kylene on wowhead: https://www.wowhead.com/npc=19186/kylene#comments:id=190361

Other barmaids
Frances Lin in Southshore inside Old Hillsbrad: https://www.wowhead.com/npc=20401
Gwenna Firebrew https://www.wowhead.com/npc=5112
Edris Barleybeard https://www.wowhead.com/npc=5140
Elly Langston https://www.wowhead.com/npc=1328

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
