### ISSUE TITLE
Penance

### ISSUE THREAD

**Issue by Alceo1** [SallyWhitemane/Mograine#701]
**Description:**
Penance is supposed to be 3 tick but you get only 2 if you'r getting any domage during the chaneling

**How to reproduce:**
Make sure you aint got ANY shield on and penance yourself or an enemy while getting dmg.

**How it should work:**
Penance should be 3 tick no matter any domage you are taking during the chaneling

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
