### ISSUE TITLE
Gargoyle follows instead of staying at it's current position.

### ISSUE THREAD

**Issue by AndreiGameDev** [SallyWhitemane/Mograine#702]
**Description:**
Gargoyle after the recent "fix" for gargoyle started following the target instead of staying where it got summoned and keep attacking. I've tested if it might act like a ghoul when it's summoned but it's the same result, gargoyle is following the target into melee.

**How to reproduce:**
Summon gargoyle from like 10-15 yards away from a dummy and start attacking it with or without ghoul.

**How it should work:**
It should remain where it got casted and not move at all.
https://www.youtube.com/watch?v=kDy2kdGB_xc&feature=youtu.be
https://www.youtube.com/watch?v=ULOHTGTPFXk&feature=youtu.be

**Comment by alexspew** [comment]
Hi, this should be resolved on next server restart!
