### ISSUE TITLE
[Quest] Seek out Neltharaku patrolling wrong place

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#707]
Description:

Seek Out Neltharaku(netherwing 2nd quest)
How to reproduce:

If you go to shadowmoon valley, you should see him flying around just south of Sanctum of Stars.

How it should work:

He should be flying around in the air so you can turn in quest/talk to him. https://www.youtube.com/watch?v=o36K8dmph2c

**Comment by alexspew** [comment]
Duplicate -> https://github.com/SallyWhitemane/Mograine/issues/406
