### ISSUE TITLE
[Quest] Thrusting Hodirs Spear glitch inside textures

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#711]
Description:

In the quest Thrusting Hodir's Spear, the wyrm took me into one of the mountains (through the face of the mountain and into the middle of some mountain that I shouldn't be able to enter)

How to reproduce:

Do the quest Thrusting Hodir's Spear and if the Wyrm's path takes you towards the face ofa  mountain it will likely take you into the center of the mountain.

How it should work:

If the Wyrm runs into a mountain it shouldn't go through the mountain wall, instead it should be blocked by the wall and take another path or just keep running into the wall.

**Comment by alexspew** [comment]
Most likely related to -> https://github.com/SallyWhitemane/Mograine/issues/393
