### ISSUE TITLE
[Quest] Chill Out, Mon

### ISSUE THREAD

**Issue by bjh368** [SallyWhitemane/Mograine#713]
The quest Chill Out, Mon in Grizzly hills, is bugged so that you cannot complete it. 
You need to use the item "snow of eternal slumbers" on a troll ghost in the main room of the tomb. The ghosts are there, and you can see even track them with "track undead" but you cannot target them, and thus your item doesn't trigger the quest progress. 

The other day I found 1 of the troll ghosts to be targetable, but today that particular troll was just like all others in the room. 

I've tried deleting cache but it has no effect on the matter.

**Comment by alexspew** [comment]
Quest seems to be working fine now? Please contact me on discord bjh368. alexs on discord.
