### ISSUE TITLE
[Netherwing][Quest] After getting exalted missing follow up to buy the drakes

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#715]
Description:

After getting exalted with the netherwing I dont get the follow up quest that takes me to netherwing ledge where I can buy a netherwing drake.

How to reproduce:

After I did the quest "Ally with the netherwing" at the NPC Mordenai in shadowmoon valley (outland) I dinged exalted because of reputation boost but did not recieve the follow up quest "Blood Oath of the Netherwing". If you wanna recreate the bug you will need to do the questline that starts at Mordenai in shadowmoon valley. The first quest is called "kindness".

How it should work:

The NPC Mordenai should give you the quest "Blood Oath of the Netherwing" and then you speak to him again to complete it. And then he should give you the quest "In service of the illidari" that makes you go to netherwing ledge disguised as an orc. This disguise makes it possible to interact with the npcs at netherwing ledge as friendly npcs. Buy from the drake vendor, take quests etc.

Here is a video: https://www.youtube.com/watch?v=MPccWr_ZI74

I couldnt find this already reported anywhere, but if you are already aware of this bug im sorry to have bothered you. Hope it gets fixed when you have time, it is still the best looking mounts ingame :3

**Comment by alexspew** [comment]
Requires 300 flying to proceed.
