### ISSUE TITLE
[Feral] T7 2x bonus not working

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#717]
Description:

Bonus of 2xT7 for feral druid does not work. 

How to reproduce:

Feral dps use 2xt7

How it should work:

Rip should last 24s with 2xT7 as u see the duration of rip is 20s
![91E75C77-1199-4721-AFB6-AF5402146EB7](https://user-images.githubusercontent.com/78295842/107263196-22dd8880-6a4a-11eb-8784-d4dcd202fe21.png)

**Comment by sicknot1** [comment]
is it fixed?

**Comment by styxel** [comment]
> is it fixed?

Rip is 12s + glyph 16s + 2set = 20s
