### ISSUE TITLE
Kungaloosh Quest 'Still At It'

### ISSUE THREAD

**Issue by cashil124** [SallyWhitemane/Mograine#720]
The quest "Still At It" in Sholazar Basin doesn't trigger when I click on a fruit to add to the still to progress the quest so it fails every time. 

**How to reproduce:**
Try the quest 'Still At It' - the game doesn't recognize a fruit being clicked on

**How it should work:**
The game should be able to progress the quest and not auto fail it when I click what I am supposed to

**Comment by alexspew** [comment]
Duplicate --> https://github.com/SallyWhitemane/Mograine/issues/607
