### ISSUE TITLE
Valkyrion Aspirant

### ISSUE THREAD

**Issue by WubWub24** [SallyWhitemane/Mograine#73]
Valkyrion Aspirant 29569  are missing Metanoia 57524.
Proof : 
![WoWScrnShot_121120_173915](https://user-images.githubusercontent.com/73794095/101923278-e0c5d100-3bd7-11eb-8f20-c12bd87b4094.jpg)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
