### ISSUE TITLE
Netherwing drake storyline BUG

### ISSUE THREAD

**Issue by Slaugh101** [SallyWhitemane/Mograine#730]
**Description:**

I did the Netherwing questline that starts with the quest "Kindness"
i did all the quests up to "Ally of the Netherwing" wich got me exalted with netherwing.
The NPC Mordenai should hand out a new quest called "In Service of the Illidari" wich will make me able to speak/be friendly with the drake dealer on Netherwing ledge to buy the mount.
But Mordenai doesnt hand out any new quest after "Ally of the Netherwing" so im hostile to everyone on Netherwing ledge.

How to fix this?

**Comment by Raulfin** [comment]
'Blood Oath of the Netherwing' is the continuation of the Netherwing quest line to obtain the nether drake flying mount. Players must be neutral with Netherwing (by completing the Ally of the Netherwing quest chain) and have Artisan riding skill (300) to accept this quest.

-'Blood Oath of the Netherwing'
--'In Service of the Illidari'
---'Enter the Taskmaster'

**Comment by alexspew** [comment]
You need to have 300 flying.

**Comment by Slaugh101** [comment]
Ok, thanks for clearence!
