### ISSUE TITLE
Halls of Lightning

### ISSUE THREAD

**Issue by Tottori97** [SallyWhitemane/Mograine#74]
Description: Halls of Lightning mobs - Titanium Thunderer & Titanium Siegebreaker are all active. Also, Titanium Siegerbreaker's should cast a fear, (https://www.wowhead.com/spell=19134/frightening-shout or https://www.wowhead.com/spell=29544/frightening-shout).
Furthermore, the drop rate of Relics of Ulduar in the dungeon seems to be a bit too low, all of us managed to get only 2-3 Relics throughout the whole dungeon.

How to reproduce: Just run HoL once and see for yourself, in particular the Titanium mobs room.

How it should work: The mobs should not all be active, they should normally be non interactive unless activated, and only a portion of them should activate, not all. The Siegebreaker's should also cast Fear, which currently they do not. Relics of Ulduar should also drop more often, in particular from mobs, as almost all of the ones we acquired were only from bosses.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
