### ISSUE TITLE
Crown Chemical Company Dungeon Issue

### ISSUE THREAD

**Issue by Stormmenace** [SallyWhitemane/Mograine#740]
**Description:**
This dungeon dropped a piece of level 85 gear gear, or rather, a piece of gear requiring a player level of 85 to equip.

**How to reproduce**

**How it should work:**
A level 80 piece of gear.

**Comment by Raulfin** [comment]
Making them lvl 85 was the fix so that playes had to wait untill Uld comes out to use them, returning them to lvl 80 should be part of that patch. Since ilvl 226 gear was not available untill Uld.

**Comment by Stormmenace** [comment]
Gotcha - just making sure it wasn't a bug :)
