### ISSUE TITLE
[Druid] Mangle isn’t automatically learned

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#741]
**Description:**
Mangle (Bear) and Mangle (Cat) are not being automatically learned by druids:
I was buying my Swift Flight form from the Druid Trainer (not sure if this is intended too) and I noticed I could learn the rank 2 of the skills Mangle (Bear) and Mangle (Cat).
My spellbook showed I only had the Rank 1 of those skills and I had to manually learn them.

**How it should work:**
Like all the other skills, these skills have to be automatically learned during leveling.

**Comment by Raulfin** [comment]
dup of #364
