### ISSUE TITLE
[Item] Black Pearl drop% too low 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#752]
**Description:**
Drop chance of [Black Pearl] isn't right i think.
 
In WotLk DB there is 1% drop chance from [Big-mouth Clam] to get [Black Pearl]. After 500 opened clams still don't have it is little bit strange. Usually it drops between 160-260 clams how i normally get on other servers (not Fun servers). I met some other players which they farm it for 3 day and still nothing. But on Ally AH there is one guy who sell it everyday. Maybe there is bug somewhere. But you have to know more about it.

**How to reproduce:**
Try to open 500 clams. You will find if me and others are unlucky or its just doesn't drop.

**How it should work:**
On other servers i usually get it between 160-260 Clams. Do you think you should't get 1% drop once?

PS: GM recommend me to write here from ticket. 

Thank you.

**Comment by alexspew** [comment]
Droprate is fairly low, i've tested on dev realm myself. It's all RNG! I opened 60 of big-mouth clams and I got one.
