### ISSUE TITLE
[Cooking] Giant clam meat low drop%

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#758]
Found a bug related to Big-mouth Clams, they drop Giant Clam Meat instead of Zesty Clam meat, there is no way to farm zesty clam meat without the clams and they are bugged

already opened like 50 and just got pearls and giant clam meat, not zesty clam meat

**Comment by alexspew** [comment]
Hi, thanks! Loot-table for Big-mouth Clams has been updated.
