### ISSUE TITLE
Frost DK talent bugged

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#76]
Chill of the Grave talent is broken and procs when you whitehit and heal yourself with the passive healing from Blood Presence. It should only proc from Chains of Ice, Howling Blast, Icy Touch and Obliterate

**Comment by Fulgurancex** [comment]
can confirm you get runic power off autoattacks but wasnt sure what caused it . Yesterday it didn't happen

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
