### ISSUE TITLE
Cant complete The Hero's Arms quest in storm peaks

### ISSUE THREAD

**Issue by Xoomie81** [SallyWhitemane/Mograine#760]
**Description:**
spent about an hour farming elementals that the tooltip said should of dropped the two items i need. looked it up and its supposed to be from looting baskets that are non-interactive. Not sure what to do.

**How to reproduce:**
not sure this applies

**How it should work:**
i shouldn't spend an hour on any quest. items should be accusable

**Comment by Xoomie81** [comment]
still havnt got it but i watched a video on wowhead and its from killing the elementals just like the tooltip said,

**Comment by alexspew** [comment]
You need to kill Scion of Storm Elementals. It has a fairly low drop chance (under 10%), quest works fine.
