### ISSUE TITLE
[Arena] (Important) Replenishment buff from ret paladin (and maybe other's replenishment buff) doesn't work in arena

### ISSUE THREAD

**Issue by artchebelum** [SallyWhitemane/Mograine#761]
**Description:**
All is in the title : the replenishment buff still doesn't work in arena and make it hard for certain comp to sustain mana. 
Pretty sure it works in bg/wg but not in arena 100% sure.

**How to reproduce:**
Step in arena, try to proc it, doesn't proc.

**How it should work:**
The replenishment buff should exist in arena

**Comment by Zeorgbugfinder** [comment]
replenishment on who?
check if u have it in arena after u jug

It should not be on other ppl just on you its how it should work in arena
