### ISSUE TITLE
[Quest][Hellfire Peninsula]Void Ridge - Vacillating Voidcallers do not leave a lootable body

### ISSUE THREAD

**Issue by wesliel** [SallyWhitemane/Mograine#764]
**Description:**
For this quest, players should be able to kill both Vacillating Voidcallers or Collapsing Voidwalkers to obtain Void Ridge Soul Shards. Vacillating Voidcallers currently would not leave a lootable body when dying.

The quest is still doable, as Collapsing Voidwalkers work fine.

**How to reproduce:**
Obtain the quest, kill mobs.

**How it should work:**
It should not disappear but should leave a body for looting.

**Comment by alexspew** [comment]
Hi, thanks! Fixed
