### ISSUE TITLE
Thunderstorm useable in sap

### ISSUE THREAD

**Issue by tii86** [SallyWhitemane/Mograine#766]
**Description:**
Thunderstorm is currently usable when you're sapped. This spell can be cast in stuns, but not other forms of crowd control.

**How to reproduce:**
1. Get Sapped.
2. Press thunderstorm.
3. Watch the enemy rogue go :O

**How it should work:**
Thunderstorm should not work in sap.

Other potential cases worth testing are
1. Is thunderstorm castable in hunter trap?
2. is pain suppression castable ~~in hunter trap?~~ In sap?

The answer for both should be no; only stuns and when you're character is free of cc.

**Comment by achrysan** [comment]
Actually Pain Suppression SHOULD be castable even if the caster is in hunter freezing trap. You are correct about the other cases.

**Comment by truepojkee** [comment]
its not fixed,

**Comment by truepojkee** [comment]
ITS NOT! - https://youtu.be/_xA_1KnMs3k
