### ISSUE TITLE
Leaving arenas and dodging losses

### ISSUE THREAD

**Issue by tii86** [SallyWhitemane/Mograine#767]
**Description:**
If your teammate dies in a 2v2 match and you are able to leave the arena, your personal rating and w/l are not affected.

**How to reproduce:**
1. Watch your teammate die in one of many innumerable situations. 
2. Run away / LOS / re-stealth / shadowmeld to drop combat
3. Click leave arena

**How it should work:**
Regardless of whether you leave arena, the losses should be correctly applied to your personal rating.

----

Currently since it is not possible to leave arenas while you're in combat (also annoying) it prevents this issue from getting out of hand. However, on sunwell the exact same bug occurred but additionally they fixed the combat related arena leaving bug... This allowed everyone to dodge losses and subsequently inflate mmr. This in my opinion contributed to the extreme rating inflation that sunwell experienced.

This assumes that mmr is calculated based on personal rating --> inflated mmr --> get more points for wins --> whole ladder inflates.

**Comment by SallyWhitemane** [comment]
We've blocked leaving rated arenas, so this issue is fixed.
