### ISSUE TITLE
Missing NPC

### ISSUE THREAD

**Issue by CryWolff** [SallyWhitemane/Mograine#770]
**Description:**
Npc Bronn Fitzwrench missing

**How to reproduce:**
Go outside of Everlook ( 60 , 40 coord ) and check

**How it should work:**

This goblin should be there, giving a repetable quest ( https://wotlk.evowow.com/?quest=9266 ) to increase rep

**Comment by alexspew** [comment]
Unable to reproduce. NPC is spawned
