### ISSUE TITLE
 [Stranglethorn Fever] doesnt work (heart of mok)

### ISSUE THREAD

**Issue by truepojkee** [SallyWhitemane/Mograine#779]
**Description:**
 [Stranglethorn Fever] doesnt work,. the guy who had summ him - do nothing and he dont have prequest

**How it should work:**

should work.

**Comment by alexspew** [comment]
Hi,

Do you have the first Stranglethorn Fever quest from Fin Fizracket?

**Comment by truepojkee** [comment]
which one?

**Comment by truepojkee** [comment]
https://www.youtube.com/watch?v=utmhme6DMK8
Look how it should work. 
part1: take quest from Fin Fizracket
par2: go to cave to Doctor Unbangwa and start quest , which will summ Mok.

part 2 doesnt work. But its mean whole quest - doesnt work

**Comment by alexspew** [comment]
Yes, he should have a quest for you to accept, and to turn that in you need a "Gorilla Fang", are you saying he doesn't have any quest when you are there?

**Comment by alexspew** [comment]
I made some changes to the quest, should be live within the week! Hopefully that will stop it from bugging out
