### ISSUE TITLE
Pylon quests Un'goro Crater (North East West)

### ISSUE THREAD

**Issue by whitemanetribe** [SallyWhitemane/Mograine#78]
**Description:**
When you interact with the pylons in un'goro the quest should complete. The dialogue works but the quest doesn't complete/progress.

**How to reproduce:**

**How it should work:**
When you interact with the pylons in un'goro the quest should complete. The dialogue works but the quest doesn't complete/progress.

**Comment by AugustFloden** [comment]
Similar to the reported issue last PTR, see video for reference:
https://github.com/SallyWhitemane/Mograine/issues/41

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
