### ISSUE TITLE
[Quest] Call of Fire

### ISSUE THREAD

**Issue by nesferatuh** [SallyWhitemane/Mograine#783]
**Description:**
Retrieve Hauteur's Ashes an then return them and the Ritual Torch to Temper at Emberglade on Azuremyst Isle. Remember  that you can use the Orb of Returning to teleport back to Temper once you have the ashes.

**How to reproduce:**
There is no Torch.

**How it should work:**
Collect torch
Collect ashes
Use Orb to teleport back and turn in.

**Comment by alexspew** [comment]
Invalid, torch is added when you right click the bag provided by quest.
