### ISSUE TITLE
shamans able to use Thunderstorm in sap. 

### ISSUE THREAD

**Issue by truepojkee** [SallyWhitemane/Mograine#788]
**Description:**

shamans able to use Thunderstorm in sap. 
**How to reproduce:**
get shaman sap > he will knock you back while sapped. ITs bug. 
evidence - https://youtu.be/_xA_1KnMs3k

**How it should work:**
only usable in stuns.

for this dev, who said, sap is stun > https://imgur.com/a/JoxIEtg
Sap is incapacity effect, not STUN effect. 
Holy shit that's worts thing I ever hear for me entire life

incapacity effect BREAKS once u do damage on target who incapacited. Thats how it works.
And stun effect not breaks once u do damane on stunned target. thats how stun works. 
If u hit sapped target - sap breaks. 
1 more evidence is a incapacity effect, not stun

**Comment by Raulfin** [comment]
dup of #766 which is fixed and on the changelog for next update.

**Comment by alexspew** [comment]
Hi,

There is no reason to be rude, you can have a discussion without you throwing stuff around. This was applied today 
Rework SPELL_ATTR5_USABLE_WHILE_STUNNED handling, fix thunderstorm useable in sap. Close: #766

It was blizzard who put the tag "Stun" on "Sap" Spell, if you want to blame them for anything.

**Comment by truepojkee** [comment]
blizzard never tag "Stun" on "Sap"
https://imgur.com/a/Ya85pA5

it was incapasity and then > sap is sap
