### ISSUE TITLE
[Druid][Balance] Eclipse (Lunar) proc chance

### ISSUE THREAD

**Issue by ghuser44** [SallyWhitemane/Mograine#79]
**Description:**
I don't know if it's just bad RNG, or a bug, but, in these first 2 days of PTR, my **Eclipse (Lunar)** procs have been terrible. I went up to **14** Wrath casts (and on 1 occasion: **17** casts) - with Avg. of 9 critical hits - before getting any **Eclipse (Lunar)** proc, on many fights, and multiple times per fight, as well. That's a lot of casts and crit hits, **with no procs**, for a **60%** proc chance off of a Wrath crit, no?

Can you, please, check the numbers on this and make sure it's properly coded? If it is, then I'm just unlucky, I guess.

**How to reproduce:**
I was in **full Tier 7.5 bis Moonkin gear**. Tested in Naxxramas and Ulduar (fully buffed) and on G.T. Dummy, in GM island (self buffed, no food).

**How it should work:**
I don't know the exact math behind this but it certainly shouldn't take me 17 casts to get 1 Eclipse proc.
My Wrath casts had, consistently, more than 50% crit counts, Avg. around 66.7% (approx.). So, 1 in 2 casts is a crit, yet I took dozens of casts to get off a proc.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
