### ISSUE TITLE
[Quest] Honor is for the Weak 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#797]
**Description:** [Quest ID:13170] Honor is for the Weak is bugged. The shade for the aforementioned is supposed to be stealthed (only the hounds have a higher detection range).

**How to reproduce:** Pick up the quest and try to do it.

**How it should work:** The shade is meant to be stealthed so you can sneak up to the lookouts and assassinate them - the whole point of being able to distract the hounds with food is that they're the only ones that can see through its stealth. The shade is _not_ stealthed, which causes the lookouts to aggro immediately and make the quest impossible to complete.

**Comment by alexspew** [comment]
Fixed on PTR, waiting for to be applied live.
