### ISSUE TITLE
[Quest] Killing Pitch in SB doesn’t enable Playing Along

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#798]
Description:

Killing Pitch in Sholazaar Basin does not enable me to pick up quest [Playing Along] from Gek Gek

How to reproduce:

Kill Pitch.

How it should work:

As soon as you kill the npc Pitch, Tracker Gek Gek is supposed to offer a quest called Playing Along. He does not do this, and when I've joined a group with a player already on [Playing Along] and they attempt to share it, they get the notification that I'm already on the quest, and I am not.

**Comment by alexspew** [comment]
Hi, please make a GM ticket next time this happens. So they can attempt to remove the quest from you, you can also try to delete your cache folder in your WoW folder.
