### ISSUE TITLE
[Quest] Rider of the Unholy quest not giving credit

### ISSUE THREAD

**Issue by mdeluca0** [SallyWhitemane/Mograine#799]
**Description:**
Killing Rokhir with the quest "The Rider of the Unholy" doesn't give kill credit.

**How to reproduce:**
Kill Rokhir with the quest.

**How it should work:**
Should get kill credit upon completion.

![WoWScrnShot_021521_230933](https://user-images.githubusercontent.com/32890117/108027632-c1885d00-6fe7-11eb-8f2c-34d3c48a37a6.jpg)

**Comment by alexspew** [comment]
Hi! Thanks, issue has been resolved.
