### ISSUE TITLE
Warchief's Blessing - some of Q-specific npc's behaviour is enabled when quest is not active

### ISSUE THREAD

**Issue by matalukes** [SallyWhitemane/Mograine#8]
Description: Some guards in Grommash Hold (Thrall room), are throwing sh**s at each other and at you as well. At other npc's they apply debuff, at you doesn't. Other parts of orgrimmar seems to work fine.

How to reproduce: I teleport to org as 80 not DK. I also tested it as alliance and it works fine.

How it should work: It's buggy behavior from [saurfangs-blessing](https://www.wowhead.com/quest=13189/saurfangs-blessing) quest, if you are not doing quest, there shouldn't be any of this behavior.

Screenshots:
![WoWScrnShot_110820_135949](https://user-images.githubusercontent.com/52035924/98465962-ceb5d480-21cc-11eb-94b0-40e26379ea76.jpg)
![WoWScrnShot_110820_140318](https://user-images.githubusercontent.com/52035924/98465964-d1b0c500-21cc-11eb-824f-7722e405e38f.jpg)

**Comment by enheken** [comment]
the quest is https://wotlkdb.com/?quest=13189 Warchief's blessing

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
