### ISSUE TITLE
[Ulduar] Winter Jormungar spawn issue

### ISSUE THREAD

**Issue by ghuser44** [SallyWhitemane/Mograine#80]
**Description:**
**Winter Jormungar** (34137) are spawning without anyone in the raid approaching the **Snow Mounds** (194907). They aggro immediately on the closest target. Also, Snow Mounds should be more visible.

**How to reproduce:**
Enter the Halls of Winter, in Ulduar (we tested it in 10m), and move in slowly. They will spawn and aggro, from afar, regardless of your positioning and whether or not you approach the Snow Mounds.

**How it should work:**
Winter Jormungar should only spawn when a Snow Mound is approached.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
