### ISSUE TITLE
[DEATH KNIGHT] Blood Tap activating 2 Death runes

### ISSUE THREAD

**Issue by Shragenator** [SallyWhitemane/Mograine#802]
Decription:
Using the blood tap ability in a certain situation causes the ability to instantly activate as death runes the 2 runes that are on cooldown in the blood rune slot.

How it works:
When specced into "Blood of the North" one can convert blood runes into death runes. In the situation where 1 death rune (in a blood rune slot) AND 1 blood rune are on cooldown simultaneously, using "Blood Tap" will instantly activate both these runes as death runes.

How it should work:
If a blood rune and a death rune (in a blood rune slot) are on cooldown, activating blood tap should instantly activate only the blood rune as a death rune, while leaving the other death rune still on cooldown.

Source (you should point out proofs of your report, please give us some source):
In game, does not match the tooltip.

**Comment by SallyWhitemane** [comment]
https://github.com/SallyWhitemane/Mograine/issues/116

**Comment by Shragenator** [comment]
This is not the same as issue #116

**Comment by Shragenator** [comment]
This is not the same issue as #116 .  

In #116 , an already activated blood rune turns into a death rune. 

In this bug, both a death rune AND a blood rune that are on cooldown (aka not available)  are both turned into ACTIVE death runes. 

This is a big difference because it means that blood tap can activate 2 runes that are on cooldown instead of one.
