### ISSUE TITLE
Totem despawns newly summoned totem

### ISSUE THREAD

**Issue by tdymel** [SallyWhitemane/Mograine#81]
**Description:**
Okay, this is a situation that happens a lot during raids. As Enhancer you have the Magma Totem in your rotation that lasts 20 seconds, so you resummon it all the time. The issue is the totem does not actually despawn after 20 seconds but it "casts(?)" some sort of despawn spell onto the totem at about 20.5secs such that if you resummon the totem at like 20.3, the old totem despawns the new one, which is quite frankly very very annoying.

**How to reproduce:*
1. Cast Magma Totem
2. Wait until it expires
3. Resummon it right when it despawns

**How it should work:**
Should not despawn the new totem

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
