### ISSUE TITLE
[Paladin][Holy] BoL and LOS interaction

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#811]
Description: Beacon of light vs LoS
How to reproduce: Sometimes while ur moving to LoS and healing ur partner Beacon of Light not working
How it should work: it should heal ALWAYS
Screenshot/video: https://www.youtube.com/watch?v=CMRTzPMz0m8
1st heal - fine
2nd heal - fine
3rd heal - fine
4th - nothing, 0 heal
5th - fine

**Comment by Fulgurancex** [comment]
https://streamable.com/3q5xef
BoL also not healing sometimes while in range
