### ISSUE TITLE
[Deathbringer's Will] Visual Bug

### ISSUE THREAD

**Issue by wudangIO** [SallyWhitemane/Mograine#82]
**Description:**
The very famous, ICC item [Deathbringer's Will] , creates a bug. When Deathbringer's Will procs and the shapeshift occurs, the weapon on the off-hand visually dissapears. It occurs only when shapeshifting occurs and than it remains that way after shapeshift ended.

**How to reproduce:** Test on a melee dualwielding class. Equip 2 melee weapons and the trinket. Attack a target until trinket ability procs and shapeshift occurs. Watch bug resulting in visual loss of weapon. Right click buff effect away. Weapon does not reappear.

**How it should work:**
I believe weapon shouldn't disappear at all, but even if thats not posible somehow, it should reappear once the effect wears off.

**Comment by SallyWhitemane** [comment]
It happened on retail, https://www.wowhead.com/item=50362/deathbringers-will#comments:id=1022691;80.
