### ISSUE TITLE
[Quest] Missing Clear the way

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#821]
Description:

Missing Quest in Chillwind Camp Western Plaguelands - "Clear the way" issued by Commander Ashlam Valorfist.

How to reproduce:

Talk to the NPC?

How it should work:

You should be able to just accept the quest, i'm not sure if it's requiring a breadcrumb quest to send you to Chillwind Camp or not.

**Comment by alexspew** [comment]
Invalid. You are required to take A Call to Arms: The Plaguelands! from Crier Goodman in Stormwind.
