### ISSUE TITLE
[Quest] [WG] Toppling the towers is horde version when player is alliance 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#822]
Descritpion:My toppling the towers q is the horde version so I can't turn it in. Tried to abandon and get it again but I still get the horde version                                          How it should work: I get the alliance version so I can turn it in

![492B0DAE-8D3C-45DA-A48D-FC545A0A91FA](https://user-images.githubusercontent.com/78295842/108063020-48c6e680-7063-11eb-95fb-a58375030274.png)

**Comment by alexspew** [comment]
Hi! This should be resolved on next server restart.
