### ISSUE TITLE
[Quest][Dungeon] Thrall in Escape from Durnhole can’t be interacted with

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#829]
**Description:
Doing quest to finish old hillsbrad and go to black morass, but I cant do this quest because thrall just wont give me the option to make him follow me.

How To Reproduce: 
When I found the bug, I was just solo'ing old hillsbrad to do black morass. I've seen some people talk about it.

How it should work:

You should be able to talk to the NPC and then he would start to run out of durnholde keep and to tabetha.

Screenshot:
![88D6E37E-7B13-481E-A1F0-4650A0131B22](https://user-images.githubusercontent.com/78295842/108069817-78c6b780-706c-11eb-85dd-533f434e425f.png)

Anna note: he did the quest with 5 barrels before that btw

**Comment by alexspew** [comment]
Player need to ride with dragon to the castle -> do 5 barrels quest -> kill the boss that walks down the stairs -> go to thrall -> turn in quest -> interact is active.
