### ISSUE TITLE
[Naxxramas] Kel'thuzad Phase 1: Soul Weaver's walk speed is too low

### ISSUE THREAD

**Issue by ghuser44** [SallyWhitemane/Mograine#83]
**Description:**
In Naxxramas, on Kel'thuzad Phase 1, the adds' movement speed is all over the place. Especially the **Soul Weaver** (16429), which moves at, like, 1% walk speed or something. They barely move, they're look static, basically. So, every time, they're being killed from max range without ever reaching us, which means we didn't get to test their ability: **Wail of Souls** (28459)

**How to reproduce:**
Engage Kel'thuzad in Naxx and watch the Soul Weaver movement speed/ spell cast.

**How it should work:**
**Soul Weaver** and **Soldier of the Frozen Wastes** (16427) are supposed to walk slowly towards the raid. The soldiers walk speed seemed the closest to being fine (they still need a small bump in walking speed, though), but the Soul Weavers weren't moving at all, basically. They should walk faster than they're doing now, but slower than, or as slow as, the Soldiers.

And while you're at it, check if they're casting **Wail of Souls** correctly, when in range of their aggro target.

**Comment by SallyWhitemane** [comment]
Wail of Souls seems fine. Rest of the issues will be fixed on next update, thanks for contribution!
