### ISSUE TITLE
Missing Mobs around quest area Malykriss: The Vile Hold (Icecrown)

### ISSUE THREAD

**Issue by kyotpls** [SallyWhitemane/Mograine#835]
**Description:**
There are mobs missing several places in Icecrown around Malykriss: The Vile Hold. The mobs are most consisted of Death Knight Initiate and Lumbering Atrocity, but also a few others like Iceskin Sentry and Lithe Stalkers. Most of the mobs are located in large packs and groups around Sapph, Rokir and Baelok. They have been here for several days and probably weeks already, but after logging in today I noticed they were missing.

**How to reproduce:**
Go to the location mentioned and observe that they are not respawning after a min or two.

**How it should work:**
The mobs should be located all through the given location, both for questing purposes, like:

_https://www.wowhead.com/quest=13160/stunning-view_
or 
_https://www.wowhead.com/quest=13147/matchmaker._

The large groups are also there to increase difficulty to finish quests like:

_https://www.wowhead.com/quest=13162/the-rider-of-frost_

**Screenshots/Video:**

https://www.youtube.com/watch?v=4xOWt_N6_q0&ab_channel=WoWQuest

![Skeleton Runesmiths](https://user-images.githubusercontent.com/37027911/108072734-8b8abd80-7067-11eb-8648-86747bd22add.jpg)

![Death Knight Initiate around Baelok](https://user-images.githubusercontent.com/37027911/108072810-a4936e80-7067-11eb-9cdc-23e81aeea1c2.jpg)

![MIssing Mobs Sapph](https://user-images.githubusercontent.com/37027911/108072762-96455280-7067-11eb-8b2c-08aae0ea3321.jpg)

**Comment by alexspew** [comment]
Hi! This should be fixed on next restart, the phasing will be removed if players have completed the riders quest chain. If it isn't fixed by wednesday, please PM me on discord :: alexs 
Thanks!
