### ISSUE TITLE
[Quest] Mastery of the crystals

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#837]
Description: Can't hand in the quest quest: Mastery of the Crystals there's multiple questgivers stacked on top of eachother but they are not interactable. 
How to reproduce: Finish quest and try to hand in (on live server) 
How it should work: Be able to the complete quest. 
Screenshot/video: https://imgur.com/a/8YiUnaY

**Comment by alexspew** [comment]
Duplicate npc deleted. Will be reflected in #changelog @discord when added. Thanks!
