### ISSUE TITLE
[Quest] Light won’t grant me vengeance 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#839]
**Description:** The quest Light Won't Grant Me Vengeance [ID:12904] incorrectly requires Making Something Out Of Nothing to be completed first.

**How to reproduce:** Go to where he is at Thrym's End in Zul'Drak.

**How it should work:** The quest should be doable alongside Making Something Out Of Nothing.

**Comment by alexspew** [comment]
Hi! This issue has been resolved. Updated quest for proper previous quest
