### ISSUE TITLE
Balance Druid - Solar Eclipse Bug

### ISSUE THREAD

**Issue by jcm9400** [SallyWhitemane/Mograine#84]
**Description:**
Starfire critical strikes are not proc'ing "Eclipse (Solar)" 100% as it should be

**How to reproduce:**
Spam Starfire on a target dummy

**How it should work:**
Starfire crits should automatically proc "Eclipse (Solar)"

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
