### ISSUE TITLE
[Quest] Betrayal NPC randomly despawns 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#841]
**Description:** [Quest ID:12713] Betrayal - The Blightblood Trolls you control for the quest despawn randomly and once you attempt to control another, all remaining ones despawn as well.

**How to reproduce:** Pick up the quest and go do it.

**How it should work:** The Blightblood Trolls should not despawn unless killed by Overlord Drakuru.

**Screenshot/video:** N/A.

**Comment by alexspew** [comment]
Invalid. Quest works as it should, however there was a duplicate NPC, which has been removed.
If you use the scepter too soon (before the raid warning), you will get control of a troll, but Drakuru will not attack. The troll will eventually despawn and then Drakuru will attack. The scepter has a longish cooldown, so you will be stuck soloing Drakuru. He simply stands in the center and casts shadow bolts and eventually Blight Crystals.
