### ISSUE TITLE
[Druid][Balance] Eclipse (Solar) has no 30 sec internal CD

### ISSUE THREAD

**Issue by ghuser44** [SallyWhitemane/Mograine#85]
**Description:**
Eclipse (Solar) (48517) has no **30** sec internal CD. Right now, I can proc it as soon as its duration of 15 sec ends. I shouldn't be able to proc it again for 15 more seconds, after the buff ends. Yet, in PTR, I can.

_P.S.: Spamming Starfire doesn't seem to refresh the solar buff, but it can proc it again, after it ends, immediately._

**The bug:** https://www.youtube.com/watch?v=quq5nCKNXFo&ab_channel=CraftyMind

**How to reproduce:**
- Get any addon to track the iCD of Eclipse (Solar). I used NeedToKnow.
- Spam Starfire until Eclipse (Solar) procs.
- Spam Starfire after Eclipse (Solar) ends, during the following 15 sec, where it should be still on CD.
- Notice it proccing even though the 30 iCD timer still didn't run out.

**How it should work:**
Each of the 2 Eclipses (Lunar and Solar) should have a **30 sec iCD**, independent of one another, that starts from the moment they proc. This is even stated in the tooltip of the talent **Eclipse** (48525). After proccing, the Eclipse that procs - Lunar or Solar - should go on an internal CD of 30 sec, during which it cannot proc again.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
