### ISSUE TITLE
The fishing daily Quest "Shrimpin' Ain't easy" is bugged

### ISSUE THREAD

**Issue by Starcallerx** [SallyWhitemane/Mograine#852]
**Description:**
The fishing daily Quest "Shrimpin' Ain't Easy" is bugged as the required fish "Bloated Barbed Gill Trout" does not appear while fishing. I cast for more than 100 times yet no fish.

**How to reproduce:**
1. Pick up the quest "Shrimpin' Ain't Easy" from NPC "Old man Barlo" outside Shattrath city.
2. Go to Zangarmarsh and start fishing. (The fish has no specific spawn point according to Wowhead and can be fished anywhere in Zangarmarsh)
3. Notice the fish does not appear.

**How it should work:**
The fish "Bloated Barbed Gill Trout" should appear while fishing if you have the quest "Shrimpin' Ain't easy" in your questlog. Also according to Wowhead, the fish has a very high chance of appearing.

**Useful Link**
Wowhead link in case need more info: https://www.wowhead.com/quest=11668/shrimpin-aint-easy#comments

**Comment by alexspew** [comment]
Fixed in next server update.
