### ISSUE TITLE
[Fishing] Achievement The Coin Master not doable

### ISSUE THREAD

**Issue by ruineroffun** [SallyWhitemane/Mograine#856]
Description:
There are two possible reasons why fishing the wanted coins for the achievement The Coin Master does not work. First possible reason is too high of a fishing level and more likely reason why the achievement is bugged is the recent update stating "Massive Loot Update - fixed fishing for all zones." At the moment since yesterday after 1000 casts I have gotten only gold coins and one (1) specific silver coin over and over again (A Peasant's Silver coin). Before this few days ago I was able to get bronze coins and different silver coins. 

Given the fact that after 1000 casts I have only gotten gold coins and one specific silver coin over and over again among the fish you get, I must be the unluckiest person in the world if the loot table is working correctly at the moment. 

How to reproduce:
Fish in dalaran coin pond.

How it should work:
You should be able to catch all the coins in bronze, silver and gold tier even if you have already gotten them.
**Gold Coins 0.44% (x15)
Silver Coins 0.89% (x15)
Copper Coins 0.89% (x23)
Fountain Goldfish 55.56%
Bent Fishing Hook 4.44%

**Copied straight from retail time wowhead comment for possibilities of catches from the pond.

**Comment by alexspew** [comment]
Hi, coins were not touched in the fishing update. However I have gone over the drop rates and concluded they were too low, i've made an update to all coins in fountain. No eta when update is live, check #changelog on discord for when it's being applied. Thank you.
