### ISSUE TITLE
Resilience PVP Problems

### ISSUE THREAD

**Issue by Hate123HGH** [SallyWhitemane/Mograine#860]
**Description:**
I am a rogue with full PVP gear and 800 resi, and when I'm fighting people in 1v1's it feels like if I was a casually geared pve player which isn't the case at all. At this point in the game with 800 resi I should be unkillable... but for example a 2k gs 14k hp rogue was able to kill me in opener without an issue, I'm getting 3 shot by dk's and warriors in 1v1's with 800 RESI!

**How to reproduce:**
I'm no DEV expert but you could try making resilience matter lol.

**How it should work:**
 At this point in the game with 800 resi I should be unkillable... BY undergeared pvers lol.

**Comment by cachocarne** [comment]
I have 765 resilience but keep on receiving 3k-4k hits all the time. I understand this can happen on some situations, but feels a little too much, especially at a state in patch where there are not so many ArPen items etc. I cannot prove this to be wrong, it's more a feeling. Will try to collect some screenshots and see if it's working as intended or not.

**Comment by Zeorgbugfinder** [comment]
welcome to deadly season
