### ISSUE TITLE
[CHAT][MOB] Houndmaster Loksey

### ISSUE THREAD

**Issue by Degatien** [SallyWhitemane/Mograine#862]
**Description:**
Houndmaster Loksey spams "release the hounds

**How to reproduce:**
Go into Scarlet Monastery -> Go to Houndmaster

**How it should work:**
One bark only when fight starts.
![image](https://user-images.githubusercontent.com/32513421/108605575-227fae80-73b5-11eb-9b66-0940415a5d32.png)

**Comment by alexspew** [comment]
Hi! This has been fixed. Should be applied during Wednesday. Was missing non-repeat flag on event
