### ISSUE TITLE
[MOB][SPAWN] Mob spawn double

### ISSUE THREAD

**Issue by Degatien** [SallyWhitemane/Mograine#864]
**Description:**
Many creatures in the world are spawned in multiples of two. 

**How to reproduce:**

**How it should work:**
Creatures should spawn as one mob. Not two with one inside of the other.

![image](https://user-images.githubusercontent.com/32513421/108605632-a33eaa80-73b5-11eb-825d-c23969beb791.png)

**Comment by scrublama** [comment]
same as #773

**Comment by herbhenk** [comment]
duplicate: https://github.com/SallyWhitemane/Mograine/issues/1195
