### ISSUE TITLE
[Quest][TBC] The Great Moongraze Hunt

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#869]
Quest Bug
Cause CTD on every turn-in attempt
Quest: The Great Moongraze Hunt
Location: Azuremyst Isle
Whenever I attempt to turn this quest in I am immediately logged out. Happens every time I try.
![BD79E761-B462-425F-A5E6-26F48A906816](https://user-images.githubusercontent.com/78295842/108618039-788b3b00-7423-11eb-92a5-7064c0cc6948.png)
Just opening the dialogue makes me crash. Unable to pick a reward.

**Comment by alexspew** [comment]
Unable to reproduce error, please delete cache if this still happens or make a GM ticket.
