### ISSUE TITLE
Metanoia

### ISSUE THREAD

**Issue by WubWub24** [SallyWhitemane/Mograine#87]
**Description:**Metanoia 57524

Normaly its stackable , and last in all zones 
**How to reproduce:**

Picture from Blizz
**How it should work:**
![asdsadsasa](https://user-images.githubusercontent.com/73794095/102006603-f566ae00-3d2a-11eb-89cc-2f37a80f8800.jpg)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
