### ISSUE TITLE
[Warlock] SoCorr (rank 3) not autolearned

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#871]
Description: Seed of Corruption (rank 3) is not autolearned for warlocks. Noticed this when I visited trainer.
How to reproduce: Level warlock to 80 I guess...
How it should work: All abilities should be autolearned except some special abilities like warlock mounts, but this ability should be autolearned.

**Comment by cachocarne** [comment]
I can confirm this. Found out by coincidence when the addon from a team colleage at BG autowhispered to me. Upon visit to my trainer, I saw I had to pay for learning the Rank 3.
