### ISSUE TITLE
[Paladin] HoF doesn’t remove Freezing Trap from Hunter 

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#872]
Description: You cant use Hand of freedome while in an ice trap
How to reproduce: do it....
How it should work: you should and this is a massive nerf to ret pvp since i cant remove stunns from my parter while I´m in cc pls fix fast ty

**Comment by Platinumcoated** [comment]
perhabs this is what OP meant? 
https://github.com/SunwellTracker/issues/issues/846
