### ISSUE TITLE
Orc Axe Specialization

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#88]
**Description:**
When I equip an axe in my main hand or offhand , I don't get the 3 expertise from the orc racial.

**How to reproduce:**
Make an orc,equip an axe and see if you get 5 expertise

**How it should work:**
you should get 5 expertise when you have axe/fist weapon equipped as an orc

**Comment by RemoteDefinition** [comment]
2h Axes from what I've seen do not give the 5 expertise as well.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!

**Comment by Fulgurancex** [comment]
Any update on this ? Stil hasn't been fixed.
