### ISSUE TITLE
[Rogue] Glyph of Blurred speed 

### ISSUE THREAD

**Issue by Fulgurancex** [SallyWhitemane/Mograine#891]
**Description:**
Glyph of Blurred speed not working properly?

**How to reproduce:**
Have said glyph equipped, be on water, like walk on it because of the glyph, mount up, and it stops working. (ground mount)

**How it should work:**
As long as sprint is active, with said glyph equipped, you should be able to walk on water even mounted.
https://www.wowhead.com/item=43379/charred-glyph#comments

By 46703 (2,087 – 3·18) on 2008/10/19 (Patch 3.0.2)
As of this post, popping sprint and then mounting allows you to run over water with a mount.

Let's hope this doesn't get nerfed :<

**Comment by lineagedr** [comment]
Not that it matters but 
```
As of 3.2.0 you can no longer mount while running on water, you will simply fall through it. 
And as an insult to injury you will no longer be able to sprint across water for the duration of that sprint :( 
A sad day for rogues indeed.Not as epic as swirlyball..but still a sad day when all of our fun toys get nerfed =/
```
https://www.wowhead.com/item=43379/charred-glyph#comments:id=835016

I guess that's why the spell 61922 had ```AURA_INTERRUPT_FLAG_MOUNT``` flag.
