### ISSUE TITLE
Hunter's Mark not revealing stealthed players.

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#892]
**Description:**
 Hunter's spell "Hunter's Mark" don't reveal stealth players ( rogues ) even tho it should. 

**How to reproduce:**
 in was in bg, marking stealth targets, which then went in stealth and you couldn't see them. You should log a hunter, duel a rogue or try it on an enemy faction rogue, Put hunter mark on him, let him vanish/restealth,, and see that it doesnt work

**How it should work:** 
Places the Hunter's Mark on the target, increasing the ranged damage of all attackers against that target by x%. The target can always be seen and tracked by the Hunter.

**Comment by SallyWhitemane** [comment]
https://www.mmo-champion.com/threads/877510-Hunters-mark-amp-vanish
Patch 1.12.0:
- Vanish now removes effects that allow the caster to always remain aware of their target (currently Hunter's Mark and Mind Vision).
