### ISSUE TITLE
Bug phase

### ISSUE THREAD

**Issue by Veresa** [SallyWhitemane/Mograine#897]
Even with the same quests done it isn't possible to see each other being in different phases.
We had to do the quest "The Fate of Bloodbane" but it wasn't possible due to this phase issue.
The NPC is Orbaz Bloodbane, the area is under Icecrown Citadel, i'm a draenei shaman lvl 80.

Go to the place with another person after doing the chain and check if you can see each other.

Anyone who has done the same quests should be able to see themselves in the appropriate areas, such as for the Sons of Hodir chain and the like.

**Comment by alexspew** [comment]
Hi Veresa, did you both complete all rider quests?

**Comment by Veresa** [comment]
Which rider quests?
We do all Vereth's the Cunning quests, except the last that we had to do it together.

**Comment by alexspew** [comment]
The Rider of The Unholy/Blood/Frost

If you've both done these 3 quests, it might seem like the phasing quest fix isn't live yet, which I apologize for. It should be live on wednesday

**Comment by Veresa** [comment]
Oh yes we both did those 3 quests, not together, and in "entering" the next quest area we ended up in different stages.
Thx :D we'll be waiting without problems until wednesday.

**Comment by alexspew** [comment]
Hi, as this issue has been up for a couple of days since wednesday and added a phase fix for mob. I'm gonna say this is fixed. Thanks!
