### ISSUE TITLE
Well Fed and Kreeg's Stout Beatdown

### ISSUE THREAD

**Issue by Synful-Syn** [SallyWhitemane/Mograine#9]
"Kreeg's Stout Beatdown": 22790, item is 18284, used to stack with all buffs back on 2.4.3 according to a wowhead comment but 2 other comments mentions on 3.2.2 and 3.3 that changes/replace the Well Fed.
I find it strange that it is a debuff that should replace Well Fed. Because it is a debuff, Ice Block removes it and I don't think it is supposed to be a debuff.
https://www.wowhead.com/item=18284/kreegs-stout-beatdown

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
