### ISSUE TITLE
[Skinning] Bug on specific NPC - Ghostpaw Alpha not skinnable

### ISSUE THREAD

**Issue by cachocarne** [SallyWhitemane/Mograine#900]
**Description:**
The Ghostpaw Alpha (https://classic.wowhead.com/npc=3825/ghostpaw-alpha#skinning) wolves in Ashenvale (and probably other kind of similar creatures with slightly different name) are not skinnable after killed and looted.

**How to reproduce:**
Kill and loot the beast, then proceed to skin it to obtain leather. It won't let you skin it.
(https://i.imgur.com/mHxkG05.png)

**How it should work:**
Beast should be skinnable.

**Comment by Raulfin** [comment]
Dup of #261

**Comment by alexspew** [comment]
Hi, this is an on going issue. Please use #261 for further information.
