### ISSUE TITLE
Alliance having 5 / 6 healers in 10 man BGs

### ISSUE THREAD

**Issue by Stormmenace** [SallyWhitemane/Mograine#903]
**Description:**
I've been in several BG's now where alliance have almost had more healers than DPS, whilst the horde is given 1 or 2. Surely there is an algorithm to sort this?!

**How to reproduce:**

**How it should work:**

**Comment by cachocarne** [comment]
I doubt there is such a thing as distributing BG groups by class/spec. Either is premade or just (bad) luck, I would say. Plus, I think the profile of healer player is more common in Alliance than Horde, if there is such a thing.
