### ISSUE TITLE
Blade of Unquenched Thirst spell power scaling

### ISSUE THREAD

**Issue by kindauncanny** [SallyWhitemane/Mograine#91]
**Description:**
Blade of Unquenched Thirst's effect is supposed to be scaling with spell power to a certain degree.

**How to reproduce:**
Use any class with spell power and no scaling talents (an example would be Priest with no talents taken) and attack in melee, or use rogue with dual wielding those and some spell power pieces to see whether there is a difference.

**How it should work:**
The proc should be scaling with spell power.
There are comments about the scaling on Wowhead concerning 2.x.x and 4.x.x as well, but I'll paste a comment that's relevant to Wrath.
![procscale](https://user-images.githubusercontent.com/75952683/102023815-08b36100-3d9f-11eb-82ed-faa626c91fa4.png)

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
