### ISSUE TITLE
Set items do not count as set after transmog!

### ISSUE THREAD

**Issue by enheken** [SallyWhitemane/Mograine#914]
**Description:**
I did transmog my t7 head piece to day and after it the item did no longer count towards the set bonus. I have not tested if my chain heal and healing wave is 5% stronger or weaker now
![transmog](https://user-images.githubusercontent.com/74271513/108992504-b2657700-7699-11eb-89fc-00e2025b3207.jpg)
**How to reproduce:**
Transmog a set item.

**How it should work:**
The item should keep it status as part of a set.

**Comment by scrublama** [comment]
a visual bug.
Like on a majority, if not all servers, with implemented transmog for wotlk.
but set bonuses should still work regardless
please test if bonuses actually disappear
