### ISSUE TITLE
[Naxxramas] Anub'arak Locust Swarm

### ISSUE THREAD

**Issue by Rvrwnn** [SallyWhitemane/Mograine#92]
**Description:** Anub'arak seems to not be slowing down after casting his ability "Locust Swarm".
Proof: https://www.twitch.tv/videos/836345984 (around 1:02:58)

**How to reproduce:** Start fight with Anub and wait until he casts Locust Swarm. Then move around and check his movement speed.

**How it should work:** "Anub'Rekhan releases a locust swarm, slowing his movement by 40% and damaging all nearby enemies. Nearby enemies are unable to attack or cast spells." (https://www.wowhead.com/spell=28785/locust-swarm?dd=3&ddsize=10#used-by-npc)

**Comment by SallyWhitemane** [comment]
Looks fine, in 25man boss uses this version of the spell https://www.wowhead.com/spell=54021/locust-swarm, it slows him down by 25%.
