### ISSUE TITLE
Blessed Hands talent in the Holy Paladin tree is bugged

### ISSUE THREAD

**Issue by dreamk33per** [SallyWhitemane/Mograine#93]
Paladin talent Blessed Hands in the Holy tree does not affect Hand of Salvation spell's effect, but it should as it is says in the description. 
You can see in the picture that the mana cost is affected as it should when the talent is taken, but not the effect itself.
There is a link to the spell's base description: https://wotlk-twinhead.twinstar.cz/?spell=1038
![Blessed hands bug](https://user-images.githubusercontent.com/72185738/102027071-95afe780-3daa-11eb-9223-39fb4691bb3f.png)

**Comment by SallyWhitemane** [comment]
Effect works correctly but tooltip is unchanged.
