### ISSUE TITLE
Mixology

### ISSUE THREAD

**Issue by whispersz** [SallyWhitemane/Mograine#930]
**Description:**
When reaching alchemy skill 50, you can learn Mixology spell from trainer. Problem is that if you let your alchemy skill at level 50, Mixology wont double the duration of the flasks and elixirs. From what i understood you gain the increased effect and duration only if your skill is high enough to make Northrend flasks.

**How to reproduce:**
Create a char, learn Alchemy, skill it to 50 and learn Mixology from an alchemy trainer. After that use a Flask of frost wyrm or endless rage. You will see that duration of the flask is still 60 minutes.

**How it should work:**
When you are able to learn Mixology, it should give you increased duration and effect of the flask you are using. It does not matter if your alchemy is 50 or 450. Effect should be the same.

**Comment by Raulfin** [comment]
How it should work:
Any flask or elixir that **can be created by the Alchemist** has double duration when it is consumed.
you should only get the bonus on a flask you know the recipie for.
