### ISSUE TITLE
Shield of Righteousness block value bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#948]
**Description :**

I'm using a trinket called "Gnomeregan Auto-Blocker 600" which gives 117 block value in passive and 200 in active for 40 seconds. I'm using aswell "Libram of Obstruction" which gives 352 block value for 10 seconds. 

**How to reproduce :**

The problem happens when I'm using both of them active from Auto-Blocker and Libram passive's proc, it only takes into account the best value (so 352 block value), instead of 552 block value. I've got a couple of screens to show you the numbers of my damage / the damage reduction from block (which is shown on character's sheet).

**

How it should work: **

My "Shield of Righteousness" should do more damage because it takes block value into account.

Screenshot :

(The three first screens show the shield block value evolution and the damage from "Shield of Righteousness" and the two last show the name of buffs - Which can be stacked)

![ScreenVraiVrai](https://user-images.githubusercontent.com/58514021/109400880-92f57500-794b-11eb-908a-d70be8eb5185.png)

**Comment by danniellos94** [comment]
There is something like block value cap that's why.  Here a proof https://youtu.be/7xuJmsQv6nM 1:41+.
Block value cap is 2760.
After that only strength,arp and warrior shield block glyph increase the damage.

**Comment by Raulfin** [comment]
can see in the SS that each trink is adding it's value correctly, but your block value is capped @18.66%

**Comment by alexspew** [comment]
Hi, as danniellos94 says, there is a block cap value.
