### ISSUE TITLE
[Warrior] Deep wounds is munching 

### ISSUE THREAD

**Issue by Dunderj** [SallyWhitemane/Mograine#95]
**Description:**
Deep Wounds is munching and consequently dealing too low dmg

**How to reproduce:**
First example I play arms and crit with an ability + whitehit at the same time and the server only register one crit for Deep Wounds damage. Check submitted screenshots from PTR:
![dw no munch](https://user-images.githubusercontent.com/38737831/102101392-db13f980-3e2a-11eb-97a6-b89957c6ec82.png) ![dw munch](https://user-images.githubusercontent.com/38737831/102101406-e109da80-3e2a-11eb-98a3-2a63ec40e387.png)

Second example: Whirlwind with 2 weapons, in first screenshot one crit and second screenshot when both crits
![ww no munch](https://user-images.githubusercontent.com/38737831/102102994-b6b91c80-3e2c-11eb-85eb-913f3b604879.png) ![ww munch](https://user-images.githubusercontent.com/38737831/102102976-b1f46880-3e2c-11eb-8241-07f1a7c50f82.png) 

**How it should work:**
Deep Wounds should stack up normally with fast frequent crits.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
