### ISSUE TITLE
Auto loot bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#950]
**Description:**
Auto Loot won't do correct thing right. 
**How to reproduce:**
Looting dead target have click it twice be active when auto looting 

**How it should work:**

Should auto loot every target in game when you go into interface click auto targets then kill a mob then loot should auto loot the target then clicking them one by one Screenshot/Video:https://www.youtube.com/watch?v=3CiRwZYWJO4&feature=youtu.be

**Comment by Raulfin** [comment]
You likely have an addon affecting this. something like Xloot or AutoLoot or something else.
