### ISSUE TITLE
Skinning Ghostpaw Alpha

### ISSUE THREAD

**Issue by Nyapaweon** [SallyWhitemane/Mograine#954]
Description:  skinning Ghostpaw Alpha

How to reproduce: Kill any Ghostpaw Alpha and loot the items then attempt to skin

How it should work: if the loot is grabbed from Ghostpaw Alpha it should be skinnable. 

Screenshot/video: https://prnt.sc/109e12r

**Comment by Raulfin** [comment]
dup of #261

**Comment by alexspew** [comment]
Hi, this is a known issue. Please use #261 for further information
