### ISSUE TITLE
Mirror of Truth not working in PVP

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#959]
Description: Mirror of Truth doesnt work in PVP. Works in PvE only.
How to reproduce: Try it in PVP.
How it should work: Should work in PvP.
Screenshot/video: Doesnt need

**Comment by Zeorgbugfinder** [comment]
1. It doesnt stack with anvil
2. It has "chance" to proc on crit so if ur unh DK hitting high resil target it barely procs every 2 min

Im pretty sure it works
