### ISSUE TITLE
[Illustration of the Dragon Soul] [Warlock] Proc bug.

### ISSUE THREAD

**Issue by zminchev** [SallyWhitemane/Mograine#96]
**Description:**
Trinket [ Illustration of the Dragon Soul ] procs when a damaging spell hits the target instead of when its casted. Warlock  [Corruption] spell also procs the trinket on every tick. Other Warlock DoTs don't seem to proc it though.

**How to reproduce:**
1. Cast any damaging spell with the trinket equipped.
2. Put Corruption on the target with the trinket equipped.

**How it should work:**
1. [ Illustration of the Dragon Soul ] should proc every time a spell is casted (damaging or a healing one), not when it hits the target.
2. The trinket should not proc off of Corruption ticks

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
