### ISSUE TITLE
Crescent-Tail Skullfis cannot be caught

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#966]
Description: 
The fish called [Crescent-Tail Skullfish] can not be caught, 1500+ fish caught, 0 [Crescent-Tail Skullfish]
how to reproduce : fish in deadwind pass.
How it should work: Fish can be caught

**Comment by alexspew** [comment]
Hi, this will be fixed hopefully on wednesday (next updates coming out). If it still isn't, let me know on discord (alexs) thanks!
