### ISSUE TITLE
Saronite node disappearing bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#967]
Description:  
i'm pretty sure this saronite deposit is not working as intended 
How to reproduce: 
you can go there where shown in the video and check yourself
How it should work:
 i think you should be able to mine that vein
Screenshot/video:
https://www.youtube.com/watch?v=5dXyNkHWRSw

**Comment by alexspew** [comment]
Hi!, Not a bug. Different phasing required.
