### ISSUE TITLE
Naxxramas Bossfight reset after wipe bug

### ISSUE THREAD

**Issue by NanuuDK** [SallyWhitemane/Mograine#97]
**Description:** When wiping on a boss (whole Raid dead) in Naxxramas, the encounter does not reset. The bosses just stand there with whatever HP they have left. You get the msg: "Unable to zone in while an encounter is in progress."

**How to reproduce:** Pull a boss and wipe the whole raid.

**How it should work:** After a wipe the Boss resets himself.

**Comment by SallyWhitemane** [comment]
Can i get any more info? Which encounter didn't reset? Can't reproduce the issue now.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
