### ISSUE TITLE
[Quest] Where in the wolrd is Hemet Nesingwary?

### ISSUE THREAD

**Issue by Matija5** [SallyWhitemane/Mograine#98]
**Description:**
1st of all the speed of the heli is way to slow, 2nd of all there are supposed to be two planes attacking you and thirdly the animation of "the driver" Monte Muzzelshot is wrong he's just laying dead hanging as he would if he was on the ground.

**How to reproduce:**
Take quest and talk to NPC to start flying and you'll see everything

**How it should work:**
Speed of the heli should be faster, 2 additional planes should come and keep shooting rockets at you and Monthe Muzzleshot should have more of a "bent over" animation when haning from the tree which is much more realistic 

https://www.youtube.com/watch?v=2YXu_vzrChE 
here is a video for a reference
at 0:40 you can see the additional 2 planes that appeared, that are shooting you down
at 1:19 you can see the position of NPC
and thru most of the video you can see the speed of the plane

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
