### ISSUE TITLE
[Death Knight] [Pet] wrong damage values

### ISSUE THREAD

**Issue by Dominiklas** [SallyWhitemane/Mograine#987]
**Description:**

Death Knight's unholy [talent/spell](https://wotlkdb.com/?spell=49206) is bugged. Currently Gargoyle does WAY TOO much damage, example from whitemane (please keep it mind that's naxx content and values!)
![image](https://user-images.githubusercontent.com/45073043/109963699-00f3c080-7ced-11eb-8790-2eb0aa1a24cd.png)

**How to reproduce:**
- just pop garg on speed pot + unh presence and see numbers

**How it should work:**
Screen shot with dmg from retail DURING ICC:
![image](https://user-images.githubusercontent.com/45073043/109963826-22ed4300-7ced-11eb-8f0e-6053a60ad338.png)
Take note that: naxx geared unholy dk DOES 84K dmg more with 3min CD pet than ICC geared death knight!:
link to [retail logs](http://www.worldoflogs.com/reports/b2k9jsgjwxc5urmd/details/64/?s=2734&e=2947)
link to [whitemane logs](http://www.worldoflogs.com/reports/rt-peztxm17cwyhblvj/details/80/?s=3609&e=3701)

Whitemane's gargoyle just spam casts gargoyle strike, while retail does cast+melee swing etc. Considering item difference currently gargoyle does 3-4 times more damage than it should do

**Comment by danniellos94** [comment]
The autoatack from a gargoyle is a well known bug from retail which could be avoided by turning back and summonning the gargoyle. You can maybe find this in old elitist jerk archivum data. Also need to take the point if dk had haste buffs/potions/bloodlust/unholy pressence, engineering. With 0 haste from items on dummy gargoyle should do 12 casts in blood pressence. Also what I would say on retail gargoyle had sometimes stop casting for like 0.2-0.3 seconds but no idea if it was a bug or not.

Proof that ebon gargoyle can go under 1 second casting and have a small delay sometimes

https://www.mmo-champion.com/threads/697868-Gargoyal-and-Haste

https://www.youtube.com/watch?v=jA5I7jCqyfg

Also

"No raid buffs, only HoW, procs were a bit random, so I only summoned the gargoyle when no procs were up.

Strength 1719, Attack Power 4384. No diseases on target.

In Blood Pres, over its duration it did:
11 Gargoyle Strikes (ave=1788, all hits, no crits), 1 Melee (glancing=409). Total damage done=20077. Damage per second of 692." 

Means that with 0 haste and without attack bug gargoyle should do 12 casts. Needed to be tested how much it does here.
