### ISSUE TITLE
[Quest]  [Defending The Vanguard]

### ISSUE THREAD

**Issue by Matija5** [SallyWhitemane/Mograine#99]
**Description:**
The bug is not in the quest itself but rather in the NPC around the quest zones, theres bunch of paladins that are supposed to be fighting against nerubians but the paladins are one shoting the them which means only mobs that are alive a thoes that are far away from the paladin NPCS

**How to reproduce:**
Just go to quest area and you'll see, if all dead taunt one spider and bring it to NPC

**How it should work:**
NPCs should be in combat with the nerubians but they are not supposed to be one shoting them, I can't really find the source of how much dmg they should be doing or how long does it take them to kill the mob.

**Comment by SallyWhitemane** [comment]
Issue will be fixed with next update, thanks for contribution!
